"""
This type stub file was generated by pyright.
"""

from typing import TypeAlias
from torch import Tensor

TensorListList: TypeAlias = list[list[Tensor | None]]
Indices: TypeAlias = list[int]
_foreach_supported_types = ...
