"""
This type stub file was generated by pyright.
"""

import torch

aten = ...
_FLOAT_TYPES = ...
_VIEW_OPS = ...
_CREATE_OPS = ...
_IGNORE_OPS = ...
def get_compute_time(func_packet, args, kwargs, out, out_dtypes) -> float:
    """
    Estimates the compute time of an aten operator.

    Args:
        func_packet: The operator overload packet.
        args: The arguments to the operator.
        kwargs: The keyword arguments to the operator.
        out: The output of the operator.
        out_dtypes: The output data types.

    Returns:
        float: The estimated compute time in nanoseconds.
    """
    ...

def get_num_bytes(t: torch.Tensor) -> int:
    """
    Calculates the memory consumption of a tensor.

    Args:
        t (torch.Tensor): The input tensor.

    Returns:
        int: The memory consumption of the tensor in bytes.
    """
    ...

def get_transfer_time(flat_args_kwargs, flat_outs) -> float:
    """
    Estimates the memory transfer time of input and output tensors.

    Args:
        flat_args_kwargs (List[torch.Tensor]): The flat list of arguments and keyword arguments.
        flat_outs (List[torch.Tensor]): The flat list of outputs.

    Returns:
        float: The estimated memory transfer time in nanoseconds.
    """
    ...

