"""
This type stub file was generated by pyright.
"""

import torch
import torch.nn as nn
from typing import Generic, TYPE_CHECKING, TypeVar
from torch.distributed._composable_state import _State
from ._fsdp_api import MixedPrecisionPolicy

if TYPE_CHECKING:
    ...
logger = ...
_StateType = TypeVar("_StateType", bound="FSDPState")
class FSDPStateContext(Generic[_StateType]):
    """This has state shared across FSDP states."""
    def __init__(self) -> None:
        ...
    


def disable_if_config_true(func) -> _Wrapped[..., Any, ..., Callable[..., Any] | Any]:
    ...

class FSDPState(_State):
    _state_name: str = ...
    def __init__(self) -> None:
        ...
    
    def init(self, modules: tuple[nn.Module, ...], device: torch.device, mp_policy: MixedPrecisionPolicy, auto_reshard_after_forward: bool) -> None:
        ...
    


