"""
This type stub file was generated by pyright.
"""

import types
import torch
from collections import OrderedDict
from collections.abc import Callable, Hashable, Iterable, Iterator, Mapping, Sequence
from itertools import repeat as _repeat
from operator import eq, ne
from typing import Any, TYPE_CHECKING, TypeVar
from ..utils import dict_keys
from . import _collections as _collections, builtins as builtins, functools as functools, itertools as itertools, operator as operator, os as os, pytree as pytree, struct as struct, sys as sys, torch_c_nn as torch_c_nn, traceback as traceback
from torch.overrides import BaseTorchFunctionMode

"""
Python polyfills for common builtins.
"""
T = TypeVar("T")
U = TypeVar("U")
C = TypeVar("C")
if TYPE_CHECKING:
    ...
class NoEnterTorchFunctionMode(BaseTorchFunctionMode):
    def __enter__(self) -> None:
        ...
    


def index(iterator: Iterator[T], item: T, start: int = ..., end: int | None = ...) -> int:
    ...

def repeat(item: T, count: int) -> Iterator[T]:
    ...

def radians(x: float) -> float:
    ...

def impl_IS_MAPPING(a: object) -> bool:
    ...

def impl_MATCH_SEQUENCE(a: object) -> bool:
    ...

def impl_MATCH_CLASS(subject: object, cls: type, nargs: int, kwargs: tuple[str, ...]) -> tuple[object, ...] | None:
    ...

def impl_MATCH_KEYS(obj: Mapping[T, U], keys: tuple[T, ...]) -> tuple[U, ...] | None:
    ...

def impl_CONTAINS_OP_fallback(a: T, b: Iterable[T]) -> bool:
    ...

def accumulate_grad(x: torch.Tensor, new_grad: torch.Tensor | None) -> None:
    ...

def list_cmp(op: Callable[[Any, Any], bool], left: Sequence[T], right: Sequence[T]) -> bool:
    """emulate `(1,2,3) > (1,2)` etc"""
    ...

def dict___eq__(d: dict[T, U], other: dict[T, U]) -> bool:
    ...

def set_symmetric_difference(set1: Iterable[T], set2: Iterable[T], cls: type[Any] = ...) -> Any:
    ...

def set_symmetric_difference_update(set1: set[T], set2: set[T]) -> None:
    ...

def set_isdisjoint(set1: set[T], set2: set[T]) -> bool:
    ...

def set_intersection(set1: set[T], *others: Iterable[T], cls: type[Any] = ...) -> Any:
    ...

def set_intersection_update(set1: set[T], *others: Iterable[T]) -> None:
    ...

def set_union(set1: set[T], *others: Iterable[T], cls: type[C] | None = ...) -> C | set[T]:
    ...

def set_update(set1: set[T], *others: Iterable[T]) -> set[T]:
    ...

def set_difference(set1: set[T], *others: Iterable[T], cls: type[Any] = ...) -> Any:
    ...

def set_difference_update(set1: set[T], *others: Iterable[T]) -> None:
    ...

def assert_dict_equal(self_: Any, d1: dict[T, U], d2: dict[T, U], msg: str | None = ...) -> None:
    ...

def assert_multi_line_equal(self_: Any, first: T, second: T, msg: str | None = ...) -> None:
    ...

def assert_sequence_equal(self_: Any, seq1: Sequence[T], seq2: Sequence[T], msg: str | None = ..., seq_type: type[Any] | None = ...) -> None:
    ...

def getattr_and_trace(*args: Any, **kwargs: Any) -> Any:
    ...

def mapping_get(obj: Mapping[T, U], key: T, value: U | None = ..., /) -> U | None:
    ...

def instantiate_user_defined_class_object(cls: type[T], /, *args: Any, **kwargs: Any) -> T:
    ...

def mutable_mapping_update(self, data: Mapping[T, U] | Iterable[tuple[T, U]] = ..., /, **kwargs: Any) -> None:
    ...

def construct_dict(cls: type[T], data: Mapping[object, object] | Iterable[tuple[object, object]] = ..., /, **kwargs: Any) -> T:
    ...

def foreach_map_fn(*args: Any) -> Any:
    ...

def foreach_lerp_inplace(self, end: list[torch.Tensor] | tuple[torch.Tensor, ...] | None, weight: Sequence[bool | complex | float | int]) -> None:
    ...

def foreach_pow_scalar(scalar: Any, exps: Sequence[bool | complex | float | int]) -> tuple[torch.Tensor, ...]:
    ...

def addcmul_inplace(self, tensor1: torch.Tensor, tensor2: torch.Tensor, value: Any) -> None:
    ...

def predicate(obj: object) -> bool:
    ...

def cmp_eq(a: object, b: object) -> bool:
    ...

def cmp_ne(a: object, b: object) -> bool:
    ...

def cmp_lt(a: Any, b: Any) -> bool:
    ...

def cmp_le(a: Any, b: Any) -> bool:
    ...

def cmp_gt(a: Any, b: Any) -> bool:
    ...

def cmp_ge(a: Any, b: Any) -> bool:
    ...

def group_tensors_by_device_and_dtype(tensorlistlist: list[list[torch.Tensor | None]], with_indices: bool = ...) -> dict[tuple[torch.device, torch.dtype], tuple[list[list[Any]], list[int]]]:
    """Pure Python implementation of torch._C._group_tensors_by_device_and_dtype.

    Groups tensors by their device and dtype. This is useful before sending
    tensors off to a foreach implementation, which requires tensors to be on
    one device and dtype.

    Args:
        tensorlistlist: A list of lists of tensors (tensors can be None).
        with_indices: If True, track original indices in the output.

    Returns:
        A dict mapping (device, dtype) tuples to (grouped_tensorlistlist, indices).
    """
    ...

