"""
This type stub file was generated by pyright.
"""

import torch.utils._pytree as python_pytree
from typing import TYPE_CHECKING
from types import ModuleType

if TYPE_CHECKING:
    ...
POLYFILLED_MODULE_NAMES: tuple[str, ...] = ...
if python_pytree._cxx_pytree_dynamo_traceable:
    ...
POLYFILLED_MODULES: tuple[ModuleType, ...] = ...
