"""
This type stub file was generated by pyright.
"""

import traceback
from traceback import StackSummary
from types import TracebackType
from ..decorators import substitute_in_graph

"""
Python polyfills for traceback
"""
__all__ = ["extract_tb", "clear_frames"]
@substitute_in_graph(traceback.extract_tb, can_constant_fold_through=True)
def extract_tb(tb: TracebackType | None, limit: int | None = ...) -> StackSummary:
    ...

@substitute_in_graph(traceback.clear_frames, can_constant_fold_through=True)
def clear_frames(tb: TracebackType | None) -> None:
    ...

