"""
This type stub file was generated by pyright.
"""

import torch
from typing import Any, NamedTuple, TYPE_CHECKING
from typing_extensions import ParamSpec, TypeVar
from torch._C._functorch import TransformType
from torch._ops import HigherOrderOperator
from collections.abc import Callable, Sequence
from torch._functorch.pyfunctorch import FuncTorchInterpreter, VmapInterpreter

if TYPE_CHECKING:
    ...
_P = ParamSpec("_P")
_R = TypeVar("_R")
class CustomFunctionHigherOrderOperator(HigherOrderOperator):
    def __init__(self) -> None:
        ...
    
    def __call__(self, autograd_function: type[torch.autograd.Function], *args: _P.args, **kwargs: _P.kwargs) -> Any:
        ...
    


custom_function_call = ...
@custom_function_call.py_impl(TransformType.Grad)
@custom_function_call.py_impl(TransformType.Jvp)
def custom_function_call_grad(interpreter: FuncTorchInterpreter, autograd_function: type[torch.autograd.Function], *operands: Any) -> Any:
    ...

def generate_single_level_function(interpreter: FuncTorchInterpreter, autograd_function: type[torch.autograd.Function]) -> type[torch.autograd.function._SingleLevelFunction]:
    ...

NO_OUT_DIMS = ...
def wrap_outputs_maintaining_identity(outputs: Any, unwrapped_inputs: Any, orig_inputs: Any, wrap_fn: Callable[..., Any], out_dims: Any = ...) -> Any:
    ...

class VmapInfo(NamedTuple):
    batch_size: int
    randomness: str
    ...


def has_overridden_vmap_rule(autograd_function: type[torch.autograd.Function]) -> bool:
    ...

def validate_vmap_returns_tuple_of_two_elements(result: Any) -> None:
    ...

@custom_function_call.py_impl(TransformType.Vmap)
def custom_function_call_vmap(interpreter: VmapInterpreter, autograd_function: type[torch.autograd.Function], *operands: Any, **kwargs: Any) -> Any:
    ...

def custom_function_call_vmap_helper(interpreter: VmapInterpreter, vmap_function: Callable[..., Any], op: Any, *operands: Any, **kwargs: Any) -> Any:
    ...

def unpack_outputs(outputs: tuple[Any, ...]) -> tuple[Any, Any]:
    ...

def custom_function_call_vmap_generate_rule(interpreter: VmapInterpreter, autograd_function: type[torch.autograd.Function], *operands: Any) -> Any:
    ...

@custom_function_call.py_impl(TransformType.Functionalize)
def custom_function_call_functionalize(interpreter: FuncTorchInterpreter, autograd_function: type[torch.autograd.Function], generate_vmap_rule: bool, *operands: Any) -> Any:
    ...

def vmapify_autograd_function(autograd_function: type[torch.autograd.Function], in_dims: Any, batch_size: int, randomness: str) -> type[torch.autograd.Function]:
    ...

def get_tangents_in_dims(input_dims: Any, tangents: tuple[Any, ...]) -> Any:
    ...

class WrappedCtx:
    _pt_reserved_attrs: tuple[str, ...] = ...
    def __init__(self, ctx: Any) -> None:
        ...
    
    def __getattr__(self, name: str) -> Any:
        ...
    
    def __setattr__(self, name: str, value: Any) -> None:
        ...
    


class CtxWithSavedTensors(WrappedCtx):
    _pt_reserved_attrs = ...
    def __init__(self, ctx: Any, new_saved_tensors: Sequence[torch.Tensor]) -> None:
        ...
    
    @property
    def saved_tensors(self) -> Sequence[torch.Tensor]:
        ...
    


class CtxCustomSave(WrappedCtx):
    _pt_reserved_attrs = ...
    def __init__(self, ctx: Any, current_level: int) -> None:
        ...
    
    def save_for_backward(self, *tensors: torch.Tensor) -> None:
        ...
    
    def save_for_forward(self, *tensors: torch.Tensor) -> None:
        ...
    


def reductify(grad_input: torch.Tensor | tuple[torch.Tensor, ...], grad_input_bdim: int | tuple[int, ...], input_bdim: int | tuple[int, ...], batch_size: int, target_shape_without_bdim_to_reduce_to: Any = ...) -> tuple[Any, ...]:
    ...

def reductify_leaf(grad_input: torch.Tensor | None, grad_input_bdim: int | None, input_bdim: int | None, batch_size: int, target_shape_without_bdim_to_reduce_to: Any = ...) -> torch.Tensor | None:
    ...

def autograd_function_forward_rewritten(original_forward: Callable[_P, _R], original_setup_context: Callable[..., Any]) -> Callable[..., _R]:
    ...

class AutogradFunctionApply(HigherOrderOperator):
    def __init__(self) -> None:
        ...
    
    def __call__(self, fwd: torch.fx.GraphModule, bwd: torch.fx.GraphModule, *fwd_args: Any, **fwd_kwargs: Any) -> Any:
        class ApplyTemplate(torch.autograd.Function):
            ...
        
        
    


autograd_function_apply = ...
class DynamoAutogradFunctionTraceHelper:
    @staticmethod
    def fwd_trace_helper(orig_fwd: Callable[_P, Any]) -> Callable[_P, Any]:
        ...
    


