"""
This type stub file was generated by pyright.
"""

import torch
import torch.fx as fx
import torch.nn as nn
from typing import Any, TYPE_CHECKING
from typing_extensions import ParamSpec, TypeVar
from .aot_autograd import make_boxed_compiler
from collections.abc import Callable, Sequence
from torch.fx.node import Node

if TYPE_CHECKING:
    ...
_P = ParamSpec("_P")
_R = TypeVar("_R")
log = ...
@make_boxed_compiler
def ts_compile(fx_g: fx.GraphModule, inps: Sequence[Any]) -> torch.jit.ScriptModule:
    """
    Compiles the :attr:`fx_g` with Torchscript compiler.

    .. warning::
        This API is experimental and likely to change.

    Args:
        fx_g(fx.GraphModule): The input Fx graph module to be compiled.

    Returns:
        Torch scripted model.
    """
    ...

def draw_graph_compile(name: str) -> Callable[[fx.GraphModule, list[Any]], fx.GraphModule]:
    ...

@make_boxed_compiler
def nop(fx_g: fx.GraphModule, _: Any) -> fx.GraphModule:
    """
    Returns the :attr:`fx_g` Fx graph module as it is. This is a no-op compiler
    and can be used to check accuracy.

    .. warning::
        This API is experimental and likely to change.

    """
    ...

class DebugInterpreter(fx.Interpreter):
    def run(self, *args: Any, initial_env: dict[Node, Any] | None = ..., enable_io_processing: bool = ...) -> Any:
        ...
    
    def run_node(self, n: Node) -> Any:
        ...
    


@make_boxed_compiler
def debug_nop(fx_g: fx.GraphModule, _: Any) -> Callable[[DebugInterpreter, Any, dict[Node, Any] | None, bool], Any]:
    """
    Returns a (slow) interpreter over the FX graph module that also checks
    various debugging properties (e.g., that tracing strides matched real
    strides.)
    """
    ...

@make_boxed_compiler
def simple_ts_compile(fx_g: fx.GraphModule, _: Any) -> torch.jit.ScriptModule:
    ...

def nnc_jit(f: Callable[..., Any]) -> Callable[..., Any]:
    ...

aten = ...
default_decompositions = ...
default_decompositions = ...
@make_boxed_compiler
def print_compile(fx_g: fx.GraphModule, _: Any) -> fx.GraphModule:
    ...

def memory_efficient_fusion(fn: Callable[_P, _R] | nn.Module, **kwargs: Any) -> Callable[_P, _R] | nn.Module:
    """
    Wrapper function over :func:`aot_function` and :func:`aot_module` to perform
    memory efficient fusion. It uses the
    :func:`min_cut_rematerialization_partition` partitioner to perform efficient
    recomputation. It uses NVFuser to compile the generated forward and backward
    graphs.

    .. warning::
        This API is experimental and likely to change.

    Args:
        fn (Union[Callable, nn.Module]): A Python function or a ``nn.Module``
            that takes one or more arguments. Must return one or more Tensors.
        **kwargs: Any other overrides you want to make to the settings

    Returns:
        Returns a ``Callable``  or ``nn.Module`` that retains the eager behavior
        of the original :attr:`fn`, but whose forward and backward graphs have
        gone through recomputation optimizations, and the graphs have been
        compiled with nvfuser.

    """
    ...

def debug_compile(fx_g: fx.GraphModule, inps: Sequence[torch.Tensor]) -> torch.jit.ScriptModule:
    ...

graph_index: int = ...
def get_inputs(input_data_path: str) -> list[torch.Tensor]:
    """
    Return a random input for the given inputs meta generated from _save_fx_default.
    """
    ...

def graph_dumper_aot(current_name: str, folder_name: str, dump_example_input: bool = ...) -> Callable[[bool, nn.Module], Any]:
    """
    Dump the forward, backward, and joint computation graph.
    Example Usage:
    save_fx_func = graph_dumper_aot(current_name, folder_name, dump_example_input = False)
    optimize_ctx = torchdynamo.optimize(
        save_fx_func
    )
    with torch.enable_grad():
        with optimize_ctx:
            result = forward_and_backward_pass(model, example_inputs)
    """
    ...

