"""
This type stub file was generated by pyright.
"""

import torch
import torch.fx as fx
from typing import Any, TYPE_CHECKING
from collections.abc import Callable
from torch._ops import OpOverloadPacket

if TYPE_CHECKING:
    ...
aten = ...
def get_aten_target(node: fx.Node) -> OpOverloadPacket | Callable[..., Any] | str:
    ...

rand_ops = ...
def fx_graph_cse(fx_g: torch.fx.graph.Graph) -> fx.Graph:
    ...

def raise_getitems(gm: fx.GraphModule) -> fx.GraphModule:
    ...

def strip_overloads(gm: fx.GraphModule) -> None:
    """
    Modifies the target of graph nodes in :attr:`gm` to strip overloads.

    Args:
        gm(fx.GraphModule): The input Fx graph module to be modified
    """
    ...

def get_placeholders(graph: fx.Graph) -> fx.graph._node_list:
    ...

def get_outputs(graph: fx.Graph) -> list[fx.Node]:
    ...

