"""
This type stub file was generated by pyright.
"""

import contextlib
from collections.abc import Callable, Generator
from typing import Any, TYPE_CHECKING
from typing_extensions import ParamSpec, TypeVar
from torch import Tensor

if TYPE_CHECKING:
    ...
_P = ParamSpec("_P")
_R = TypeVar("_R")
in_dims_t = int | tuple[Any, ...]
out_dims_t = int | tuple[int, ...] | None
def doesnt_support_saved_tensors_hooks(f: Callable[_P, _R]) -> Callable[_P, _R]:
    ...

def vmap_impl(func: Callable[_P, Tensor | tuple[Tensor, ...]], in_dims: in_dims_t, out_dims: out_dims_t, randomness: str, chunk_size: int | None, *args: _P.args, **kwargs: _P.kwargs) -> Any:
    ...

def get_chunk_sizes(total_elems: int, chunk_size: int) -> list[int]:
    ...

@contextlib.contextmanager
def vmap_increment_nesting(batch_size: int, randomness: str) -> Generator[int, None, None]:
    ...

def restore_vmap(func: Callable[..., _R], in_dims: in_dims_t, batch_size: int, randomness: str) -> Callable[..., tuple[Any, Any]]:
    ...

def wrap_batched(args: tuple[Any, ...], bdims: in_dims_t, level: int) -> tuple[Any, ...]:
    ...

def unwrap_batched(args: Any, level: int) -> tuple[Any, Any]:
    ...

