"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from torch.distributed.device_mesh import DeviceMesh
from torch.distributed.tensor._op_schema import OpStrategy

@dataclass
class EinsumDims:
    contracting_dims: list[str]
    batch_dims: list[str]
    lhs_out_only_dims: list[str]
    rhs_out_only_dims: list[str]
    @classmethod
    def parse_equation(cls, equation: str) -> tuple[list[str], str]:
        """
        Parse the einsum equation str to input dim chars and output dim char
        """
        ...
    
    @classmethod
    def parse_dims(cls, input_dims: list[str], output_dim: str) -> EinsumDims:
        """
        Parse the dims and extract the contracting, batch, and free dimensions
        for the left and right hand sides.
        """
        ...
    


def gen_einsum_strategies(equation: str, mesh: DeviceMesh, *, linearity: bool = ...) -> OpStrategy:
    """
    Generate a strategy list for the ops that follow einsum style notation.

    In principle, each mesh dim is independent of other device mesh dim when we
    generate strategies. So we generate strategy over each device mesh dim and
    do product combination on all mesh dims. We basically follow the below rule
    for each device mesh dim:

    1. Shard on contracting dim: When both inputs shard on contracting dim over
       the same device dim. The result will be Partial over that device dim.

    2. Shard on noncontracting dim:
        2.1: Shard on batch dim: output, both inputs all should shard on batch
        dim.
        2.2: Shard on lhs only dim or rhs only dim: both output and lhs or rhs
        input should shard on this free dim.

    3. Linearity (Partial): If enabled, set Partial on output and inputs over
       the same device mesh dim.
    """
    ...

