"""
This type stub file was generated by pyright.
"""

from torch.distributed.tensor._op_schema import OpSchema, RuntimeSchemaInfo, StrategyType
from torch.distributed.tensor._ops.utils import register_op_strategy

aten = ...
@register_op_strategy(aten.embedding.default)
def embedding_strategy(op_schema: OpSchema) -> StrategyType:
    """
    This strategy handles embedding op. We have two possible embedding shardings:
    rowwise and colwise
    """
    ...

@register_op_strategy(aten.embedding_dense_backward.default, schema_info=RuntimeSchemaInfo(static_argnum=2))
def embedding_dense_backward_strategy(op_schema: OpSchema) -> StrategyType:
    """
    This strategy handles embedding op. We have two possible embedding shardings:
    rowwise and colwise
    """
    ...

