"""
This type stub file was generated by pyright.
"""

import torch
from dataclasses import dataclass

@dataclass
class MaskBuffer:
    data: torch.Tensor | None = ...
    refcount: int = ...
    def materialize_mask(self, mask) -> None:
        ...
    
    def release_mask(self) -> None:
        ...
    
    def apply_mask(self, tensor) -> None:
        ...
    


