"""
This type stub file was generated by pyright.
"""

import torch
from collections.abc import Callable, Sequence
from typing import Optional
from torch._ops import OpOverload
from torch.distributed.tensor._op_schema import ArgsType, KwargsType, OpSchema, OpStrategy, StrategyType
from torch.distributed.tensor._ops.single_dim_strategy import _ShardingPlaceholder
from torch.distributed.tensor.placement_types import Placement

aten = ...
pointwise_ops = ...
linear_pointwise_ops = ...
partial_preserving_ops: dict[torch._ops.OpOverload, str] = ...
def pointwise_strategy(op_schema: OpSchema, linearity: int = ..., preserve_partial: str | None = ...) -> OpStrategy:
    ...

def linear_pointwise_strategy(op_schema: OpSchema) -> StrategyType:
    """
    Linear pointwise operators can propagate pending reductions.
    For example, c = add(a, b); if a is pending sum, then c will be
    pending sum as well without any communication overhead.

    Note that:
    1. Only unary and binary operations are supported, out variant
      ops are not supported.
    2. There're multiple types of linearity, refer to the doc of
      common_pointwise_strategy for more details.
    """
    ...

def partial_preserving_pointwise_strategy(op_schema: OpSchema) -> StrategyType:
    """
    Strategy for pointwise ops that preserve specific Partial types.

    For example, torch.maximum preserves Partial("max") placements because
    max(max(a), max(b)) == max(a, b). Similarly, torch.minimum preserves
    Partial("min") placements.
    """
    ...

def single_mesh_dim_pointwise_strategy(op: OpOverload, args_schema: ArgsType, kwargs_schema: KwargsType, linearity: int = ...) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

def single_mesh_dim_linear_pointwise_strategy(linearity: int = ...) -> Callable[[OpOverload, ArgsType, KwargsType], list[list[Placement | _ShardingPlaceholder]]]:
    ...

def single_mesh_dim_common_pointwise_strategy(args_schema: ArgsType, linearity: int = ..., scalar_tensor_idx: Optional[int] = ...) -> list[list[Placement | _ShardingPlaceholder]]:
    ...

def copy_strategy(op_schema: OpSchema) -> StrategyType:
    """
    Strategy for copy_ that preserves any Partial placement.

    copy_ simply copies data and should preserve whatever Partial placement
    the destination has, regardless of the reduce_op type (sum, avg, max, min, etc.).
    """
    ...

def common_pointwise_strategy(op, args_schema: Sequence[object], followed_strategy: OpStrategy, followed_strategy_index: int, linearity: int = ..., scalar_tensor_idx: int | None = ..., preserve_partial: str | None = ...) -> OpStrategy:
    """
    Common strategy for pointwise operations.

    Args:
        args_schema: Input arguments schema
        followed_strategy: Strategy to follow for output placement
        followed_strategy_index: Index of the strategy being followed
        linearity: depending on the operator, we support different types of linearity
            -1: the operation does not support linearity
            0: the unary operation that supports linearity, output propagates partial.
            1: the binary operation supports add linearity, where it requires every operand
                to be partial, output propagates partial.
            2: the binary operation supports multiplicative linearity, where it requires
                the primary operand to be partial, and the other operands to be replicate,
                output propagates partial.
        scalar_tensor_idx: Index of the Replicate scalar tensor for which we allow the mesh
            to be different from the mesh of followed_strategy
        preserve_partial: If set, Partial placements with this reduce_op will be preserved
            through the operation (e.g., "max" for torch.maximum, "min" for torch.minimum).
    """
    ...

p_sum_scalar_redistribute_ops = ...
norm_partial_avoidable_redistribute_ops = ...
for_each_ops = ...
for_each_linearity_ops = ...
def list_pointwise_strategy(op_schema: OpSchema, linearity: bool = ...) -> StrategyType:
    """
    Apply the pointwise strategy to the zipped arguments. For example, if we
    run a foreach add of two lists l1 and l2, then we apply the pointwise
    strategy on each pair (l1[i], l2[i]). If the first argument is a list but
    the second (or later) one is a tensor, then we broadcast the tensor by
    replicating it into a list with the length of the first argument.

    Args:
        mesh (DeviceMesh): device mesh for pointwise ops
        op_schema (OpSchema): schema of the operator to generate strategy for
        linearity (bool): specify whether op(a) + op(b) = op(a + b)

    Returns:
        OpStrategy: generated strategy
    """
    ...

def list_linear_pointwise_strategy(op_schema: OpSchema) -> StrategyType:
    """
    for each list op stratgy that supports linearity
    """
    ...

fused_ops = ...
_FUSED_OP_SCALAR_IDX = ...
