"""
This type stub file was generated by pyright.
"""

import torch
from collections.abc import Callable, Iterable, Sequence
from typing import TypeAlias, TypeVar
from torch._prims_common import DimsSequenceType, DimsType
from torch.distributed.tensor._dtensor_spec import DTensorSpec, TensorMeta
from torch.distributed.tensor._op_schema import OpSchema, OpStrategy, OutputSharding, PlacementList, RuntimeSchemaInfo, StrategyType
from torch.distributed.tensor.device_mesh import DeviceMesh
from torch.distributed.tensor.placement_types import Placement

def register_prop_rule(op: torch._ops.OpOverload | list[torch._ops.OpOverload], schema_info: RuntimeSchemaInfo | None = ...) -> Callable[[Callable[[OpSchema], OutputSharding]], Callable[[OpSchema], OutputSharding]]:
    ...

_OpSchemaT = TypeVar("_OpSchemaT", bound=OpSchema)
_StrategyTypeT = TypeVar("_StrategyTypeT", bound=StrategyType)
_ShardingStrategyFunc: TypeAlias = Callable[[_OpSchemaT], _StrategyTypeT]
def register_op_strategy(op: torch._ops.OpOverload | list[torch._ops.OpOverload], schema_info: RuntimeSchemaInfo | None = ...) -> Callable[[_ShardingStrategyFunc], _ShardingStrategyFunc]:
    ...

def replicate_op_strategy(op_schema: OpSchema) -> StrategyType:
    """
    Fallback strategy all use Replication()
    """
    ...

def as_list(x: list[object] | object) -> list[object] | torch.fx.immutable_collections.immutable_list:
    ...

def normalize_dim(dim: int, ndim: int) -> int:
    ...

def normalize_dims(dims: DimsType, ndim: int) -> DimsSequenceType:
    """Normalize a dim or a sequence of dims, so that they are all positive."""
    ...

def prod(xs: Iterable[int]) -> int:
    ...

def is_tensor_shardable(shape: Sequence[int], spec: DTensorSpec, allow_unbacked_sharding: bool | None = ...) -> bool:
    """
    Check if the shape is shardable according to the spec.

    This function handles both `Shard` and `_StridedShard` placements:
    - For `Shard`: checks if the tensor dimension size >= number of shards
    - For `_StridedShard`: additionally checks if the dimension is shardable after
      splitting with the placement's `split_factor`

    allow_unbacked_sharding: determines the fallback value if unbacked shapes are involved,
    and the queried shape properties are not statically known.

    e.g. when asking if u0 is shardable on num_shards, and u0 has generic bounds [0, inf],
    the behavior of allow_unbacked_sharding is:

        None: will data-dependent error
        True: assumes shardability; we return True, allowing zero-size shards at runtime when u0 < num_shards.
        False: returns False, and lower-bounding u0, e.g. torch._check(u0 >= num_shards), is needed to enable sharding.
    """
    ...

def is_tensor_evenly_shardable(shape: Sequence[int], spec: DTensorSpec) -> bool:
    """Check if the shape is evenly shardable according to the spec."""
    ...

def is_tensor_evenly_shardable_on_dim(shape: Sequence[int], spec: DTensorSpec, dim: int) -> bool:
    """Check if the shape is evenly shardable according to the spec on dim."""
    ...

def is_tensor_dim_sharded(spec: DTensorSpec, dim: int) -> bool:
    """Return True if tensor dim is sharded."""
    ...

def is_tensor_partial(spec: DTensorSpec) -> bool:
    """Return True if tensor is partial on the mesh."""
    ...

def infer_broadcast_dims_map(common_shape: torch.Size, input_shape: torch.Size) -> list[int]:
    ...

def map_placements_after_broadcast(placements: tuple[Placement, ...], shape: torch.Size, broadcast_dims_map: list[int], partial_to_replicate: bool = ...) -> tuple[Placement, ...]:
    """Map each placement based on the output shape after broadcast."""
    ...

def generate_redistribute_costs(src_strategy: OpStrategy, dst_spec: DTensorSpec) -> list[float]:
    """Generates one row in the 'redistribute_costs' matrix in an OpSpec
    The length of the returned list will match the number of strategies in 'src_strategy'.

    Each value in the row is the cost of redistributing from a particular src_strategy to dst_spec.
    """
    ...

def expand_to_full_mesh_op_strategy(mesh: DeviceMesh, op_schema: OpSchema, single_mesh_dim_strategies: list[PlacementList], *, output_tensor_meta: TensorMeta | Sequence[TensorMeta | None] | None = ..., input_index: int = ..., inplace_op: bool = ..., allow_unbacked_sharding: bool | None = ..., is_valid_strategy_cb: Callable[[list[DTensorSpec], DTensorSpec | tuple[DTensorSpec | None, ...]], bool] | None = ...) -> OpStrategy:
    """
    Convenience function to allow writing a sharding strategy considering only a single mesh dimension,
    and have it expanded combinatorially to all mesh dimensions.

    Args:
        mesh (DeviceMesh): the device mesh to expand the strategy to
        op_schema (OpSchema): the op schema
        single_mesh_dim_strategies (list[PlacementList]): the sharding strategies to expand. The outer list is over
            different strategies.  The inner PlacementList is over the outputs and inputs of the op. If input_index is 1,
            a PlacementList looks like [output_placement, input_placement1, input_placement2, ...].
        output_tensor_meta: tensor metadata for the output(s), used to populate DTensorSpec.tensor_meta field
        input_index: the number of outputs of the op, defaults to 1
        inplace_op: whether the op is inplace or not, defaults to False
        is_valid_strategy_cb: a callback function to filter out invalid sharding rules, defaults to None.

    Example: Let's say `my_op(tensor_x, tensor_y) - > output_tensor`  can support sharding or replicating tensor_x,
    but always requires tensor_y to be replicated.  We can specify these valid combinations ignoring mesh dims.
    Then, we can rely on `expand_to_full_mesh_op_strategy` to create every possible combination of these shardings
    over multiple mesh dimensions, filtering out any combinations that are invalid based on the actual mesh dim size.

        single_mesh_dim_strategies = [
            # first strategy: return output sharded on first dim, shard tensor_x on its first dim, replicate tensor_y
            [Shard(0), Shard(0), Replicate()]
            # second strategy: replicate output, and both inputs
            [Replicate(), Replicate(), Replicate()]
        ]
    """
    ...

def shift_shard_dims_after_insert(placements: Sequence[Placement], insert_dim: int = ...) -> Sequence[Placement]:
    ...

def shift_shard_dims_after_remove(placements: Sequence[Placement], remove_dim: int = ...) -> Sequence[Placement]:
    ...

