"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable, Sequence
from typing import Any, Literal, Optional, TYPE_CHECKING
from torch.utils._ordered_set import OrderedSet
from .base import VariableTracker
from .constant import ConstantVariable
from torch._dynamo.codegen import PyCodegen
from torch._dynamo.symbolic_convert import InstructionTranslator
from torch._dynamo.variables.builtin import BuiltinVariable
from .functions import UserFunctionVariable

"""
Dictionary-related variable tracking classes for PyTorch Dynamo.

This module implements variable tracking for different types of dictionary-like objects:
- Regular Python dictionaries (dict)
- Ordered dictionaries (collections.OrderedDict)
- Default dictionaries (collections.defaultdict)
- Dictionary views (keys and values)
- Sets and frozensets (implemented internally using dictionaries)

These classes are responsible for tracking dictionary operations during graph compilation,
maintaining proper guards for dictionary mutations and key existence checks. They handle
dictionary creation, modification, key/value access, and view operations while ensuring
correct behavior in the compiled code through appropriate guard installation.

The implementation uses a special _HashableTracker wrapper to handle dictionary keys
while preserving proper aliasing semantics. Sets are implemented as dictionaries with
None values for efficiency and code reuse.
"""
if TYPE_CHECKING:
    ...
def was_instancecheck_override(obj: Any) -> bool:
    ...

def raise_unhashable(arg: VariableTracker, tx: Optional[InstructionTranslator] = ...) -> None:
    ...

def is_hashable(x: VariableTracker) -> bool:
    ...

class ConstDictVariable(VariableTracker):
    CONTAINS_GUARD = ...
    _nonvar_fields = ...
    class _HashableTracker:
        """
        Auxiliary opaque internal class that wraps a VariableTracker and makes it hashable
        This should not be seen or touched by anything outside of ConstDictVariable and its children
        Note that it's also fine to put VTs into dictionaries and sets, but doing so does not take into account aliasing
        """
        def __init__(self, vt: VariableTracker) -> None:
            ...
        
        def __hash__(self) -> int:
            """
            Computes the hash value for the wrapped VariableTracker.

            For unrealized LazyVariableTrackers, uses the hash of the original value
            to avoid realizing the tracker and inserting unnecessary guards.
            For all other cases, delegates to the VariableTracker's get_python_hash method.

            Returns:
                The hash value of the underlying variable tracker
            """
            ...
        
        def __eq__(self, other: object) -> bool:
            """
            Checks equality between two _HashableTracker instances.

            Delegates to the VariableTracker's is_python_equal method to compare
            the underlying variable trackers for Python-level equality.

            Args:
                other: Another _HashableTracker instance to compare with

            Returns:
                True if the underlying variable trackers are Python-equal, False otherwise
            """
            ...
        
    
    
    def __init__(self, items: dict[VariableTracker, VariableTracker], user_cls: type = ..., **kwargs: Any) -> None:
        ...
    
    def as_proxy(self) -> dict[Any, Any]:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    def as_python_constant(self) -> dict[Any, Any]:
        ...
    
    def keys_as_python_constant(self) -> dict[Any, VariableTracker]:
        ...
    
    def python_type(self) -> type:
        ...
    
    def __contains__(self, vt: VariableTracker) -> bool:
        ...
    
    def call_tree_map_branch(self, tx: InstructionTranslator, tree_map_fn: UserFunctionVariable, map_fn: VariableTracker, rest: Sequence[VariableTracker], tree_map_kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def len(self) -> int:
        ...
    
    def has_new_items(self) -> bool:
        ...
    
    def is_new_item(self, value: Optional[VariableTracker], other: VariableTracker) -> bool:
        ...
    
    def reconstruct_kvs_into_new_dict(self, codegen: PyCodegen) -> None:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def getitem_const_raise_exception_if_absent(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker:
        ...
    
    def getitem_const(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker:
        ...
    
    def maybe_getitem_const(self, arg: VariableTracker) -> Optional[VariableTracker]:
        ...
    
    def realize_key_vt(self, arg: VariableTracker) -> None:
        ...
    
    def install_dict_keys_match_guard(self) -> None:
        ...
    
    def install_dict_contains_guard(self, tx: InstructionTranslator, args: list[VariableTracker]) -> None:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def clone(self, **kwargs: Any) -> VariableTracker:
        ...
    
    def is_python_hashable(self) -> bool:
        """
        Dictionaries are mutable and therefore not hashable in Python.
        """
        ...
    


class MappingProxyVariable(VariableTracker):
    def __init__(self, dv_dict: ConstDictVariable, **kwargs: Any) -> None:
        ...
    
    def python_type(self) -> type:
        ...
    
    def unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    


class NNModuleHooksDictVariable(ConstDictVariable):
    def install_dict_keys_match_guard(self) -> None:
        ...
    
    def install_dict_contains_guard(self, tx: InstructionTranslator, args: list[VariableTracker]) -> None:
        ...
    


class DefaultDictVariable(ConstDictVariable):
    def __init__(self, items: dict[VariableTracker, VariableTracker], user_cls: type, default_factory: Optional[VariableTracker] = ..., **kwargs: Any) -> None:
        ...
    
    def is_python_constant(self) -> bool:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    @staticmethod
    def is_supported_arg(arg: VariableTracker) -> bool:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


class SetVariable(ConstDictVariable):
    """We model a sets as dictionary with None values"""
    CONTAINS_GUARD = ...
    def __init__(self, items: Iterable[VariableTracker], **kwargs: Any) -> None:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    @property
    def set_items(self) -> set[ConstDictVariable._HashableTracker]:
        ...
    
    def as_proxy(self) -> Any:
        ...
    
    def python_type(self) -> type:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def python_type_var(self) -> BuiltinVariable:
        ...
    
    def getitem_const(self, tx: InstructionTranslator, arg: VariableTracker) -> VariableTracker:
        ...
    
    def install_dict_keys_match_guard(self) -> None:
        ...
    


class OrderedSetClassVariable(VariableTracker):
    def __init__(self, **kwargs: Any) -> None:
        ...
    
    def as_python_constant(self) -> type[OrderedSet[Any]]:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> OrderedSetVariable:
        ...
    


class OrderedSetVariable(SetVariable):
    def debug_repr(self) -> str:
        ...
    
    def as_python_constant(self) -> OrderedSet[Any]:
        ...
    
    def python_type(self) -> type[OrderedSet[Any]]:
        ...
    
    def python_type_var(self) -> OrderedSetClassVariable:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


class FrozensetVariable(SetVariable):
    def debug_repr(self) -> str:
        ...
    
    @property
    def set_items(self) -> set[ConstDictVariable._HashableTracker]:
        ...
    
    def python_type(self) -> type:
        ...
    
    def python_type_var(self) -> BuiltinVariable:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def is_python_hashable(self) -> Literal[True]:
        """
        Frozensets are immutable and hashable in Python.
        """
        ...
    
    def get_python_hash(self) -> int:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    


class DictKeySetVariable(SetVariable):
    def debug_repr(self) -> str:
        ...
    
    def install_dict_keys_match_guard(self) -> None:
        ...
    
    def install_dict_contains_guard(self, tx: InstructionTranslator, args: list[VariableTracker]) -> None:
        ...
    
    @property
    def set_items(self) -> Any:
        ...
    
    def python_type(self) -> type:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class DictViewVariable(VariableTracker):
    """
    Models _PyDictViewObject

    This is an "abstract" class. Subclasses will override kv and the items method
    """
    kv: Optional[str] = ...
    def __init__(self, dv_dict: ConstDictVariable, **kwargs: Any) -> None:
        ...
    
    @property
    def view_items(self) -> Any:
        ...
    
    @property
    def view_items_vt(self) -> list[VariableTracker]:
        ...
    
    def unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class DictKeysVariable(DictViewVariable):
    kv = ...
    @property
    def set_items(self) -> set[VariableTracker]:
        ...
    
    @property
    def view_items_vt(self) -> list[VariableTracker]:
        ...
    
    def python_type(self) -> type:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class DictValuesVariable(DictViewVariable):
    kv = ...
    @property
    def view_items_vt(self) -> list[VariableTracker]:
        ...
    
    def python_type(self) -> type:
        ...
    
    def debug_repr(self) -> str:
        ...
    


class DictItemsVariable(DictViewVariable):
    kv = ...
    @property
    def view_items_vt(self) -> list[VariableTracker]:
        ...
    
    def python_type(self) -> type:
        ...
    
    def debug_repr(self) -> str:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def is_python_hashable(self) -> Literal[False]:
        """
        Dictionary item views are not hashable in Python.
        """
        ...
    


