"""
This type stub file was generated by pyright.
"""

import functools
import types
import torch
from collections.abc import Callable, Sequence
from types import FunctionType
from typing import Any, Literal, Optional, TYPE_CHECKING, TypeVar
from typing_extensions import Never
from weakref import WeakKeyDictionary
from torch._guards import Source
from .. import variables
from ..source import AttrSource
from .base import VariableTracker
from .constant import ConstantVariable
from torch._dynamo.codegen import PyCodegen
from torch._dynamo.symbolic_convert import InliningGeneratorInstructionTranslator, InstructionTranslator, InstructionTranslatorBase
from torch._dynamo.variables.ctx_manager import ContextWrappingVariable
from torch._higher_order_ops.triton_kernel_wrap import TritonGridType, TritonHOPifier, TritonKernelType
from .lists import BaseListVariable, ListVariable
from .tensor import TensorVariable

"""
Function-related variable tracking classes for Dynamo's symbolic execution.

This module contains classes that track different types of functions during graph
compilation, including:
- User-defined functions and methods
- Built-in functions and methods
- Wrapped functions (e.g. from decorators)
- Special function types (e.g. functools.partial)
- Triton kernels and related function types

These classes are responsible for:
- Tracking function calls and their arguments
- Managing function closures and cell variables
- Handling function attributes and special methods
- Maintaining guards for function identity and closure contents
- Supporting function inlining and specialization
- Enabling proper symbolic execution of different function types

The variable trackers here work together with the rest of Dynamo to enable
accurate graph capture while handling Python's various function-related behaviors.
"""
if TYPE_CHECKING:
    ...
_F = TypeVar("_F", bound=Callable[..., Any])
CO_VARARGS = ...
CO_VARKEYWORDS = ...
_SUPPORTED_TREE_MAP_KWARGS = ...
_TREE_MAP_ONLY_SUPPORTED_KWARGS = ...
PT2_ISSUE_TRACKER_URL = ...
_spec_cache: WeakKeyDictionary[Any, Any] = ...
class ClosureConversionError(NotImplementedError):
    ...


@functools.lru_cache
def get_pytree_SUPPORTED_NODES_source() -> AttrSource:
    ...

class FunctionSpec:
    def __init__(self, func: FunctionType) -> None:
        ...
    
    def update_defaults(self, func: FunctionType) -> None:
        ...
    


def bind_args_cached(func: FunctionType, tx: InstructionTranslator, fn_source: Source | None, args: Sequence[Any], kwargs: dict[str, Any]) -> dict[str, VariableTracker]:
    ...

def wrap_bound_arg(tx: InstructionTranslator, val: Any, source: Source | None = ...) -> VariableTracker:
    ...

def wrap_args_kwargs(tx: InstructionTranslator, result: dict[str, Any]) -> None:
    ...

def init_cellvars(parent: InstructionTranslator, result: dict[str, VariableTracker], code: types.CodeType) -> None:
    """
    Update `result` to add mapping from local name to new cells created
    directly by `code`, or update SideEffects in `parent` if the a local cell is
    already in `result` (cell argument).
    """
    ...

fn_known_dunder_attrs = ...
def fn_var_getattr(tx: InstructionTranslator, fn: object, source: Source | None, name: str) -> VariableTracker:
    ...

class BaseUserFunctionVariable(VariableTracker):
    def get_filename(self) -> str:
        ...
    
    def get_name(self) -> str:
        ...
    
    def get_globals(self) -> dict[str, Any]:
        ...
    
    def get_code(self) -> types.CodeType:
        ...
    
    def has_self(self) -> bool:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def closure_vars(self, tx: InstructionTranslator) -> dict[str, VariableTracker]:
        ...
    
    def should_allow_nested_graph_breaks(self) -> bool:
        ...
    


class UserFunctionVariable(BaseUserFunctionVariable):
    """Some unsupported user-defined global function"""
    _nonvar_fields = ...
    _TREE_MAP_MODULES = ...
    @classmethod
    def create_with_source(cls, value: Any, source: Any) -> UserFunctionVariable:
        ...
    
    def __init__(self, fn: types.FunctionType | torch.jit.ScriptFunction, is_constant: bool = ..., **kwargs: Any) -> None:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def self_args(self) -> list[VariableTracker]:
        ...
    
    def get_function(self) -> types.FunctionType:
        ...
    
    def get_code(self) -> types.CodeType:
        ...
    
    def python_type(self) -> type:
        ...
    
    def has_self(self) -> bool:
        ...
    
    def get_globals(self) -> dict[str, Any]:
        ...
    
    def get_source(self) -> Source:
        ...
    
    def bind_args(self, parent: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> dict[str, VariableTracker]:
        """
        Assume `args` and `kwargs` are VariableTracker arguments for a call to
        this function, create new bindings for initial locals.
        """
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def is_python_hashable(self) -> Literal[True]:
        ...
    
    def get_python_hash(self) -> int:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    


class InspectSignatureVariable(UserFunctionVariable):
    """
    Variable tracker for inspect.signature with caching support.

    inspect.Signature is expensive to trace. When inspect.signature is called
    repeatedly on the same function during tracing, we cache the result to avoid
    retracing the signature construction each time. Although this is different
    from CPython behavior, it is safe to do so because inspect.signature does
    not change across different calls to the same function.
    """
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class TreeMapOnlyFunctionVariable(BaseUserFunctionVariable):
    _nonvar_fields = ...
    def __init__(self, allowed_types: tuple[type, ...], map_fn: VariableTracker, **kwargs: Any) -> None:
        ...
    
    def python_type(self) -> type:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class BuiltinMethodVariable(BaseUserFunctionVariable):
    def __init__(self, fn: types.BuiltinMethodType, is_constant: bool = ..., **kwargs: Any) -> None:
        ...
    
    @staticmethod
    def is_supported_builtin_method(obj: Any) -> bool:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class LocalGeneratorObjectVariable(VariableTracker):
    def __init__(self, code: types.CodeType, f_globals: dict[str, Any], inline_tracer: InliningGeneratorInstructionTranslator, **kwargs: Any) -> None:
        ...
    
    def get_code(self) -> types.CodeType:
        ...
    
    def get_filename(self) -> str:
        ...
    
    def get_name(self) -> str:
        ...
    
    def get_function(self) -> Never:
        ...
    
    def has_self(self) -> bool:
        ...
    
    def __name__(self) -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    __repr__ = ...
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def get_globals(self) -> dict[str, Any]:
        ...
    
    def python_type(self) -> type:
        ...
    
    def next_variable(self, tx: InstructionTranslatorBase) -> VariableTracker:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def has_unpack_var_sequence(self, tx: InstructionTranslator) -> bool:
        ...
    
    def has_force_unpack_var_sequence(self, tx: InstructionTranslator) -> bool:
        ...
    
    def force_unpack_var_sequence(self, tx: InstructionTranslatorBase) -> list[VariableTracker]:
        ...
    
    def force_apply_to_var_sequence(self, tx: InstructionTranslatorBase, fn: Callable[[VariableTracker], Any]) -> None:
        ...
    
    def should_allow_nested_graph_breaks(self) -> Literal[False]:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class ContextlibContextManagerLocalGeneratorObjectVariable(LocalGeneratorObjectVariable):
    """
    .. note::

        This is only used when the function is annotated with @contextlib.contextmanager

        It is a special case of a generator function as we do not allow return a context manager
        from a torch.compile function.
    """
    ...


class LocalGeneratorFunctionVariable(BaseUserFunctionVariable):
    """functions that behaves like iterators

    .. note::

        This is a wrapper around (Nested)UserFunctionVariable
    """
    def __init__(self, vt: BaseUserFunctionVariable, *, generator_cls: type = ..., **kwargs: Any) -> None:
        ...
    
    def __getattr__(self, name: str) -> Any:
        ...
    
    def get_code(self) -> types.CodeType:
        ...
    
    def get_globals(self) -> dict[str, Any]:
        ...
    
    def has_self(self) -> bool:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class FunctionDecoratedByContextlibContextManagerVariable(LocalGeneratorFunctionVariable):
    """
    .. note::

        This is only used when the function is annotated with @contextlib.contextmanager
    """
    def __init__(self, vt: BaseUserFunctionVariable, **kwargs: Any) -> None:
        ...
    


class UserMethodVariable(UserFunctionVariable):
    """Some unsupported user-defined method"""
    def __init__(self, fn: Callable[..., Any], obj: VariableTracker, source_fn: Source | None = ..., **kwargs: Any) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def self_args(self) -> list[VariableTracker]:
        ...
    
    def python_type(self) -> type[types.MethodType]:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    


class WrappedUserMethodVariable(UserMethodVariable):
    def __init__(self, wrapped: UserMethodVariable, context: ContextWrappingVariable, **kwargs: Any) -> None:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


class WrappedUserFunctionVariable(UserFunctionVariable):
    def __init__(self, wrapped: UserFunctionVariable, context: ContextWrappingVariable, **kwargs: Any) -> None:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


def invoke_and_store_as_constant(tx: InstructionTranslator, fn: Callable[..., Any], name: str, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
    ...

class NestedUserFunctionVariable(BaseUserFunctionVariable):
    _nonvar_fields = ...
    def __init__(self, fn_name: VariableTracker, code: VariableTracker, f_globals: dict[str, Any], defaults: VariableTracker | None, kwdefaults: VariableTracker | None, annotations: VariableTracker | None, closure: VariableTracker | None, wrapped_fn: VariableTracker | None = ..., **kwargs: Any) -> None:
        ...
    
    def self_args(self) -> list[VariableTracker]:
        ...
    
    def as_python_constant(self) -> types.FunctionType:
        ...
    
    def get_code(self) -> types.CodeType:
        ...
    
    def python_type(self) -> type[types.FunctionType]:
        ...
    
    def get_function(self, _converting: set[int] | None = ...) -> types.FunctionType:
        ...
    
    def is_python_constant(self) -> bool:
        ...
    
    def call_setattr(self, tx: InstructionTranslator, name_var: VariableTracker, val: VariableTracker) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def has_closure(self) -> bool:
        ...
    
    def const_getattr(self, tx: InstructionTranslator, name: str) -> Any:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def has_self(self) -> bool:
        ...
    
    def get_globals(self) -> dict[str, Any]:
        ...
    
    def bind_args(self, parent: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> dict[str, VariableTracker]:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


class WrappedNestedUserFunctionVariable(NestedUserFunctionVariable):
    def __init__(self, wrapped: NestedUserFunctionVariable, context: ContextWrappingVariable, **kwargs: Any) -> None:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


class SkipFunctionVariable(VariableTracker):
    _nonvar_fields = ...
    def __init__(self, value: Any, reason: str | None = ..., **kwargs: Any) -> None:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    @classmethod
    def create_with_source(cls, value: Any, source: Source) -> SkipFunctionVariable:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def is_python_hashable(self) -> bool:
        ...
    
    def get_python_hash(self) -> int:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    


class WrappedSkipFunctionVariable(SkipFunctionVariable):
    def __init__(self, wrapped: SkipFunctionVariable, context: ContextWrappingVariable, **kwargs: Any) -> None:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


class WrapperUserFunctionVariable(VariableTracker):
    """
    Used to represent a wrapper object that contains the actual callable as an
    attribute. For example, torch.jit.script/trace have the original function at
    their _torchdynamo_inline attribute. Similarly, functions with
    __script_if_tracing_wrapper have the original attr at "__original_fn".
    """
    def __init__(self, wrapper_obj: Any, attr_to_trace: str, **kwargs: Any) -> None:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def self_args(self) -> list[VariableTracker]:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class WrapperUserMethodVariable(WrapperUserFunctionVariable):
    """
    Similar to WrapperUserFunctionVariable, but for methods. The only delta is
    saving the vt for `self` object of the method which is then used by
    WrapperUserFunctionVariable in `call_function` method.
    """
    def __init__(self, wrapper_obj: Any, attr_to_trace: str, self_obj: VariableTracker, **kwargs: Any) -> None:
        ...
    
    def self_args(self) -> list[VariableTracker]:
        ...
    


class CollectiveFunctionRewriteVariable(UserFunctionVariable):
    """
    Some of the torch.distributed.* collective APIs are possible to rewrite to 'traceable' collectives.

    This class provides both a way to check if a function is remappable, and perform the remapping.

    In the case that a function is 'remappable' but only for some combinations of call-time arguments,
    we check the args at `call_function` time and fall back to graph-breaking if needed.  This is no worse
    than status-quo as we currently graph-break on all distributed.* collectives.
    """
    def __init__(self, fn: Callable[..., Any], *, replacement_var: UserFunctionVariable, **kwargs: Any) -> None:
        ...
    
    @staticmethod
    def create(tx: InstructionTranslator, old_fn: Callable[..., Any], source: Source, **options: Any) -> CollectiveFunctionRewriteVariable:
        ...
    
    @staticmethod
    def can_rewrite(variable: Any) -> bool:
        ...
    
    @staticmethod
    def rewrite(tx: InstructionTranslator, fn: Callable[..., Any]) -> tuple[Any, AttrSource]:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class FunctoolsWrapsVariable(UserFunctionVariable):
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class CollectionsNamedTupleFunction(UserFunctionVariable):
    def as_python_constant(self) -> Any:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class FunctoolsPartialVariable(VariableTracker):
    _nonvar_fields = ...
    def __init__(self, func: VariableTracker, args: Sequence[VariableTracker], keywords: dict[str, VariableTracker], original_cache_hash: Any = ..., **kwargs: Any) -> None:
        ...
    
    def python_type(self) -> type:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def get_function(self) -> Any:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def guard_as_python_constant(self) -> Any:
        """Similar to as_python_constant(), but add ID_MATCH guards to try to force things to become constants"""
        ...
    
    def is_python_hashable(self) -> bool:
        ...
    
    def get_python_hash(self) -> int:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    


class PolyfilledFunctionVariable(VariableTracker):
    _nonvar_fields = ...
    @classmethod
    def create_with_source(cls, value: Any, source: Source) -> PolyfilledFunctionVariable:
        ...
    
    def __init__(self, fn: _F, **kwargs: Any) -> None:
        ...
    
    @property
    def polyfill_fn(self) -> Callable[..., Any]:
        ...
    
    def can_constant_fold_through(self) -> bool:
        ...
    
    def get_function(self) -> Any:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    


class SysFunctionVariable(VariableTracker):
    def __init__(self, value: Any, **kwargs: Any) -> None:
        ...
    
    def exc_info(self, tx: InstructionTranslator) -> variables.TupleVariable:
        ...
    
    def exception(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class DynamoTritonHOPifier(TritonHOPifier):
    def raise_unsupported(self, msg: str) -> Never:
        ...
    
    def is_callable(self, maybe_callable: VariableTracker) -> bool:
        ...
    
    def get_value(self, val: VariableTracker) -> Any:
        ...
    
    def check_grid(self, grid: BaseListVariable) -> tuple[torch.fx.proxy.Proxy, ...]:
        ...
    
    def call_grid(self, grid: Any, meta: dict[str, Any], tx: InstructionTranslator) -> Any:
        ...
    
    def call_user_defined_fn(self, user_fn: Callable[..., Any], args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker], tx: Optional[InstructionTranslator], variable: Any) -> VariableTracker:
        ...
    
    def wrap_user_defined_obj(self, user_obj: Any, tx: Optional[InstructionTranslator], variable: Any, name: str) -> VariableTracker:
        ...
    
    def maybe_unpack_configs(self, configs: Any, tx: Optional[InstructionTranslator]) -> list[Any]:
        ...
    
    def maybe_unpack_heuristic_result(self, result: VariableTracker) -> Any:
        ...
    
    def call_getitem(self, variable: TritonKernelVariable, args: Sequence[Any]) -> TritonKernelVariable:
        ...
    
    def call_HOP(self, variable: TritonKernelVariable, grids: Any, combined_args: dict[str, Any], tx: InstructionTranslator) -> variables.ConstantVariable:
        ...
    


dynamo_triton_hopifier_singleton = ...
class TritonKernelVariable(VariableTracker):
    grid: TritonGridType
    kernel: TritonKernelType
    kernel_idx: int | None
    kernel_source: AttrSource
    def __init__(self, kernel: Any, kernel_idx: int | None, grid: Any, **kwargs: Any) -> None:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def specialize_symbolic(self, arg: Any) -> Any:
        ...
    


class TMADescriptorExperimentalVariable(VariableTracker):
    def __init__(self, data_ptr: variables.DataPtrVariable, dims: list[VariableTracker], block_dims: list[VariableTracker], element_size: VariableTracker, **kwargs: Any) -> None:
        ...
    
    def to_metadata(self) -> Any:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def get_tensor(self) -> VariableTracker:
        ...
    


class TMADescriptorStableVariable(VariableTracker):
    def __init__(self, tensor: TensorVariable, block_shape: ListVariable, **kwargs: Any) -> None:
        ...
    
    def to_metadata(self) -> Any:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def get_tensor(self) -> Any:
        ...
    


class CreateTMADescriptorExperimentalVariable(VariableTracker):
    def __init__(self, rank: int, **kwargs: Any) -> None:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class CreateTMADescriptorStableVariable(VariableTracker):
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class PyTreeGetNodeTypeFunctionVariable(UserFunctionVariable):
    """
    `torch.utils._pytree._get_node_type` function is very hot function. We want to special case it to reduce Dynamo tracing time.

    def _get_node_type(tree: Any) -> Any:
        node_type = type(tree)
        # All namedtuple types are implicitly registered as pytree nodes.
        # XXX: Other parts of the codebase expect namedtuple types always return
        #      `namedtuple` instead of the actual namedtuple type. Even if the type
        #      is explicitly registered.
        if is_namedtuple_class(node_type):
            return namedtuple
        return node_type
    """
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class PyTreeTreeIsLeafFunctionVariable(UserFunctionVariable):
    """
    `torch.utils._pytree.tree_is_leaf` function is a hot function. We want to special case it to reduce Dynamo tracing time.

    def tree_is_leaf(
        tree: PyTree,
        is_leaf: Callable[[PyTree], bool] | None = None,
    ) -> bool:
        if is_leaf is not None and is_leaf(tree):
            return True
        return _get_node_type(tree) not in SUPPORTED_NODES

    When is_leaf is None (the common case), we can optimize by not tracing into the function.
    When is_leaf is not None, we fall back to regular tracing since it requires executing user code.
    """
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class SparseTensorCreationSkipVariable(SkipFunctionVariable):
    """
    Skip variable for sparse tensor factory functions with clear messaging regarding lack of support.
    """
    def __init__(self, value: Any, **kwargs: Any) -> None:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class TritonSetAllocatorSkipVariable(SkipFunctionVariable):
    """
    Skip variable for triton.set_allocator with a clear message to move it outside the compiled region.
    """
    def __init__(self, value: Any, **kwargs: Any) -> None:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


