"""
This type stub file was generated by pyright.
"""

import contextlib
import torch.fx
from collections.abc import Generator, Iterable, Sequence
from dataclasses import dataclass
from typing import Any, Literal, Optional, ParamSpec, TYPE_CHECKING, TypeVar
from torch._dynamo.variables.functions import UserFunctionVariable
from torch._dynamo.variables.nn_module import UnspecializedNNModuleVariable
from torch._guards import Source
from torch._higher_order_ops.invoke_subgraph import NestedCompileRegionOptions
from torch._ops import HigherOrderOperator
from torch.fx.graph_module import GraphModule
from torch.fx.proxy import Proxy
from torch.multiprocessing.reductions import StorageWeakRef
from torch.utils import _pytree as pytree
from .base import VariableTracker
from torch._dynamo.output_graph import SubgraphTracer
from torch._dynamo.symbolic_convert import InstructionTranslator
from torch._subclasses.fake_tensor import FakeTensorMode
from . import AutogradFunctionContextVariable

"""
This module contains classes and utilities for handling higher-order operators in Dynamo.
It provides functionality for tracing and transforming control flow constructs like
conditions (torch.cond), loops (torch.while_loop), maps (torch.ops.higher_order.map),
and other higher-order operations.

The module includes specialized VariableTracker classes for different types of
higher-order operations, along with utilities for:
- Speculating and capturing subgraphs
- Managing control flow
- Handling autograd function applications
- Supporting function transformations
- Processing activation checkpoints

These classes work together to enable Dynamo to correctly trace and compile code
containing complex control flow patterns and higher-order functions while preserving
their semantic behavior.
"""
if TYPE_CHECKING:
    ...
P = ParamSpec("P")
R = TypeVar("R")
HOP_VT_Alias = TypeVar("HOP_VT_Alias", bound="TorchHigherOrderOperatorVariable")
log = ...
hc_log = ...
@dataclass
class OutputSpec:
    """
    Contains the treespec of the output of the speculated subgraph, and the
    information to mask out the constant values from the output during
    flattening and inserting them back during unflattening. Cleaning up
    constants from the graph makes the graph simpler for AOTDispatcher and
    Inductor.
    """
    treespec: pytree.TreeSpec
    masks_to_filter_const_values: list[bool] | None = ...
    const_values: list[Any] | None = ...
    num_intermediate_nodes_as_outputs: int = ...
    def __post_init__(self) -> None:
        ...
    


@contextlib.contextmanager
def discard_graph_changes(tx: InstructionTranslator) -> Generator[None, None, None]:
    ...

def check_meta_consistency_vt(vars1: list[VariableTracker], vars2: list[VariableTracker], lhs_name: str, rhs_name: str, include_contiguity: bool = ...) -> None:
    ...

@contextlib.contextmanager
def dynamo_enable_grad(tx: InstructionTranslator, enable: bool = ...) -> Generator[None, None, None]:
    ...

@contextlib.contextmanager
def dynamo_allow_side_effects_in_hop(tx: InstructionTranslator) -> Generator[None, None, None]:
    ...

def find_mismatched_vars(var: Any, types: type | tuple[type, ...], allow_none: bool = ...) -> set[VariableTracker]:
    """
    Recursively finds variables whose type is not an instance of the specified types.
    Args:
        var: The variable to check.
        types: A tuple of allowed types.
        allow_none (bool): Whether to allow None values. Defaults to False.
    Returns:
        A set of variables whose type is not an instance of the specified types.
    """
    ...

def only_consist_of(var: Any, types: tuple[type, ...], allow_none: bool = ...) -> bool:
    ...

def add_call_function(tx: InstructionTranslator, fn: Any, args: tuple[Any, ...], kwargs: dict[str, Any], flat_example_value: Any, config: Optional[NestedCompileRegionOptions] = ...) -> VariableTracker:
    ...

def overwrite_tensor_vt_requires_grad(graph_output_vts: Iterable[VariableTracker], flat_variable: VariableTracker) -> None:
    ...

def overwrite_tensor_vt_proxy(graph_output_vts: Iterable[VariableTracker], flat_variable: VariableTracker) -> None:
    ...

def get_tensor_storages(tensor: torch.Tensor) -> set[StorageWeakRef]:
    """
    Get storage references from a tensor.

    Handles regular tensors. Raises NotImplementedError for sparse tensors
    and traceable wrapper subclasses.

    Args:
        tensor: The tensor to extract storages from

    Returns:
        Set of StorageWeakRef objects for the tensor's storage(s)
    """
    ...

class StorageAliasingTracker:
    """
    Tracks storage references to detect aliasing between tensors.

    This class encapsulates the logic for collecting storages from tensors
    and checking for aliasing conflicts. Used to filter intermediate outputs
    that would create input-output or output-output aliasing.
    """
    def __init__(self) -> None:
        ...
    
    def collect_from_inputs(self, tx: InstructionTranslator) -> None:
        """Collect storages from graph input placeholders."""
        ...
    
    def collect_from_outputs(self, graph_output_vts: Sequence[VariableTracker]) -> None:
        """Collect storages from existing graph outputs."""
        ...
    
    def check_and_track(self, proxy_node: Proxy) -> bool:
        """
        Check if a tensor can be added as a subgraph output without causing aliasing issues.

        Given a proxy node, extracts its example tensor value and checks if its storage
        aliases with any previously tracked storages (from inputs or other outputs).
        If there's no aliasing conflict, the tensor's storage is added to the tracked set.

        Args:
            proxy_node: An FX proxy node whose example_value is the tensor to check.

        Returns:
            True if the tensor doesn't alias with tracked storages (safe to add as output),
            False if it aliases (should be filtered out).
        """
        ...
    


def collect_intermediate_outputs(tx: InstructionTranslator, subtracer: SubgraphTracer, graph_output_vts: Sequence[VariableTracker], filter_aliased_intermediates: bool = ...) -> list[VariableTracker]:
    ...

def are_same_graph_modules(fn_name: str, a_mod: GraphModule, b_mod: GraphModule, fake_mode: FakeTensorMode) -> bool:
    ...

def validate_args_and_maybe_create_graph_inputs(sub_args: list[VariableTracker], tracer: SubgraphTracer, tx: InstructionTranslator, set_subgraph_inputs: str, description: str, sub_args_names: Sequence[str] | None = ...) -> list[Any]:
    ...

def move_lifted_freevars_phs_to_end(graph: torch.fx.Graph, lifted_freevars: dict[Proxy, Proxy]) -> None:
    ...

def check_aliasing_and_input_mutation(subtracer: SubgraphTracer, graph: torch.fx.Graph, supports_input_mutation: bool, supports_aliasing: bool, source_target: Optional[HigherOrderOperator]) -> None:
    ...

def trace_hop_function(f: VariableTracker, tx: InstructionTranslator, subtracer: SubgraphTracer, enable_grad: bool | None, restore_side_effects: bool, args: Sequence[VariableTracker], sub_kwargs: dict[str, VariableTracker]) -> VariableTracker:
    ...

def trace_hop_function_with_auto_output_flattening(f: VariableTracker, tx: InstructionTranslator, subtracer: SubgraphTracer, enable_grad: bool | None, allow_side_effects: bool, args: Sequence[VariableTracker], sub_kwargs: dict[str, VariableTracker]) -> VariableTracker:
    ...

def get_hop_args(tx: InstructionTranslator, f: VariableTracker, subtracer: SubgraphTracer, sub_args: list[VariableTracker], sub_kwargs: dict[str, VariableTracker], set_subgraph_inputs: str, description: str) -> list[VariableTracker]:
    ...

def speculate_subgraph_with_auto_output_flattening(tx: InstructionTranslator, f: VariableTracker, sub_args: Sequence[VariableTracker], sub_kwargs: dict[str, VariableTracker] | None, description: str, *, source_target: Optional[HigherOrderOperator] = ..., enable_grad: Optional[bool] = ..., set_subgraph_inputs: Literal["automatic", "automatic_with_forced_inputs", "flatten_manual", "manual"] = ..., allow_side_effects: bool = ..., filter_aliased_intermediates: bool = ..., supports_input_mutation: bool = ..., supports_aliasing: bool = ..., tracer: Optional[SubgraphTracer] = ...) -> tuple[VariableTracker, torch.fx.Graph, dict[torch.fx.Proxy, torch.fx.Proxy], VariableTracker | tuple[VariableTracker, ...],]:
    """
    Speculate subgraph for Higher-Order Operators (HOPs) with automatic output flattening.

    ## Automatic output flattening

    For many HOPs, the representation exists only as a container for the
    subgraph. In later compiler stages or at runtime, the HOP is desugared and
    simply executes the subgraph directly, as if it were inlined. For such hops,
    we follow automatic output flattening.
    For example:
    - invoke_subgraph
    - activation checkpointing (torch.utils.checkpoint.checkpoint)
    - autograd.Function
    - nested_compile_region

    This is in contrast to control flow HOPs which do not follow this desugaring:
    - torch.cond (conditional execution based on predicate)
    - torch.while_loop (iterative execution)
    - torch.map (parallel execution over batch dimension)

    For control flow HOPs, the HOP behavior is fundamentally different from just
    running the body function once.

    ## Key Advantage: Disentangling VTs from Graph Outputs

    Desugaring simplify HOP processing by allowing us to disentangle the output
    variable trackers (VTs) from the HOP subgraph outputs. This mirrors typical
    Dynamo processing where:
    - VTs "run ahead" representing the program state for continued tracing
    - The graph is a side data structure tracking computation seen so far

    This separation is crucial for HOPs with non-proxyable outputs (e.g., custom
    user-defined objects containing tensors). The function may return complex Python
    objects for Dynamo to continue tracing, but only the tensor/symint VTs need to
    be registered as actual FX graph outputs.

    Example:
        class Foo:
            def __init__(self, a, b):
                self.a = a  # tensor
                self.b = b  # tensor

        def gn(x):
            return Foo(torch.sin(x), torch.cos(x))

        result = some_hop(gn, x)  # Returns Foo instance
        out = result.a + result.b  # Dynamo can continue tracing

    Here, `output` VT is a UserDefinedObjectVariable wrapping Foo, but
    `graph_output_vts` contains only the tensor VTs (a and b) that should be
    actual FX graph outputs. This allows Dynamo to continue tracing with the
    Foo object while the graph only needs to output the constituent tensors.

    ## Return Values

    Unlike `speculate_subgraph`, this function returns:
    - output: The VT that Dynamo continues tracing with (may be complex Python objects)
    - graph: The FX graph representing the subgraph computation
    - lifted_freevars: Free variables lifted as inputs to the subgraph
    - graph_output_vts: Only the tensor/symint VTs that are actual FX graph outputs

    The key difference is `graph_output_vts` instead of `treespec`, which gives more
    flexibility for handling non-proxyable outputs.
    """
    ...

def speculate_subgraph(tx: InstructionTranslator, f: VariableTracker, sub_args: Sequence[VariableTracker], sub_kwargs: dict[str, VariableTracker] | None, description: str, *, source_target: HigherOrderOperator | None = ..., always_restore: bool = ..., enable_grad: bool | None = ..., set_subgraph_inputs: Literal["automatic", "semi_automatic", "flatten_manual", "manual"] = ..., restore_side_effects: bool = ..., should_flatten_outputs: bool = ..., remove_consts_from_outputs: bool = ..., supports_input_mutation: bool = ..., supports_aliasing: bool = ..., tracer: Optional[SubgraphTracer] = ...) -> tuple[tuple[VariableTracker, OutputSpec], torch.fx.Graph, dict[Proxy, Proxy]]:
    ...

def make_attr(tx: InstructionTranslator, name: str) -> Proxy:
    ...

def add_hop_context(cls: type[HOP_VT_Alias]) -> type[HOP_VT_Alias]:
    """
    Class decorator that adds HOP context to exceptions raised in call_function.

    Requires the class to have _HOP_NAME and _ALLOW_FALLBACK_TO_EAGER set.
    """
    ...

class TorchHigherOrderOperatorVariable(VariableTracker):
    _HOP_NAME: Optional[str] = ...
    _ALLOW_FALLBACK_TO_EAGER: bool = ...
    def __init_subclass__(cls, **kwargs: Any) -> None:
        ...
    
    def __init__(self, value: HigherOrderOperator, source: Source | None = ..., **kwargs: Any) -> None:
        ...
    
    @staticmethod
    def make(value: HigherOrderOperator, source: Source | None = ..., **kwargs: Any) -> TorchHigherOrderOperatorVariable:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def as_python_constant(self) -> HigherOrderOperator:
        ...
    
    def is_python_hashable(self) -> bool:
        ...
    
    def get_python_hash(self) -> int:
        ...
    
    def is_python_equal(self, other: object) -> bool:
        ...
    


class CustomFunctionHigherOrderOperatorVariable(TorchHigherOrderOperatorVariable):
    """
    Wraps torch._functorch.autograd_function.custom_function_call
    """
    _HOP_NAME = ...


class CondHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...
    _ALLOW_FALLBACK_TO_EAGER = ...
    supports_input_mutation = ...
    supports_aliasing = ...


class CallTorchbindHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...
    def __init__(self, hop: HigherOrderOperator, source: Source | None, script_obj_var: Any, method_name: str) -> None:
        ...
    


def validate_subgraph_output_types(output: VariableTracker | Sequence[VariableTracker]) -> None:
    """Verify that that the output of the subgraph is a tensor,
    int, bool, SymBool, or SymInt.
    """
    ...

class WhileLoopHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...
    _ALLOW_FALLBACK_TO_EAGER = ...
    supports_input_mutation = ...
    supports_aliasing = ...


class WhileLoopStackOutputHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...
    _ALLOW_FALLBACK_TO_EAGER = ...
    supports_input_mutation = ...
    supports_aliasing = ...


class AssociativeScanHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...
    _ALLOW_FALLBACK_TO_EAGER = ...
    supports_input_mutation = ...
    supports_aliasing = ...


class ScanHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...
    _ALLOW_FALLBACK_TO_EAGER = ...
    supports_input_mutation = ...
    supports_aliasing = ...


class MapHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...
    _ALLOW_FALLBACK_TO_EAGER = ...
    supports_input_mutation = ...
    supports_aliasing = ...


class PrintHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...


class ExecutorchCallDelegateHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...


class FunctorchHigherOrderVariable(UserFunctionVariable):
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def should_allow_nested_graph_breaks(self) -> bool:
        ...
    


class FunctionalCallVariable(FunctorchHigherOrderVariable):
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class ReparametrizeModuleCallVariable(FunctorchHigherOrderVariable):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class WrapHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...
    supports_input_mutation = ...
    supports_aliasing = ...
    allow_side_effects = ...
    def install_subgraph_in_output_graph(self, tx: InstructionTranslator, fn_vt: VariableTracker, fn_args_vt: Sequence[VariableTracker], kwargs: dict[str, VariableTracker], body_gmod: GraphModule, attr_name: str = ...) -> str:
        ...
    
    def create_wrapped_node(self, tx: InstructionTranslator, fn_vt: VariableTracker, fn_args_vt: Sequence[VariableTracker], kwargs: dict[str, VariableTracker], description: str, *, subgraph_name: str = ...) -> tuple[tuple[Proxy, ...], dict[str, VariableTracker], Any, VariableTracker, GraphModule, str, VariableTracker | tuple[VariableTracker, ...],]:
        ...
    


class WrapWithSetGradEnabledHigherOrderVariable(TorchHigherOrderOperatorVariable):
    """
    This hop is not exposed to users but is inserted into the graph
    after export as a post-processing step.
    """
    _HOP_NAME = ...
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class WrapWithAutocastHigherOrderVariable(TorchHigherOrderOperatorVariable):
    """
    This hop is not exposed to users but is inserted into the graph
    after export as a post-processing step.
    """
    _HOP_NAME = ...
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class HintsWrapperHigherOrderVariable(WrapHigherOrderVariable):
    _HOP_NAME = ...
    _ALLOW_FALLBACK_TO_EAGER = ...
    def install_subgraph_in_output_graph(self, tx: InstructionTranslator, fn_vt: VariableTracker, fn_args_vt: Sequence[VariableTracker], kwargs: dict[str, VariableTracker], body_gmod: GraphModule, attr_name: str = ...) -> str:
        ...
    


class OutDtypeHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...


class StrictModeHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...
    _ALLOW_FALLBACK_TO_EAGER = ...


class CheckpointHigherOrderVariable(WrapHigherOrderVariable):
    _HOP_NAME = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    


class DynamoBypassingWrapperHigherOrderVariable(WrapHigherOrderVariable):
    _HOP_NAME = ...
    def __init__(self, hop: HigherOrderOperator, source: Source | None) -> None:
        ...
    


class ExportTracepointHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class RunWithRNGStateHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...


class AutoFunctionalizeHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...


class FlexAttentionBackwardHighOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...
    def proxy_submod(self, tx: InstructionTranslator, arg: UnspecializedNNModuleVariable) -> Proxy:
        ...
    
    def to_proxy(self, tx: InstructionTranslator, arg: VariableTracker) -> Any:
        ...
    


class TraceWrappedHigherOrderOperatorVariable(TorchHigherOrderOperatorVariable):
    """
    Handles torch._dynamo._trace_wrapped_higher_order_op.inner_trace
    by unwrapping the higher order op and inlining through it.  This op
    is created by dynamo to survive through AotAutograd, then unwrapped
    here in the call to dynamo from compiled autograd.
    """
    _HOP_NAME = ...


class FlexAttentionHigherOrderVariable(TorchHigherOrderOperatorVariable):
    _HOP_NAME = ...
    @staticmethod
    def normalize_to_args(args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> list[VariableTracker]:
        ...
    
    def create_wrapped_node(self, tx: InstructionTranslator, query: VariableTracker, fn: VariableTracker, fn_name: str) -> tuple[Proxy, tuple[Proxy, ...]]:
        ...
    


@add_hop_context
class AutogradFunctionApplyVariable(VariableTracker):
    _HOP_NAME: str = ...
    _ALLOW_FALLBACK_TO_EAGER = ...
    def __init__(self, fwd_fn: Any, bwd_fn: Any, parent_source: Source | None, **kwargs: Any) -> None:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        """
        At the highest level, the goal of tracing an autograd.Function is to
        essentially emit a new autograd.Function object. To do this, Dynamo
        traces fwd and bwd graph and then inserts a AutogradFunctionApply HOP in
        the graph that call the traced fwd and bwd graph in the `forward` and
        `backward` methods respectively. AOTDispatcher desugars this HOP and
        just inlines the hop fwd and bwd into the main graph during its tracing.

        However, the traced forward and backward graphs cannot be directly
        placed in the new autograd.Function because autograd.Function has some
        requirements.

        a) # fwd graph inputs = # bwd graph outputs
        b) # fwd graph outputs = # bwd graph inputs
        c) Since the graphs do not have ctx variable, we have to manually return
        the saved_tensors from the forward and have additional inputs in the
        backward, and wire the connections.

        Unfortunately, reworking the initial traced fwd and bwd graphs to
        satisfy the above 3 conditions leads to a very tedious codebase.

        Lets look at an example

        class Foo:
            def __init__(self):
                self.a = 4

        class MySin(torch.autograd.Function):
            @staticmethod
            def forward(ctx, x, foo):
                ctx.save_for_backward(x)
                return x.sin() + foo.a

            @staticmethod
            def backward(ctx, grad):
                x, = ctx.saved_tensors
                return grad * x.cos()

        We want the resulting graphs to look like:

        # Note that Dynamo lifts the foo_a directly as an input.
        def fwd(ctx, x, foo_a):
            # (output, saved tensors / attrs)
            return (x.sin() + foo_a, (x))

        # Note that backward graph has None as the second output to match the
        # fwd requirements (even though the original backward function has just
        # output)
        def bwd(ctx, grad, x):
            return grad * x.cos(), None


        To accomplish this, we're going to:
        1. Construct a ctx object
        2. Speculate subgraph forward
        3. Speculate subgraph backward
        4. rewired_bwd_graph_inputs - Use the traced fwd graph as the anchor point, and rewire the backward graph outputs
        5. handle_saved_tensors_wiring - Handle the saved tensors, as mentioned in (c)
        """
        ...
    
    def prepare_ctx_vt(self, tx: InstructionTranslator, args: Any, kwargs: Any) -> AutogradFunctionContextVariable:
        ...
    
    def trace_forward_graph(self, tx: InstructionTranslator, ctx: AutogradFunctionContextVariable, fwd_tracer: SubgraphTracer, args: Any, kwargs: Any) -> tuple[VariableTracker, VariableTracker, torch.fx.Graph, dict[Proxy, Proxy], VariableTracker | tuple[VariableTracker, ...],]:
        """
        Traces the forward method of the autograd.Function object.
        """
        ...
    
    def trace_backward_graph(self, tx: InstructionTranslator, ctx: AutogradFunctionContextVariable, fwd_tracer: SubgraphTracer, fwd_out: VariableTracker, fwd_fn: VariableTracker) -> tuple[Sequence[VariableTracker], VariableTracker, torch.fx.Graph, dict[Proxy, Proxy], VariableTracker | tuple[VariableTracker, ...],]:
        """
        Traces the backward method of the autograd.Function object.
        """
        ...
    
    def rewire_bwd_graph_outputs(self, fwd_freevars: dict[Proxy, Proxy], bwd_out: VariableTracker, bwd_graph: torch.fx.Graph, bwd_freevars: dict[Proxy, Proxy], orig_fwd_args: Sequence[VariableTracker]) -> None:
        ...
    
    def handle_saved_tensors_wiring(self, fwd_out: VariableTracker, fwd_graph: torch.fx.Graph, fwd_freevars: dict[Proxy, Proxy], fwd_graph_body_outputs: Sequence[VariableTracker], bwd_graph: torch.fx.Graph, bwd_freevars: dict[Proxy, Proxy]) -> tuple[torch.fx.Graph, torch.fx.Graph]:
        ...
    
    def prepare_fn_vt(self, tx: InstructionTranslator, ctx: AutogradFunctionContextVariable, method_name: str, args: Sequence[VariableTracker]) -> tuple[VariableTracker, Sequence[VariableTracker]]:
        ...
    


def maybe_positional_arg_names(func: VariableTracker) -> list[str] | None:
    ...

class BaseHOPVariable(WrapHigherOrderVariable):
    _HOP_NAME = ...
    supports_input_mutation = ...
    supports_aliasing = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        ...
    
    def python_type(self) -> type:
        ...
    


class InvokeSubgraphHigherOrderVariable(WrapHigherOrderVariable):
    _HOP_NAME = ...
    _ALLOW_FALLBACK_TO_EAGER = ...
    supports_input_mutation = ...
    supports_aliasing = ...
    allow_side_effects = ...
    filter_aliased_intermediates = ...
    def install_subgraph_in_output_graph(self, tx: InstructionTranslator, fn_vt: VariableTracker, fn_args_vt: Sequence[VariableTracker], kwargs: dict[str, VariableTracker], body_gmod: GraphModule, attr_name: str) -> str:
        ...
    


class LocalMapWrappedHigherOrderVariable(WrapHigherOrderVariable):
    _HOP_NAME = ...
    supports_input_mutation = ...
    supports_aliasing = ...
    _enabled = ...
    @classmethod
    @contextlib.contextmanager
    def enable(cls) -> Generator[None, None, None]:
        """Context manager to temporarily enable local map wrapping.
        Will be removed when speculate_subgraph supports subclass inputs:
        https://github.com/pytorch/pytorch/issues/161456.

        Usage:
            with LocalMapWrappedHigherOrderVariable.enable_wrapping():
                # Code where should_wrap_in_hop will return True
                pass
        """
        ...
    
    @classmethod
    def should_wrap_in_hop(cls, value: Any) -> bool:
        ...
    
    @staticmethod
    def build(**options: Any) -> TorchHigherOrderOperatorVariable:
        ...
    
    def python_type(self) -> type:
        ...
    


_hop_name_to_variable_class = ...
