"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Sequence
from typing import Any, TYPE_CHECKING, Union
from .base import VariableTracker
from .constant import ConstantVariable
from torch._dynamo.codegen import PyCodegen
from torch._dynamo.symbolic_convert import InstructionTranslator

"""
This module provides iterator-related variable tracking functionality for Dynamo.
It implements variable classes for handling Python iterators and itertools functions
during symbolic execution and tracing.

The module includes:
- Base iterator variable classes for tracking iterator state
- Implementations of built-in iterators (zip, map, filter)
- Support for itertools functions (product, accumulate, combinations, etc.)
- Mutation tracking and reconstruction capabilities for iterator operations

These classes integrate with Dynamo's variable tracking system to enable proper
handling of iterator operations during code transformation and optimization.
"""
if TYPE_CHECKING:
    ...
MAX_ITERATOR_LIMIT = ...
class ItertoolsVariable(VariableTracker):
    def __init__(self, value: Any, **kwargs: Any) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class IteratorVariable(VariableTracker):
    def __init__(self, **kwargs: Any) -> None:
        ...
    
    def next_variable(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def force_unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def force_apply_to_var_sequence(self, tx: InstructionTranslator, fn: Callable[[Any], Any]) -> None:
        ...
    
    def has_force_unpack_var_sequence(self, tx: InstructionTranslator) -> bool:
        ...
    
    def call_obj_hasattr(self, tx: InstructionTranslator, name: str) -> ConstantVariable:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class ObjectIteratorVariable(IteratorVariable):
    """
    VariableTracker for iter(obj) that implements the iterator protocol (i.e.,
    has a `__next__` method).

    We use this class to track the state of the iterator and handle the case
    when the iterator is exhausted:

    Example usage:
        > b = iter(obj)
        > list(b)  # exhaust the iterator
        > list(b)  # empty list
    """
    def __init__(self, obj: VariableTracker, **kwargs: Any) -> None:
        ...
    
    def next_variable(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    


class RepeatIteratorVariable(IteratorVariable):
    def __init__(self, item: VariableTracker, **kwargs: Any) -> None:
        ...
    
    def next_variable(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


class CountIteratorVariable(IteratorVariable):
    def __init__(self, item: Union[int, VariableTracker] = ..., step: Union[int, VariableTracker] = ..., **kwargs: Any) -> None:
        ...
    
    def next_variable(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


class ZipVariable(IteratorVariable):
    """
    Represents zip(*iterables)
    """
    _nonvar_fields = ...
    def __init__(self, iterables: list[VariableTracker], strict: bool = ..., **kwargs: Any) -> None:
        ...
    
    def python_type(self) -> type[zip]:
        ...
    
    def has_unpack_var_sequence(self, tx: InstructionTranslator) -> bool:
        ...
    
    def unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def next_variable(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def reconstruct_items(self, codegen: PyCodegen) -> None:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


class MapVariable(ZipVariable):
    """
    Represents map(fn, *iterables)
    """
    def __init__(self, fn: VariableTracker, iterables: list[VariableTracker], **kwargs: Any) -> None:
        ...
    
    def python_type(self) -> type:
        ...
    
    def has_unpack_var_sequence(self, tx: InstructionTranslator) -> bool:
        ...
    
    def next_variable(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


class FilterVariable(IteratorVariable):
    """
    Represents filter(fn, iterable)
    """
    _nonvar_fields = ...
    def __init__(self, fn: VariableTracker, iterable: list[VariableTracker], **kwargs: Any) -> None:
        ...
    
    def python_type(self) -> type:
        ...
    
    def has_unpack_var_sequence(self, tx: InstructionTranslator) -> bool:
        ...
    
    def unpack_var_sequence(self, tx: InstructionTranslator) -> list[VariableTracker]:
        ...
    
    def next_variable(self, tx: InstructionTranslator) -> VariableTracker:
        ...
    
    def reconstruct_items(self, codegen: PyCodegen) -> None:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


