"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable, Sequence
from typing import Any, Optional, TYPE_CHECKING, TypeVar
from typing_extensions import ParamSpec
from torch._guards import Source
from torch.fx.proxy import Proxy
from .base import VariableTracker
from .user_defined import UserDefinedObjectVariable, UserDefinedVariable
from torch._dynamo.symbolic_convert import InstructionTranslator

"""
This module implements variable tracking for TorchScript objects during Dynamo tracing.

The TorchScriptObjectVariable class provides specialized handling for TorchScript
objects with strong safety guarantees by:
- Enforcing method-call-only access to prevent unsafe attribute manipulation
- Converting graph breaks into hard errors via _raise_hard_error_if_graph_break
- Proper proxy and source tracking for TorchScript method calls
- Integration with higher-order operators for method call handling

Key safety features:
- Strict validation that only method calls are allowed (no direct attribute access)
- Immediate error reporting for potentially unsafe operations
- Proper source tracking for debugging and guard installation
- Safe handling of TorchScript object method calls through torchbind

The module ensures that TorchScript objects are handled safely during tracing
by limiting operations to known-safe patterns and failing fast for unsafe usage.
"""
if TYPE_CHECKING:
    ...
_P = ParamSpec("_P")
_T = TypeVar("_T")
class OpaqueObjectClassVariable(UserDefinedVariable):
    """
    A variable that represents an opaque object class (not instance).
    Since UserDefinedClassVariable has some special handling for side effects,
    we have a separate class here which will directly return the object when
    __init__ is called.
    """
    def __init__(self, value: Any, **kwargs: Any) -> None:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def is_python_constant(self) -> bool:
        ...
    
    def is_python_hashable(self) -> bool:
        ...
    
    def as_proxy(self) -> Any:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    def call_function(self, tx: InstructionTranslator, args: Sequence[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    


class TorchScriptObjectVariable(UserDefinedObjectVariable):
    _fake_script_object_cache: dict[int, TorchScriptObjectVariable] = ...
    @classmethod
    def is_matching_cls(cls, user_cls: type) -> bool:
        ...
    
    @staticmethod
    def create(proxy: Proxy, value: Any, ctor_args_kwargs: Any = ..., **options: Any) -> TorchScriptObjectVariable:
        ...
    
    def __init__(self, proxy: Proxy, value: Any, ctor_args_kwargs: Any = ..., source: Optional[Source] = ..., **kwargs: Any) -> None:
        ...
    
    def as_proxy(self) -> Proxy:
        ...
    
    @_raise_hard_error_if_graph_break("Dynamo cannot safely trace script object due to graph break.")
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    @_raise_hard_error_if_graph_break("Dynamo cannot safely trace script object due to graph break.")
    def call_method(self, tx: InstructionTranslator, name: str, args: Iterable[Any], kwargs: dict[str, Any]) -> VariableTracker:
        ...
    
    def as_python_constant(self) -> Any:
        ...
    
    def is_python_hashable(self) -> bool:
        ...
    


