"""
This type stub file was generated by pyright.
"""

from collections.abc import Sequence
from typing import Any, TYPE_CHECKING, TypeGuard
from torch._guards import Source
from torch.backends.cuda import SDPAParams
from torch.fx.proxy import Proxy
from .base import VariableTracker
from torch._dynamo.codegen import PyCodegen
from torch._dynamo.symbolic_convert import InstructionTranslator

if TYPE_CHECKING:
    ...
PARAM_NAMES = ...
class SDPAParamsVariable(VariableTracker):
    """Represents the c++ params struct for scaled dot product attention.
    This is a read-only container."""
    @staticmethod
    def create(tx: InstructionTranslator, value: Any, source: Source) -> VariableTracker:
        ...
    
    def __init__(self, proxy: Proxy, param_vars: Sequence[VariableTracker], **kwargs: Any) -> None:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def as_proxy(self) -> Proxy:
        ...
    
    def var_getattr(self, tx: InstructionTranslator, name: str) -> VariableTracker:
        ...
    
    @staticmethod
    def is_sdpa_params(value: Any) -> TypeGuard[SDPAParams]:
        ...
    


