"""
This type stub file was generated by pyright.
"""

import torch
from collections.abc import Callable
from typing import Any, Optional
from torch._dynamo.variables.dicts import ConstDictVariable
from torch._dynamo.variables.lists import TupleVariable
from torch.fx import Proxy
from ..exc import TYPE_CHECKING
from .base import VariableTracker
from .ctx_manager import FxTracebackAnnotateVariable
from torch._dynamo.symbolic_convert import InstructionTranslator
from ..codegen import PyCodegen
from torch._library.custom_ops import custom_op

if TYPE_CHECKING:
    ...
Tensor = torch.Tensor
def new_event(*args: Any, **kwargs: Any) -> int:
    ...

def new_stream(*args: tuple[Any], **kwargs: Any) -> int:
    ...

def get_current_stream(device: torch.device) -> int:
    ...

@custom_op("streams::fork", mutates_args=())
def fork_stream(from_index: int, to_index: int) -> None:
    ...

@fork_stream.register_fake
def _(from_index: int, to_index: int) -> None:
    ...

@custom_op("streams::join", mutates_args=())
def join_stream(from_index: int, to_index: int) -> None:
    ...

@join_stream.register_fake
def _(from_index: int, to_index: int) -> None:
    ...

@custom_op("streams::record_event", mutates_args=())
def record_event(event_index: int, stream_index: int) -> None:
    ...

@record_event.register_fake
def _(event_index: int, stream_index: int) -> None:
    ...

@custom_op("streams::wait_event", mutates_args=())
def wait_event(event_index: int, stream_index: int) -> None:
    ...

@wait_event.register_fake
def _(event_index: int, stream_index: int) -> None:
    ...

@custom_op("streams::wait_stream", mutates_args=())
def wait_stream(waiting_stream_index: int, waited_on_stream_index: int) -> None:
    ...

@wait_stream.register_fake
def _(event_index: int, stream_index: int) -> None:
    ...

@custom_op("streams::sync_dealloc", mutates_args=())
def sync_dealloc(wait_event_index: int, src_stream_index: int, to_dealloc: torch.Tensor) -> None:
    """An op which waits on an event and moves the last usage of to_dealloc
    after the wait, so that after the sync occurs, the deallocation or
    subsequent reuse of the tensor's memory will be guaranteed to happen
    after a side stream is finished using it.
    See https://docs.pytorch.org/docs/stable/generated/torch.Tensor.record_stream.html#torch.Tensor.record_stream
    for more details"""
    ...

@custom_op("streams::record_stream", mutates_args=())
def record_stream(tensor: torch.Tensor, stream_index: int) -> None:
    ...

@record_stream.register_fake
def _(src_stream_index: int, wait_event_index: int, to_dealloc: torch.Tensor) -> None:
    ...

class SymbolicStreamState:
    """Track the currently entered stream if any"""
    def __init__(self) -> None:
        ...
    
    def enter_stream(self, stream: StreamVariable) -> None:
        ...
    
    def exit_stream(self) -> None:
        ...
    
    def cur_stream(self, device: Optional[torch.device] = ...) -> StreamVariable:
        ...
    
    def in_stream_context(self) -> bool:
        ...
    


class StreamContextVariable(FxTracebackAnnotateVariable):
    """This represents torch.cuda.StreamContext"""
    @staticmethod
    def create(tx: InstructionTranslator, stream_to_enter: StreamVariable, **kwargs: dict[str, Any]) -> StreamContextVariable:
        ...
    
    def __init__(self, stream: Optional[StreamVariable], **kwargs: Any) -> None:
        ...
    
    def enter(self, tx: InstructionTranslator, *args: VariableTracker) -> VariableTracker:
        ...
    
    def exit(self, tx: InstructionTranslator, *args: VariableTracker) -> VariableTracker:
        ...
    
    def supports_graph_breaks(self) -> bool:
        ...
    
    def get_stream(self) -> StreamVariable:
        ...
    


class StreamVariable(StreamContextVariable):
    """Represents the device-agnostic torch.Stream class"""
    def __init__(self, proxy: Proxy, value: torch.Stream, user_object_index: Optional[int] = ..., **kwargs: Any) -> None:
        ...
    
    def python_type(self) -> type:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def as_proxy(self) -> Proxy:
        ...
    
    def module_name(self) -> str:
        ...
    
    def fn_name(self) -> str:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    
    def get_stream(self) -> StreamVariable:
        ...
    
    @staticmethod
    def make_construct_in_graph_stream_fn(args: TupleVariable, kwargs: ConstDictVariable) -> Callable[[int, PyCodegen], None]:
        ...
    


class EventVariable(VariableTracker):
    def __init__(self, proxy: Proxy, value: torch.Event, user_object_index: Optional[int], **kwargs: Any) -> None:
        ...
    
    def call_method(self, tx: InstructionTranslator, name: str, args: list[VariableTracker], kwargs: dict[str, VariableTracker]) -> VariableTracker:
        ...
    
    def as_proxy(self) -> Proxy:
        ...
    
    @staticmethod
    def make_construct_in_graph_event_fn(args: TupleVariable, kwargs: ConstDictVariable) -> Callable[[int, PyCodegen], None]:
        ...
    
    def reconstruct(self, codegen: PyCodegen) -> None:
        ...
    


