"""
This type stub file was generated by pyright.
"""

import torch
from dataclasses import dataclass
from typing import TYPE_CHECKING
from .gemm import GemmMaxAutotuneTemplateConfigHeuristics
from ..kernel_inputs import KernelInputs, MMKernelInputs

if TYPE_CHECKING:
    ...
log = ...
autotuning_log = ...
ConfigKey = tuple[int, int, int, int, int]
@dataclass
class HeuristicConfig:
    """Configuration recommended by nvMatmulHeuristics."""
    tile_m: int
    tile_n: int
    tile_k: int
    cluster_m: int
    cluster_n: int
    stages: int
    split_k: int
    warp_tile_m: int
    warp_tile_n: int
    warp_tile_k: int
    estimated_runtime: float
    ...


class NVUniversalGemmHeuristics(GemmMaxAutotuneTemplateConfigHeuristics):
    """
    Heuristics for NVGEMM kernel selection using nvMatmulHeuristics.
    """
    def should_run(self, inputs: KernelInputs) -> bool:
        """Check if heuristics should be used.

        Args:
            inputs: KernelInputs
        """
        ...
    
    def filter_kernels(self, kernels: list, inputs: MMKernelInputs, count: int, accumulator_type: torch.dtype = ...) -> list:
        """
        Filter and rank kernels using nvMatmulHeuristics.

        Matches on (tile_m, tile_n, tile_k, cluster_m, cluster_n).
        Returns kernels sorted by estimated runtime.

        If nvMatmulHeuristics is not installed or max_autotune is disabled,
        returns the first `count` kernels without heuristic ranking.

        Args:
            kernels: List of cutlass_api.Kernel objects
            inputs: MMKernelInputs with matrix shapes, dtypes, and strides
            count: Maximum number of kernels to return
            accumulator_type: Accumulator dtype

        Returns:
            Filtered list of kernels, sorted by estimated performance
        """
        ...
    


_nvgemm_heuristics: NVUniversalGemmHeuristics | None = ...
def get_nvgemm_heuristics() -> NVUniversalGemmHeuristics:
    """Get the singleton NVUniversalGemmHeuristics instance."""
    ...

