"""
This type stub file was generated by pyright.
"""

import dataclasses
import sympy
import torch
from functools import partial
from threading import Lock
from typing import Any, Optional, TYPE_CHECKING
from torch._inductor.template_heuristics.triton_addmm import AddMMConfigMixin
from ..kernel.bmm import bmm_template
from ..kernel.mm import blackwell_ws_persistent_device_tma_mm_template, mm_template, persistent_tma_mm_template, scaled_mm_device_tma_epilogue_scaling_template, scaled_mm_device_tma_main_loop_scaling_template
from ..kernel.mm_plus_mm import mm_plus_mm_template
from ..kernel_inputs import KernelInputs
from .gemm import GemmMaxAutotuneTemplateConfigHeuristics
from .registry import register_template_heuristic
from collections.abc import Callable, Generator
from triton import Config as TritonConfig

if TYPE_CHECKING:
    ...
else:
    ...
@dataclasses.dataclass
class BaseConfig:
    """
    Base Gemm configuration used for most backends (CPU, CUDA)
    """
    block_m: int
    block_n: int
    block_k: int
    num_stages: int
    num_warps: int
    hint_override: Optional[int] = ...


@dataclasses.dataclass
class GemmConfig(BaseConfig):
    """
    Gemm configuration used for most backends (CPU, CUDA)
    """
    group_m: int = ...


ConvConfig = BaseConfig
@dataclasses.dataclass
class BlackwellGPUGemmConfig(GemmConfig):
    """
    Gemm configuration used for templates with features explicitly
    targeting Nvidia Blackwell GPUs
    """
    epilogue_subtile: int = ...
    warp_specialize: bool = ...
    flatten: bool = ...


@dataclasses.dataclass
class FlexConfig:
    """
    Base Config class for flex attention
    - FlexAttn forward and backward will use this. For flex decoding,
      please use FlexDecodingConfig.

    NOTE:
    For flex_attn bwd block_m and block_n are reused for block_m1, block_m2, block_n1, block_n2

    """
    block_m: int
    block_n: int
    num_stages: int
    num_warps: int
    ...


@dataclasses.dataclass
class FlexBwDConfig:
    """
    Base Config class for flex attention backward
    - FlexAttn backward will use this.

    Note: flex bwd configs

    Kernel Constraints:
      * BLOCK_N1 % BLOCK_M1 == 0
      * BLOCK_M2 % BLOCK_N2 == 0

    Pattern 1 - Symmetric Pairing (M, N, N, M):
    - Used in autotune configs
    - block_m1=M, block_n1=N, block_m2=N, block_n2=M
    - Only requires checking BLOCK_N % BLOCK_M == 0
    - Second constraint (BLOCK_M2 % BLOCK_N2) automatically satisfied

    Pattern 2 - Independent Parameters (M1, N1, M2, N2):
    - Used in exhaustive search for maximum flexibility
    - All four parameters can be set independently
    - Requires checking both constraints

    """
    block_m1: int
    block_n1: int
    block_m2: int
    block_n2: int
    num_stages: int
    num_warps: int
    ...


@dataclasses.dataclass
class FlexDecodeConfig:
    """
    Config class for flex decoding
    """
    block_n: int
    num_stages: int
    num_warps: int
    ...


@dataclasses.dataclass
class ROCmGemmConfig(GemmConfig):
    """
    ROCm subclass for GEMMs, with AMD backend specific tuneable kernargs
    """
    matrix_instr_nonkdim: int = ...
    waves_per_eu: int = ...
    kpack: int = ...


@dataclasses.dataclass
class ROCmConvConfig(ConvConfig):
    """
    ROCm subclass for Conv, with AMD backend specific tuneable kernargs
    """
    matrix_instr_nonkdim: int = ...
    waves_per_eu: int = ...
    kpack: int = ...


@dataclasses.dataclass
class ROCmFlexConfig(FlexConfig):
    """
    ROCm subclass for FlexAttn, with AMD backend specific tuneable kernargs
    """
    matrix_instr_nonkdim: int = ...
    waves_per_eu: int = ...
    kpack: int = ...


@dataclasses.dataclass
class ROCmFlexBwDConfig(FlexBwDConfig):
    """
    ROCm subclass for FlexAttn backward, with AMD backend specific tuneable kernargs
    """
    matrix_instr_nonkdim: int = ...
    waves_per_eu: int = ...
    kpack: int = ...


@dataclasses.dataclass
class ROCmFlexDecodeConfig(FlexDecodeConfig):
    """
    ROCm subclass for FlexDecode, with AMD backend specific tuneable kernargs
    """
    matrix_instr_nonkdim: int = ...
    waves_per_eu: int = ...
    kpack: int = ...


class BaseHeuristicSingleton(type):
    """
    Thread-safe implementation of single to be used in the config heuristic subclasses
    to ensure heavy __init__ calls are not repeatedly run
    """
    _instances: dict[type[Any], Any] = ...
    _lock: Lock = ...
    def __call__(cls: BaseHeuristicSingleton, *args: Any, **kwargs: Any) -> BaseConfigHeuristic:
        ...
    


class BaseConfigHeuristic(metaclass=BaseHeuristicSingleton):
    """
    Base class for mm_configs, device specific triton kernels config inherit from here
    """
    def __init__(self) -> None:
        ...
    
    def get_shared_memory_estimation(self, gemm_config: BaseConfig, dtype_size: int, has_sm_layout_conversion: bool, layout_conversion_byte_size: int) -> int:
        ...
    
    def preprocess_mm_configs(self, m: int, n: int, k: int, configs: list[BaseConfig], has_int8_tensor: bool = ..., scale: float = ..., exclude: Callable[[sympy.Integer, sympy.Integer, sympy.Integer], bool] = ..., dtype_size: int = ..., op_name: str = ..., **kwargs) -> Generator[TritonConfig, None, None]:
        ...
    
    def triton_config(self, num_stages: int, num_warps: int, **kwargs: Any) -> TritonConfig:
        ...
    
    def get_mm_configs(self) -> partial[Generator[TritonConfig, None, None]]:
        ...
    
    def get_exhaustive_mm_configs(self) -> partial[Generator[TritonConfig, None, None]]:
        ...
    
    def get_conv_configs(self) -> partial[Generator[TritonConfig, None, None]]:
        ...
    
    def get_flex_attn_fwd_configs(self, head_dim: int, dtype: Any) -> list[FlexConfig]:
        ...
    
    def get_flex_attn_bwd_configs(self, head_dim: int, dtype: Any) -> list[FlexBwDConfig]:
        ...
    
    def get_flex_decode_configs(self, head_dim: int, dtype: Any) -> list[FlexDecodeConfig]:
        ...
    


class CPUConfigHeuristic(BaseConfigHeuristic):
    """
    CPU-specific config heuristic with CPU-specific optimizations.
    """
    def preprocess_mm_configs(self, m: int, n: int, k: int, configs: list[BaseConfig], has_int8_tensor: bool = ..., scale: float = ..., exclude: Callable[[sympy.Integer, sympy.Integer, sympy.Integer], bool] = ..., dtype_size: int = ..., op_name: str = ..., **kwargs) -> Generator[TritonConfig, None, None]:
        """
        CPU-specific preprocessing that applies CPU-specific scaling (0.5) and exclusion logic.
        """
        ...
    


class CUDAConfigHeuristic(BaseConfigHeuristic):
    """
    Child class for CUDA device specific gemm/flex attention/conv/ configs.
    """
    def __init__(self) -> None:
        ...
    
    def get_flex_attn_fwd_configs(self, head_dim: int, dtype: Any) -> list[FlexConfig]:
        ...
    
    def get_flex_attn_bwd_configs(self, head_dim: int, dtype: Any) -> list[FlexBwDConfig]:
        ...
    
    def get_flex_decode_configs(self, head_dim: int, dtype: Any) -> list[FlexDecodeConfig]:
        ...
    


class ROCmConfigHeuristic(BaseConfigHeuristic):
    """
    Child class for ROCm specific gemm/flex attention/conv/ configs.
    """
    def __init__(self) -> None:
        ...
    
    def get_flex_attn_fwd_configs(self, head_dim: int, dtype: Any) -> list[FlexConfig]:
        ...
    
    def get_flex_attn_bwd_configs(self, head_dim: int, dtype: Any) -> list[FlexBwDConfig]:
        ...
    
    def get_flex_decode_configs(self, head_dim: int, dtype: Any) -> list[FlexDecodeConfig]:
        ...
    


class XPUConfigHeuristic(BaseConfigHeuristic):
    """
    Placeholder child class for Intel GPU specific overrides.
    """
    def __init__(self) -> None:
        ...
    
    def get_flex_attn_fwd_configs(self, head_dim: int, dtype: Any) -> list[FlexConfig]:
        ...
    
    def get_flex_attn_bwd_configs(self, head_dim: int, dtype: Any) -> list[FlexBwDConfig]:
        ...
    
    def get_flex_decode_configs(self, head_dim: int, dtype: Any) -> list[FlexDecodeConfig]:
        ...
    


class MTIAConfigHeuristic(BaseConfigHeuristic):
    """
    Placeholder child class for MTIA specific overrides.
    """
    ...


class MMTemplateConfigMixin(GemmMaxAutotuneTemplateConfigHeuristics):
    """
    Mixin class that converts config lists to template kwargs.
    This handles the logic that was previously in choices.get_mm_configs.

    This mixin expects to be used with BaseConfigHeuristic or its subclasses.
    """
    get_mm_configs: Callable[[], partial[Generator[TritonConfig, None, None]]]
    get_exhaustive_mm_configs: Callable[[], partial[Generator[TritonConfig, None, None]]]
    _filter_configs: Callable[[list[BaseConfig]], list[BaseConfig]]
    def get_extra_kwargs(self, kernel_inputs: KernelInputs, op_name: str) -> dict[str, Any]:
        ...
    


class INT8MMTemplateConfigMixin(MMTemplateConfigMixin):
    """
    Ensure that we feed in has_int8_tensor=True
    """
    def __init__(self) -> None:
        ...
    


class MMPlusMMTemplateConfigMixin(MMTemplateConfigMixin):
    """
    Ensure that _should_scale_configs is False
    """
    def __init__(self) -> None:
        ...
    


class TMAWorkspaceMixin(MMTemplateConfigMixin):
    """
    Small mixin to ensure that the workspace arg is correct for TMA
    and TMA specific filtering can happen.
    """
    def get_extra_kwargs(self, kernel_inputs: KernelInputs, op_name: str) -> dict[str, Any]:
        ...
    


def get_shared_memory_checker_opts(op_name: str, dtype_size: int) -> dict[str, Any]:
    ...

class TMATemplateConfigMixin(TMAWorkspaceMixin, MMTemplateConfigMixin):
    """
    TMA-specific mixin that uses persistent configs and adds TMA options.
    This inherits from MMTemplateConfigMixin and overrides config generation.
    """
    ...


class BlackwellTMATemplateConfigMixin(TMATemplateConfigMixin):
    ...


class BaseScaledMMConfigMixin(MMTemplateConfigMixin):
    """
    This is a base that handles the common case for ScaledMM

    The TMA and non-TMA should build on top of this
    """
    def adjust_kernel_inputs(self, kernel_inputs: KernelInputs, op_name: str) -> KernelInputs:
        """
        for scaled_mm, we need to unsqueeze scale tensors, and bias
        """
        ...
    


class ScaledMMConfigMixin(BaseScaledMMConfigMixin):
    """Mixing for scaled mm with the regular mm template"""
    def get_extra_kwargs(self, kernel_inputs: KernelInputs, op_name: str) -> dict[str, Any]:
        ...
    


class ScaledTMAConfigMixin(TMAWorkspaceMixin, BaseScaledMMConfigMixin):
    """
    Scaled TMA-specific mixin that extends BaseScaledMMConfigMixin with TMA functionality.
    This is for scaled MM templates that use device TMA.
    This inherits from BaseScaledMMConfigMixin and adds TMA-specific options.
    """
    ...


class ScaledBlackwellTMAConfigMixin(BlackwellTMATemplateConfigMixin, ScaledMMConfigMixin):
    """
    Scaled Blackwell TMA-specific mixin that extends ScaledMMConfigMixin with TMA functionality.
    This is for scaled MM templates that use device TMA on Blackwell.
    This inherits from ScaledMMConfigMixin, which inherits the scale_mm_epilogue, and adds TMA-specific options.
    """
    ...


@register_template_heuristic(mm_template.uid, "cuda", register=torch.version.hip is None)
@register_template_heuristic(bmm_template.uid, "cuda", register=torch.version.hip is None)
class CUDAMMTemplateConfigHeuristic(MMTemplateConfigMixin, CUDAConfigHeuristic):
    """Standard MM template heuristic for CUDA"""
    ...


@register_template_heuristic(mm_template.uid, "cuda", register=torch.version.hip is None, op_name="addmm")
@register_template_heuristic(bmm_template.uid, "cuda", register=torch.version.hip is None, op_name="baddbmm")
class CUDAAddMMTemplateConfigHeuristic(AddMMConfigMixin, CUDAMMTemplateConfigHeuristic):
    """Addmm specific mixin for CUDA"""
    ...


@register_template_heuristic(mm_template.uid, "cuda", register=torch.version.hip is None, op_name="mm-ah")
class CUDAMMAHTemplateConfigHeuristic(MMTemplateConfigMixin, CUDAConfigHeuristic):
    """Standard MM template heuristic for CUDA using the extra mm configs only (for autoheuristic)"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(persistent_tma_mm_template.uid, "cuda", register=torch.version.hip is None)
class CUDAPersistentTMATemplateConfigHeuristic(TMATemplateConfigMixin, CUDAConfigHeuristic):
    """Persistent TMA template heuristic for CUDA"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(blackwell_ws_persistent_device_tma_mm_template.uid, "cuda", register=torch.version.hip is None)
class CUDABlackwellPersistentTMATemplateConfigHeuristic(BlackwellTMATemplateConfigMixin, CUDAConfigHeuristic):
    """Blackwell Persistent TMA template"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(persistent_tma_mm_template.uid, "cuda", register=torch.version.hip is None, op_name="addmm")
class CUDAAddmmPersistentTMATemplateConfigHeuristic(AddMMConfigMixin, CUDAPersistentTMATemplateConfigHeuristic):
    """Addmm specific mixin for CUDA"""
    ...


@register_template_heuristic(blackwell_ws_persistent_device_tma_mm_template.uid, "cuda", register=torch.version.hip is None, op_name="addmm")
class CUDABlackwellAddmmPersistentTMATemplateConfigHeuristic(AddMMConfigMixin, CUDABlackwellPersistentTMATemplateConfigHeuristic):
    """Addmm extension for DataCenter Blackwell Templates"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_template.uid, "cuda", register=torch.version.hip is None, op_name="scaled_mm")
class CUDAScaledMMTemplateConfigHeuristic(ScaledMMConfigMixin, CUDAConfigHeuristic):
    """Scaled MM template heuristic for CUDA"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(scaled_mm_device_tma_epilogue_scaling_template.uid, "cuda", register=torch.version.hip is None, op_name="scaled_mm")
class CUDAScaledTMAEpilogueScalingTemplateConfigHeuristic(ScaledTMAConfigMixin, CUDAConfigHeuristic):
    """Scaled TMA template heuristic for CUDA: epilogue scaling variants (TensorWise, RowWise)"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(scaled_mm_device_tma_main_loop_scaling_template.uid, "cuda", register=torch.version.hip is None, op_name="scaled_mm")
class CUDAScaledTMAMainLoopScalingTemplateConfigHeuristic(ScaledTMAConfigMixin, CUDAConfigHeuristic):
    """
    Scaled TMA template heuristic for CUDA:
        main loop scaling variants (BlockWise1x128, BlockWise1x32, BlockWise1x16, BlockWise128x128)
    """
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(blackwell_ws_persistent_device_tma_mm_template.uid, "cuda", register=torch.version.hip is None, op_name="scaled_mm")
class CUDAScaledBlackwellTMATemplateConfigHeuristic(ScaledBlackwellTMAConfigMixin, CUDAConfigHeuristic):
    """Scaled Blackwell TMA template heuristic for CUDA"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_plus_mm_template.uid, "cuda", register=torch.version.hip is None)
class CUDAMMPlusMMTemplateConfigHeuristic(MMPlusMMTemplateConfigMixin, CUDAConfigHeuristic):
    """MM Plus MM template heuristic for CUDA"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_template.uid, "cuda", register=torch.version.hip is None, op_name="int_mm")
class CUDAInt8MMTemplateConfigHeuristic(INT8MMTemplateConfigMixin, CUDAConfigHeuristic):
    """Int8 MM template heuristic for CUDA"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_template.uid, "cuda", register=torch.version.hip is not None)
@register_template_heuristic(bmm_template.uid, "cuda", register=torch.version.hip is not None)
class ROCmMMTemplateConfigHeuristic(MMTemplateConfigMixin, ROCmConfigHeuristic):
    """Standard MM template heuristic for ROCm"""
    ...


@register_template_heuristic(mm_template.uid, "cuda", register=torch.version.hip is not None, op_name="addmm")
@register_template_heuristic(bmm_template.uid, "cuda", register=torch.version.hip is not None, op_name="baddbmm")
class ROCmAddMMTemplateConfigHeuristic(AddMMConfigMixin, ROCmMMTemplateConfigHeuristic):
    """Addmm specific mixin for ROCm"""
    ...


@register_template_heuristic("mm-ah", "cuda", register=torch.version.hip is not None)
class ROCmMMAHTemplateConfigHeuristic(MMTemplateConfigMixin, ROCmConfigHeuristic):
    """Standard MM template heuristic for ROCm using the extra mm configs only (for autoheuristic)"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_template.uid, "cuda", register=torch.version.hip is not None, op_name="scaled_mm")
class ROCmScaledMMTemplateConfigHeuristic(ScaledMMConfigMixin, ROCmConfigHeuristic):
    """Scaled MM template heuristic for ROCm (non-TMA)"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_template.uid, "cuda", register=torch.version.hip is not None, op_name="int_mm")
class ROCmInt8MMTemplateConfigHeuristic(INT8MMTemplateConfigMixin, ROCmConfigHeuristic):
    """Int8 MM template heuristic for ROCm"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_plus_mm_template.uid, "cuda", register=torch.version.hip is not None)
class ROCmMMPlusMMTemplateConfigHeuristic(MMPlusMMTemplateConfigMixin, ROCmConfigHeuristic):
    """MM Plus MM template heuristic for ROCm"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_template.uid, "cpu")
@register_template_heuristic(bmm_template.uid, "cpu")
class CPUMMTemplateConfigHeuristic(MMTemplateConfigMixin, CPUConfigHeuristic):
    """Standard MM template heuristic for CPU"""
    ...


@register_template_heuristic(mm_template.uid, "cpu", op_name="addmm")
@register_template_heuristic(bmm_template.uid, "cpu", op_name="baddbmm")
class CPUAddmmTemplateConfigHeuristic(AddMMConfigMixin, CPUMMTemplateConfigHeuristic):
    """Addmm specific mixin for CPU"""
    ...


@register_template_heuristic(mm_template.uid, "cpu", op_name="scaled_mm")
class CPUScaledMMTemplateConfigHeuristic(ScaledMMConfigMixin, CPUConfigHeuristic):
    """Scaled MM template heuristic for CPU (non-TMA)"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_template.uid, "cpu", op_name="int_mm")
class CPUInt8MMTemplateConfigHeuristic(INT8MMTemplateConfigMixin, CPUConfigHeuristic):
    """Int8 MM template heuristic for CPU"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_plus_mm_template.uid, "cpu")
class CPUMMPlusMMTemplateConfigHeuristic(MMPlusMMTemplateConfigMixin, CPUConfigHeuristic):
    """MM Plus MM template heuristic for CPU"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_template.uid, "xpu")
@register_template_heuristic(bmm_template.uid, "xpu")
class XPUMMTemplateConfigHeuristic(MMTemplateConfigMixin, XPUConfigHeuristic):
    """Standard MM template heuristic for XPU"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_template.uid, "xpu", op_name="addmm")
@register_template_heuristic(bmm_template.uid, "xpu", op_name="baddbmm")
class XPUAddmmTemplateConfigHeuristic(AddMMConfigMixin, XPUMMTemplateConfigHeuristic):
    """Addmm specific mixin for XPU"""
    ...


@register_template_heuristic(persistent_tma_mm_template.uid, "xpu")
class XPUPersistentTMATemplateConfigHeuristic(TMATemplateConfigMixin, XPUConfigHeuristic):
    """Persistent TMA template heuristic for XPU"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(persistent_tma_mm_template.uid, "xpu", op_name="addmm")
class XPUAddmmPersistentTMATemplateConfigHeuristic(AddMMConfigMixin, XPUPersistentTMATemplateConfigHeuristic):
    """Addmm specific mixin for XPU"""
    ...


@register_template_heuristic(mm_template.uid, "xpu", op_name="scaled_mm")
class XPUScaledMMTemplateConfigHeuristic(ScaledMMConfigMixin, XPUConfigHeuristic):
    """Scaled MM template heuristic for XPU (non-TMA)"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_template.uid, "xpu", op_name="int_mm")
class XPUInt8MMTemplateConfigHeuristic(INT8MMTemplateConfigMixin, XPUConfigHeuristic):
    """Int8 MM template heuristic for XPU"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_plus_mm_template.uid, "xpu")
class XPUMMPlusMMTemplateConfigHeuristic(MMPlusMMTemplateConfigMixin, XPUConfigHeuristic):
    """MM Plus MM template heuristic for XPU"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_template.uid, "mtia")
@register_template_heuristic(bmm_template.uid, "mtia")
class MTIAMMTemplateConfigHeuristic(MMTemplateConfigMixin, MTIAConfigHeuristic):
    """Standard MM template heuristic for MTIA"""
    ...


@register_template_heuristic(mm_template.uid, "mtia", op_name="addmm")
@register_template_heuristic(bmm_template.uid, "mtia", op_name="baddbmm")
class MTIAAddMMTemplateConfigHeuristic(AddMMConfigMixin, MTIAMMTemplateConfigHeuristic):
    """Addmm specific mixin for MTIA"""
    ...


@register_template_heuristic(mm_template.uid, "mtia", op_name="scaled_mm")
class MTIAScaledMMTemplateConfigHeuristic(ScaledMMConfigMixin, MTIAConfigHeuristic):
    """Scaled MM template heuristic for MTIA (non-TMA)"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_template.uid, "mtia", op_name="int_mm")
class MTIAInt8MMTemplateConfigHeuristic(INT8MMTemplateConfigMixin, MTIAConfigHeuristic):
    """Int8 MM template heuristic for MTIA"""
    def __init__(self) -> None:
        ...
    


@register_template_heuristic(mm_plus_mm_template.uid, "mtia")
class MTIAMMPlusMMTemplateConfigHeuristic(MMPlusMMTemplateConfigMixin, MTIAConfigHeuristic):
    """MM Plus MM template heuristic for MTIA"""
    def __init__(self) -> None:
        ...
    


