"""
This type stub file was generated by pyright.
"""

from contextlib import _GeneratorContextManager
from typing import TYPE_CHECKING, TypeAlias
from typing_extensions import Protocol

"""Lock acquisition utilities

This module provides safe and unsafe lock acquisition functions for both threading.Lock
and FileLock objects, with configurable timeout behaviors. It supports three timeout modes:
blocking (infinite wait), non-blocking (immediate), and blocking with timeout (finite wait).

The module offers both context manager and manual acquisition patterns:
- Safe acquisition: Uses context managers that automatically handle lock release
- Unsafe acquisition: Manual acquisition that requires explicit release by the caller
"""
if TYPE_CHECKING:
    ...
_LockContextManager: TypeAlias = _GeneratorContextManager[None, None, None]
class _LockProtocol(Protocol):
    def __call__(self, timeout: float | None = ...) -> _LockContextManager:
        ...
    


_BLOCKING: float = ...
_NON_BLOCKING: float = ...
_BLOCKING_WITH_TIMEOUT: float = ...
_DEFAULT_TIMEOUT: float = ...
