"""
This type stub file was generated by pyright.
"""

from typing_extensions import ParamSpec, TypeVar, TypedDict

"""Utility functions

This module provides helper functions for LRU caching decorators used
throughout the caching system.
"""
P = ParamSpec("P")
R = TypeVar("R")
class EncodedTensor(TypedDict):
    """TypedDict for encoded tensor metadata."""
    shape: tuple[int, ...]
    stride: tuple[int, ...]
    dtype: str
    ...


