"""
This type stub file was generated by pyright.
"""

import torch
from collections.abc import Callable
from torch.distributed.distributed_c10d import Work

def local_p2p_op(dst: torch.SymInt, tensor: torch.Tensor, op: Callable[[torch.Tensor, int], Work | None]) -> Work | list[Work | None] | None:
    """
    Runs a point-to-point (P2P) operation for all combinations of source and destination ranks.
    """
    ...

def wait_all(work: Work | list[Work | None] | None) -> None:
    """
    Waits for all work objects in the input to complete.

    A single Work object, None, or a list of Work objects (possibly containing None).
    If None, does nothing. If a single Work, waits for it to complete. If a list, waits
    for each non-None Work in the list to complete.
    """
    ...

