"""
This type stub file was generated by pyright.
"""

import numba
from warnings import catch_warnings, simplefilter, warn
from .umap_ import UMAP
from .aligned_umap import AlignedUMAP
from importlib.metadata import PackageNotFoundError, version

__version__ = ...
