"""
This type stub file was generated by pyright.
"""

import numba
from sklearn.base import BaseEstimator

INT32_MIN = ...
INT32_MAX = ...
@numba.njit(parallel=True)
def in1d(arr, test_set) -> _Array1D[numpy.bool[builtins.bool]]:
    ...

def invert_dict(d) -> dict[Any, Any]:
    ...

@numba.njit()
def procrustes_align(embedding_base, embedding_to_align, anchors):
    ...

def expand_relations(relation_dicts, window_size=...) -> _Array[tuple[int, int, int], signedinteger[_32Bit]]:
    ...

@numba.njit()
def build_neighborhood_similarities(graphs_indptr, graphs_indices, relations) -> _Array1D[floating[_32Bit]]:
    ...

def get_nth_item_or_val(iterable_or_val, n) -> None:
    ...

PARAM_NAMES = ...
def set_aligned_params(new_params, existing_params, n_models, param_names=...):
    ...

@numba.njit()
def init_from_existing_internal(previous_embedding, weights_indptr, weights_indices, weights_data, relation_dict) -> _Array[tuple[int, int], floating[_32Bit]]:
    ...

def init_from_existing(previous_embedding, graph, relations) -> _Array[tuple[int, int], floating[_32Bit]]:
    ...

class AlignedUMAP(BaseEstimator):
    def __init__(self, n_neighbors=..., n_components=..., metric=..., metric_kwds=..., n_epochs=..., learning_rate=..., init=..., alignment_regularisation=..., alignment_window_size=..., min_dist=..., spread=..., low_memory=..., set_op_mix_ratio=..., local_connectivity=..., repulsion_strength=..., negative_sample_rate=..., transform_queue_size=..., a=..., b=..., random_state=..., angular_rp_forest=..., target_n_neighbors=..., target_metric=..., target_metric_kwds=..., target_weight=..., transform_seed=..., force_approximation_algorithm=..., verbose=..., unique=...) -> None:
        ...
    
    def fit(self, X, y=..., **fit_params) -> Self:
        ...
    
    def fit_transform(self, X, y=..., **fit_params):
        ...
    
    def update(self, X, y=..., **fit_params) -> None:
        ...
    


