"""
This type stub file was generated by pyright.
"""

import numba
import numpy as np

_mock_identity = np.eye(2, dtype=np.float64)
_mock_cost = 1 - _mock_identity
_mock_ones = np.ones(2, dtype=np.float64)
@numba.njit()
def sign(a) -> Literal[-1, 1]:
    ...

@numba.njit()
def softmax(z) -> _Array1D[float64]:
    ...

@numba.njit(fastmath=True)
def euclidean(x, y) -> Incomplete:
    r"""Standard euclidean distance.

    ..math::
        D(x, y) = \sqrt{\sum_i (x_i - y_i)^2}
    """
    ...

@numba.njit(fastmath=True)
def euclidean_grad(x, y) -> tuple[Incomplete, Any]:
    r"""Standard euclidean distance and its gradient.

    ..math::
        D(x, y) = \sqrt{\sum_i (x_i - y_i)^2}
        \frac{dD(x, y)}{dx} = (x_i - y_i)/D(x,y)
    """
    ...

@numba.njit()
def standardised_euclidean(x, y, sigma=...) -> Incomplete:
    r"""Euclidean distance standardised against a vector of standard
    deviations per coordinate.

    ..math::
        D(x, y) = \sqrt{\sum_i \frac{(x_i - y_i)**2}{v_i}}
    """
    ...

@numba.njit(fastmath=True)
def standardised_euclidean_grad(x, y, sigma=...) -> tuple[Incomplete, Any]:
    r"""Euclidean distance standardised against a vector of standard
    deviations per coordinate with gradient.

    ..math::
        D(x, y) = \sqrt{\sum_i \frac{(x_i - y_i)**2}{v_i}}
    """
    ...

@numba.njit()
def manhattan(x, y) -> float | Any:
    r"""Manhattan, taxicab, or l1 distance.

    ..math::
        D(x, y) = \sum_i |x_i - y_i|
    """
    ...

@numba.njit()
def manhattan_grad(x, y) -> tuple[float | Any, _Array1D[float64]]:
    r"""Manhattan, taxicab, or l1 distance with gradient.

    ..math::
        D(x, y) = \sum_i |x_i - y_i|
    """
    ...

@numba.njit()
def chebyshev(x, y) -> float:
    r"""Chebyshev or l-infinity distance.

    ..math::
        D(x, y) = \max_i |x_i - y_i|
    """
    ...

@numba.njit()
def chebyshev_grad(x, y) -> tuple[float | Any, _Array1D[float64]]:
    r"""Chebyshev or l-infinity distance with gradient.

    ..math::
        D(x, y) = \max_i |x_i - y_i|
    """
    ...

@numba.njit()
def minkowski(x, y, p=...) -> Any:
    r"""Minkowski distance.

    ..math::
        D(x, y) = \left(\sum_i |x_i - y_i|^p\right)^{\frac{1}{p}}

    This is a general distance. For p=1 it is equivalent to
    manhattan distance, for p=2 it is Euclidean distance, and
    for p=infinity it is Chebyshev distance. In general it is better
    to use the more specialised functions for those distances.
    """
    ...

@numba.njit()
def minkowski_grad(x, y, p=...) -> tuple[Any, _Array1D[floating[_32Bit]]]:
    r"""Minkowski distance.

    ..math::
        D(x, y) = \left(\sum_i |x_i - y_i|^p\right)^{\frac{1}{p}}

    This is a general distance. For p=1 it is equivalent to
    manhattan distance, for p=2 it is Euclidean distance, and
    for p=infinity it is Chebyshev distance. In general it is better
    to use the more specialised functions for those distances.
    """
    ...

@numba.njit()
def poincare(u, v) -> Any:
    r"""Poincare distance.

    ..math::
        \delta (u, v) = 2 \frac{ \lVert  u - v \rVert ^2 }{ ( 1 - \lVert  u \rVert ^2 ) ( 1 - \lVert  v \rVert ^2 ) }
        D(x, y) = \operatorname{arcosh} (1+\delta (u,v))
    """
    ...

@numba.njit()
def hyperboloid_grad(x, y) -> tuple[Incomplete, _Array1D[float64]]:
    ...

@numba.njit()
def weighted_minkowski(x, y, w=..., p=...) -> Any:
    r"""A weighted version of Minkowski distance.

    ..math::
        D(x, y) = \left(\sum_i w_i |x_i - y_i|^p\right)^{\frac{1}{p}}

    If weights w_i are inverse standard deviations of data in each dimension
    then this represented a standardised Minkowski distance (and is
    equivalent to standardised Euclidean distance for p=1).
    """
    ...

@numba.njit()
def weighted_minkowski_grad(x, y, w=..., p=...) -> tuple[Any, _Array1D[floating[_32Bit]]]:
    r"""A weighted version of Minkowski distance with gradient.

    ..math::
        D(x, y) = \left(\sum_i w_i |x_i - y_i|^p\right)^{\frac{1}{p}}

    If weights w_i are inverse standard deviations of data in each dimension
    then this represents a standardised Minkowski distance (and is
    equivalent to standardised Euclidean distance for p=1).
    """
    ...

@numba.njit()
def mahalanobis(x, y, vinv=...) -> Incomplete:
    ...

@numba.njit()
def mahalanobis_f64(x, y, vinv=...) -> Incomplete:
    "float64 version of mahalanobis. Used for testing (need accuracy in finite differences)"
    ...

@numba.njit()
def mahalanobis_grad(x, y, vinv=...) -> tuple[Incomplete, Any]:
    ...

@numba.njit()
def hamming(x, y):
    ...

@numba.njit()
def canberra(x, y) -> float | Any:
    ...

@numba.njit()
def canberra_grad(x, y) -> tuple[float | Any, _Array1D[float64]]:
    ...

@numba.njit()
def bray_curtis(x, y) -> float | Any:
    ...

@numba.njit()
def bray_curtis_grad(x, y) -> tuple[float | Any, Any | _Array1D[float64]]:
    ...

@numba.njit()
def jaccard(x, y) -> float:
    ...

@numba.njit()
def matching(x, y):
    ...

@numba.njit()
def dice(x, y) -> float:
    ...

@numba.njit()
def kulsinski(x, y) -> float:
    ...

@numba.njit()
def rogers_tanimoto(x, y):
    ...

@numba.njit()
def russellrao(x, y) -> float:
    ...

@numba.njit()
def sokal_michener(x, y):
    ...

@numba.njit()
def sokal_sneath(x, y) -> float:
    ...

@numba.njit()
def haversine(x, y) -> Any:
    ...

@numba.njit()
def haversine_grad(x, y) -> tuple[Any, Any]:
    ...

@numba.njit()
def yule(x, y) -> float:
    ...

@numba.njit()
def cosine(x, y) -> float | Any:
    ...

@numba.njit(fastmath=True)
def cosine_grad(x, y) -> tuple[float, _Array1D[floating[_32Bit]]] | tuple[Any, _Array1D[floating[_32Bit]]]:
    ...

@numba.njit()
def correlation(x, y) -> float | Any:
    ...

@numba.njit()
def hellinger(x, y) -> float | Any:
    ...

@numba.njit()
def hellinger_grad(x, y) -> tuple[float, _Array1D[floating[_32Bit]]] | tuple[Incomplete, _Array1D[floating[_32Bit]]]:
    ...

@numba.njit()
def softmax_hellinger(x, y) -> float | Any:
    """
    Hellinger distance between softmax(x) and softmax(y).
    """
    ...

@numba.njit()
def softmax_hellinger_grad(x, y) -> tuple[float | Incomplete, _Array1D[float64]]:
    """
    Hellinger distance and grad between softmax(x) and softmax(y).
    """
    ...

@numba.njit()
def approx_log_Gamma(x) -> Literal[0]:
    ...

@numba.njit()
def log_beta(x, y) -> Any | int:
    ...

@numba.njit()
def log_single_beta(x):
    ...

@numba.njit()
def ll_dirichlet(data1, data2) -> Any:
    """The symmetric relative log likelihood of rolling data2 vs data1
    in n trials on a die that rolled data1 in sum(data1) trials.

    ..math::
        D(data1, data2) = DirichletMultinomail(data2 | data1)
    """
    ...

@numba.njit(fastmath=True)
def symmetric_kl(x, y, z=...) -> float:
    r"""
    symmetrized KL divergence between two probability distributions

    ..math::
        D(x, y) = \frac{D_{KL}\left(x \Vert y\right) + D_{KL}\left(y \Vert x\right)}{2}
    """
    ...

@numba.njit(fastmath=True)
def symmetric_kl_grad(x, y, z=...) -> tuple[float | Any, Any]:
    """
    symmetrized KL divergence and its gradient

    """
    ...

@numba.njit(fastmath=True)
def correlation_grad(x, y) -> tuple[float, _Array1D[floating[_32Bit]]] | tuple[Any, _Array1D[floating[_32Bit]]]:
    ...

@numba.njit(fastmath=True)
def sinkhorn_distance(x, y, M=..., cost=..., maxiter=...) -> float | Any:
    ...

@numba.njit(fastmath=True)
def spherical_gaussian_energy_grad(x, y) -> tuple[Any, _Array1D[floating[_32Bit]]]:
    ...

@numba.njit(fastmath=True)
def diagonal_gaussian_energy_grad(x, y) -> tuple[Any, NDArray[floating[_32Bit]]] | tuple[Any, _Array1D[floating[_32Bit]]]:
    ...

@numba.njit(fastmath=True)
def gaussian_energy_grad(x, y) -> tuple[Any, NDArray[floating[_32Bit]]] | tuple[Any, _Array1D[floating[_32Bit]]]:
    ...

@numba.njit(fastmath=True)
def spherical_gaussian_grad(x, y) -> tuple[float, NDArray[floating[_32Bit]]] | tuple[Any, _Array1D[floating[_32Bit]]]:
    ...

def get_discrete_params(data, metric) -> dict[str, float] | dict[str, Array | float | Any] | dict[str, Any] | dict[Any, Any]:
    ...

@numba.njit()
def categorical_distance(x, y) -> float:
    ...

@numba.njit()
def hierarchical_categorical_distance(x, y, cat_hierarchy=...) -> float:
    ...

@numba.njit()
def ordinal_distance(x, y, support_size=...):
    ...

@numba.njit()
def count_distance(x, y, poisson_lambda=..., normalisation=...) -> float | Any:
    ...

@numba.njit()
def levenshtein(x, y, normalisation=..., max_distance=...) -> float:
    """
    Compute the Levenshtein (edit) distance between two strings
    using dynamic programming.

    Parameters
    ----------
    x, y : str
        Input strings.
    normalisation : float, default=1.0
        Value by which the final distance is divided.
    max_distance : int, default=20
        Maximum distance threshold.

    Returns
    -------
    float
        Normalised edit distance.
    """
    ...

@numba.njit()
def levenshtein_myers_ascii(x, y, normalisation=..., max_distance=...) -> float:
    """
    Compute the Levenshtein (edit) distance between two ASCII strings
    using Myers' bit-parallel algorithm.

    Parameters
    ----------
    x, y : str
        Input strings (ASCII only).
    normalisation : float, default=1.0
        Value by which the final distance is divided.
    max_distance : int, default=20
        Maximum distance threshold.

    Returns
    -------
    float
        Normalised edit distance.
    """
    ...

named_distances = ...
named_distances_with_gradients = ...
DISCRETE_METRICS = ...
SPECIAL_METRICS = ...
@numba.njit(parallel=True)
def parallel_special_metric(X, Y=..., metric=...) -> _Array[tuple[int, int], float64]:
    ...

@numba.njit(parallel=True, nogil=True)
def chunked_parallel_special_metric(X, Y=..., metric=..., chunk_size=...) -> _Array[tuple[int, int], floating[_32Bit]]:
    ...

def pairwise_special_metric(X, Y=..., metric=..., kwds=..., ensure_all_finite=...) -> NDArray[Any] | NDArray[floating[Any]] | Any | _Array[tuple[int, int], float64]:
    ...

