"""
This type stub file was generated by pyright.
"""

import numba

@numba.njit()
def arr_unique(arr) -> ndarray[_AnyShape, dtype[Any]]:
    ...

@numba.njit()
def arr_union(ar1, ar2) -> ndarray[_AnyShape, dtype[Any]]:
    ...

@numba.njit()
def arr_intersect(ar1, ar2) -> ndarray[_AnyShape, dtype[Any]]:
    ...

@numba.njit()
def sparse_sum(ind1, data1, ind2, data2) -> tuple[Any | ndarray[_AnyShape, dtype[Any]], ndarray[_AnyShape, dtype[floating[_32Bit]]]]:
    ...

@numba.njit()
def sparse_diff(ind1, data1, ind2, data2) -> tuple[Any | ndarray[_AnyShape, dtype[Any]], ndarray[_AnyShape, dtype[floating[_32Bit]]]]:
    ...

@numba.njit()
def sparse_mul(ind1, data1, ind2, data2) -> tuple[ndarray[_AnyShape, dtype[Any]], ndarray[_AnyShape, dtype[floating[_32Bit]]]]:
    ...

@numba.njit()
def general_sset_intersection(indptr1, indices1, data1, indptr2, indices2, data2, result_row, result_col, result_val, right_complement=..., mix_weight=...) -> None:
    ...

@numba.njit()
def general_sset_union(indptr1, indices1, data1, indptr2, indices2, data2, result_row, result_col, result_val) -> None:
    ...

@numba.njit()
def sparse_euclidean(ind1, data1, ind2, data2) -> Incomplete:
    ...

@numba.njit()
def sparse_manhattan(ind1, data1, ind2, data2) -> float | Any:
    ...

@numba.njit()
def sparse_chebyshev(ind1, data1, ind2, data2) -> float:
    ...

@numba.njit()
def sparse_minkowski(ind1, data1, ind2, data2, p=...) -> Any:
    ...

@numba.njit()
def sparse_hamming(ind1, data1, ind2, data2, n_features):
    ...

@numba.njit()
def sparse_canberra(ind1, data1, ind2, data2) -> floating[_32Bit]:
    ...

@numba.njit()
def sparse_bray_curtis(ind1, data1, ind2, data2) -> float | Any:
    ...

@numba.njit()
def sparse_jaccard(ind1, data1, ind2, data2) -> float | Any:
    ...

@numba.njit()
def sparse_matching(ind1, data1, ind2, data2, n_features):
    ...

@numba.njit()
def sparse_dice(ind1, data1, ind2, data2) -> float | Any:
    ...

@numba.njit()
def sparse_kulsinski(ind1, data1, ind2, data2, n_features) -> float:
    ...

@numba.njit()
def sparse_rogers_tanimoto(ind1, data1, ind2, data2, n_features):
    ...

@numba.njit()
def sparse_russellrao(ind1, data1, ind2, data2, n_features) -> float:
    ...

@numba.njit()
def sparse_sokal_michener(ind1, data1, ind2, data2, n_features):
    ...

@numba.njit()
def sparse_sokal_sneath(ind1, data1, ind2, data2) -> float | Any:
    ...

@numba.njit()
def sparse_cosine(ind1, data1, ind2, data2) -> float | Any:
    ...

@numba.njit()
def sparse_hellinger(ind1, data1, ind2, data2) -> float | Any:
    ...

@numba.njit()
def sparse_correlation(ind1, data1, ind2, data2, n_features) -> float:
    ...

@numba.njit()
def approx_log_Gamma(x) -> Literal[0]:
    ...

@numba.njit()
def log_beta(x, y) -> Any | int:
    ...

@numba.njit()
def log_single_beta(x):
    ...

@numba.njit()
def sparse_ll_dirichlet(ind1, data1, ind2, data2) -> float | Any:
    ...

sparse_named_distances = ...
sparse_need_n_features = ...
SPARSE_SPECIAL_METRICS = ...
