"""
This type stub file was generated by pyright.
"""

import numba

@numba.njit()
def trustworthiness_vector_bulk(indices_source, indices_embedded, max_k) -> _Array1D[float64]:
    ...

def make_trustworthiness_calculator(metric) -> Callable[..., _Array1D[float64]]:
    ...

def trustworthiness_vector(source, embedding, max_k, metric=...) -> _Array1D[float64]:
    ...

