"""
This type stub file was generated by pyright.
"""

import contextlib
import torch
import torch.utils._pytree as pytree
from collections.abc import Callable, Generator, Sequence
from dataclasses import dataclass
from typing import Any, NamedTuple
from torch._C import DispatchKey
from torch._higher_order_ops.utils import register_fake
from torch._ops import HigherOrderOperator
from torch.fx.experimental.proxy_tensor import ProxyTorchDispatchMode

_leaf_function_module_retriever: Callable[[int], Any] | None = ...
def set_leaf_function_module_retriever(retriever: Callable[[int], Any]) -> None:
    ...

class LeafModuleState(NamedTuple):
    """
    In dynamo, nn.Module arguments to leaf functions are converted to this
    pytree format (index, parameters, buffers). This structure is then
    flattened to produce the actual inputs to invoke_leaf_function.

    At runtime, the original module is reconstructed from it.
    """
    nn_module_index: int
    named_parameters: dict[str, torch.nn.Parameter]
    named_buffers: dict[str, torch.Tensor]
    ...


@dataclass
class GradientInfo:
    """
    We need the gradient edge to trigger the autograd engine backward.

    We need the tensor metadata (size, stride, dtype, device) to create zeros when
    gradient is None at runtime but required by the backward graph (because the graph
    is traced with fake implementation).
    """
    edge: torch.autograd.graph.GradientEdge
    size: torch.Size
    stride: tuple[int, ...]
    dtype: torch.dtype
    device: torch.device
    ...


def unwrap_fn_spec(fn_spec: pytree.TreeSpec) -> Callable:
    ...

def check_escaped_gradients(outputs: Any, inputs: Sequence[Any], requires_grad_indices: set[int]) -> None:
    """
    Check if autograd graph depends on tensors that not passed as explicit inputs.

    Controlled by torch._dynamo.config.leaf_function_check_escaped_gradients.
    """
    ...

@contextlib.contextmanager
def reconstruct_original_args(input_spec: pytree.TreeSpec | None, flat_args: tuple[Any, ...]) -> Generator[tuple[list[Any] | tuple[Any, ...], dict[str, Any]], None, None]:
    ...

def autograd_grad_with_gradient_info(output_infos: Sequence[GradientInfo | None], input_infos: Sequence[GradientInfo | None], grad_outputs: Sequence[Any] | None = ..., retain_graph: bool | None = ..., create_graph: bool = ..., allow_unused: bool = ...) -> tuple[torch.Tensor | None, ...]:
    """
    Compute gradients using GradientInfo, it additionally handles the case
    where input and output infos are None.

    Args:
        output_infos: GradientInfo for each output (None if no grad_fn),
        input_infos: GradientInfo for each input (None if not requires_grad)
        grad_outputs: Gradients w.r.t. outputs

    Returns a tuple of gradients with None for inputs that don't require grad.
    """
    ...

class InvokeLeafFunction(HigherOrderOperator):
    def __init__(self) -> None:
        ...
    
    def __call__(self, real_fn_spec, fake_fn_spec, *flat_args) -> Any:
        """
        real_fn_spec: pytree.TreeSpec for the real function that's wrapped in dynamo
        fake_fn_spec: pytree.TreeSpec for the fake function that's wrapped in dynamo
        """
        ...
    
    def gen_schema(self, real_fn_spec, fake_fn_spec, *flat_args) -> FunctionSchema:
        ...
    


invoke_leaf_function = ...
class InvokeLeafFunctionAutogradOp(torch.autograd.Function):
    @staticmethod
    def forward(ctx, real_fn_spec, fake_fn_spec, *flat_args) -> Any:
        ...
    
    @staticmethod
    def backward(ctx, *grads) -> tuple[None, None, *tuple[Any, ...]]:
        ...
    


@invoke_leaf_function.py_autograd_impl
def invoke_leaf_function_autograd(real_fn_spec, fake_fn_spec, *flat_args) -> Any:
    ...

@invoke_leaf_function.py_functionalize_impl
def invoke_leaf_function_functionalization(ctx, *all_args) -> Any:
    ...

@invoke_leaf_function.py_impl(ProxyTorchDispatchMode)
def invoke_leaf_function_proxy_mode(proxy_mode, *all_args) -> Any:
    ...

@register_fake(invoke_leaf_function)
def invoke_leaf_function_fake(real_fn_spec, fake_fn_spec, *flat_args):
    ...

@invoke_leaf_function.py_impl(DispatchKey.CompositeExplicitAutograd)
def invoke_leaf_function_dense(real_fn_spec, fake_fn_spec, *flat_args):
    ...

