"""
This type stub file was generated by pyright.
"""

import logging
import torch
from collections.abc import Callable
from typing import Any, Literal, TypeAlias
from torch.utils._ordered_set import OrderedSet

logger: logging.Logger = ...
overlap_log = ...
BucketMode: TypeAlias = Literal["default", "custom_ops", "custom_ops_multidtype"]
def bucket_key(node: torch.fx.Node, mode: BucketMode | None = ...) -> object | None:
    ...

def pick_bucket_dtype(dtypes: list[torch.dtype]) -> torch.dtype:
    ...

def bucket_cap_mb_by_bucket_idx_default(bucket_id: int) -> float:
    """
    Determine the size of a bucket based on its ID.

    Args:
    bucket_id (int): The ID of the bucket.

    Returns:
    float: The size of the bucket.
    """
    ...

def bucket_all_gather(gm: torch.fx.GraphModule, bucket_cap_mb_by_bucket_idx: Callable[[int], float] | None = ..., mode: BucketMode = ...) -> None:
    ...

def bucket_reduce_scatter(gm: torch.fx.GraphModule, bucket_cap_mb_by_bucket_idx: Callable[[int], float] | None = ..., mode: BucketMode = ...) -> None:
    ...

def is_all_gather_into_tensor(node: torch.fx.Node) -> bool:
    ...

def is_reduce_scatter_tensor(node: torch.fx.Node) -> bool:
    ...

def is_wait_tensor(node: torch.fx.Node) -> bool:
    ...

def is_all_reduce_tensor(node: torch.fx.Node) -> bool:
    ...

def is_all_to_all_tensor(node: torch.fx.Node) -> bool:
    ...

def get_collective_type(node: torch.fx.Node) -> str:
    """Get the collective type name for a node."""
    ...

def get_full_bucket_key(node: torch.fx.Node, bucket_mode: BucketMode) -> tuple[str, Any]:
    """Get the full bucket key including collective type and bucket key."""
    ...

def is_wait_tensor_from_all_gather_into_tensor(node: torch.fx.Node) -> bool:
    ...

def is_fsdp_all_gather(node: torch.fx.Node, all_node_ancestors: dict[torch.fx.Node, OrderedSet[torch.fx.Node]]) -> bool:
    """
    Check if the node is a FSDP-related all_gather by its recursive ancestors.
    On the path from the all-gather to its originate placeholder, there should not be any compute node
    So there should be ONLY ONE placeholder in its recursive ancestors.
    """
    ...

def is_fsdp_reduce_scatter(node: torch.fx.Node) -> bool:
    """
    Check if a reduce_scatter node is FSDP-related by verifying its output flows
    directly to graph outputs through only unary ops (e.g., to_copy, wait).
    """
    ...

def collect_node_descendants(graph: torch.fx.Graph) -> dict[torch.fx.Node, OrderedSet[torch.fx.Node]]:
    """
    Collects the descendants of each node in the graph.
    Args:
        graph (torch.fx.Graph): The graph to collect descendants from.
    Returns:
        dict[torch.fx.Node, OrderedSet[torch.fx.Node]]: A dictionary mapping each node to its descendants.
    """
    ...

def greedy_bucket_collective_by_mb(gm: torch.fx.GraphModule, bucket_cap_mb_by_bucket_idx: Callable[[int], float], filter_node: Callable[[torch.fx.Node], bool], node_group_key: Callable[[torch.fx.Node], Any], filter_wait_node: Callable[[torch.fx.Node], bool] | None = ...) -> list[list[torch.fx.Node]]:
    """
    Bucketing adjacent collectives with equal node_group_key.
    We can not bucket non adjacent collectives,
    as this will effectively change the order of collectives.
    Reordering can lead to different order on different ranks.
    """
    ...

def bucket_all_gather_by_mb(gm: torch.fx.GraphModule, bucket_cap_mb_by_bucket_idx: Callable[[int], float], filter_wait_node: Callable[[torch.fx.Node], bool] | None = ..., mode: BucketMode = ...) -> list[list[torch.fx.Node]]:
    """
    Identifies all all_gather nodes and groups them into buckets,
    based on size limit `bucket_cap_mb_by_bucket_idx`.

    Args:
        gm (torch.fx.GraphModule): GraphModule where to bucket all_gathers.
        bucket_cap_mb_by_bucket_idx (Callable[[int], float]): Callable to specify cap of the bucket
            in megabytes by bucket idx.  The idea of `bucket_cap_mb_by_bucket_idx` is to allow
            to specify different sizes of the buckets at the start,
            as first all_gather is usually exposed.  Interface of bucket_cap_mb_by_bucket_idx
            is `bucket_cap_mb_by_bucket_idx_default` function that is default value for `bucket_cap_mb_by_bucket_idx`.
        filter_wait_node (Callable[[torch.fx.Node], bool] | None): If specified,
            only all_gather nodes with wait_node that satisfy `filter_wait_node` will be bucketed.

    Returns:
        list[list[torch.fx.Node]]: List of buckets, where each bucket is a list of all_gather nodes.
    """
    ...

def bucket_reduce_scatter_by_mb(gm: torch.fx.GraphModule, bucket_cap_mb_by_bucket_idx: Callable[[int], float], filter_wait_node: Callable[[torch.fx.Node], bool] | None = ..., mode: BucketMode = ...) -> list[list[torch.fx.Node]]:
    """
    Identifies all reduce_scatter nodes and groups them into buckets,
        based on size limit `bucket_cap_mb_by_bucket_idx`.

    Args:
        gm (torch.fx.GraphModule): GraphModule where to bucket reduce_scatters.
        bucket_cap_mb_by_bucket_idx (Callable[[int], float]): Callable to specify cap of the bucket
            in megabytes by bucket idx.  The idea of `bucket_cap_mb_by_bucket_idx` is to allow
            to specify different sizes of the buckets.
        filter_wait_node (Callable[[torch.fx.Node], bool] | None): If specified,
            only reduce_scatter nodes with wait_node that satisfy `filter_wait_node` will be bucketed.

    Returns:
        list[list[torch.fx.Node]]: List of buckets, where each bucket is a list of reduce_scatter nodes.
    """
    ...

def bucket_all_reduce_by_mb(gm: torch.fx.GraphModule, bucket_cap_mb_by_bucket_idx: Callable[[int], float], filter_wait_node: Callable[[torch.fx.Node], bool] | None = ...) -> list[list[torch.fx.Node]]:
    ...

def bucket_all_reduce(gm: torch.fx.GraphModule, bucket_cap_mb_by_bucket_idx: Callable[[int], float] | None = ..., mode: str | None = ...) -> None:
    ...

def reduce_scatter_merge_fn_to_trace_custom_ops(rs_ins: list[torch.Tensor], group_size: int, group_name: str, reduce_op: str, reduce_dtype: torch.dtype, device: torch.device) -> list[torch.Tensor]:
    ...

def reduce_scatter_merge_fn_to_trace(rs_ins: list[torch.Tensor], group_size: int, group_name: str, reduce_op: str, reduce_dtype: torch.dtype, device: torch.device) -> list[torch.Tensor]:
    ...

def all_reduce_merge_fn_to_trace(ar_ins: list[torch.Tensor], group_name: str, reduce_op: str, reduce_dtype: torch.dtype, device: torch.device) -> list[torch.Tensor]:
    ...

_ALL_DTYPES = ...
def all_gather_merge_fn_to_trace_custom_ops(_ag_ins: list[torch.Tensor], group_size: int, group_name: str, dtype: torch.dtype, out_dtypes: list[torch.dtype], rank: int) -> list[torch.Tensor]:
    ...

def all_gather_merge_fn_to_trace(ag_ins: list[torch.Tensor], group_size: int, group_name: str, dtype: torch.dtype, out_dtypes: list[torch.dtype], rank: int) -> list[torch.Tensor]:
    ...

def all_gather_merge_fn_to_trace_functional(ag_ins: list[torch.Tensor], group_size: int, group_name: str, dtype: torch.dtype, out_dtypes: list[torch.dtype], rank: int, use_fsdp_ag_copy_in: bool = ...) -> list[torch.Tensor]:
    ...

def has_mergeable_all_gather_convert_dtype(n: torch.fx.Node) -> bool:
    ...

def process_collective_bucket(g: torch.fx.Graph, bucket_nodes: list[torch.fx.Node], fn_to_trace: Callable[..., list[torch.Tensor]], trace_args_fn: Callable[[list[torch.fx.Node]], tuple[Any, ...]], insert_before: torch.fx.Node | None = ..., wait_insertion_point: torch.fx.Node | None = ...) -> tuple[list[torch.fx.Node], dict[torch.fx.Node, torch.fx.Node]]:
    """
    Process a single bucket of collective operation nodes with flexible insertion control.

    Args:
        g: The graph to modify
        bucket_nodes: Nodes in the current bucket to process
        fn_to_trace: Function to trace and insert
        trace_args_fn: Function to create trace arguments from inputs
        insert_before: Where to insert the traced function (default: after last bucket node)
        wait_insertion_point: If provided, move all nodes from wait() onwards to before this node

    Returns:
        new_nodes: List of all newly inserted nodes
        replacements: Dictionary mapping old wait nodes to new output nodes
    """
    ...

def merge_reduce_scatter_bucket(g: torch.fx.Graph, rs_nodes: list[torch.fx.Node], mode: BucketMode = ..., insert_before: torch.fx.Node | None = ..., wait_insertion_point: torch.fx.Node | None = ...) -> tuple[list[torch.fx.Node], dict[torch.fx.Node, torch.fx.Node]]:
    ...

def merge_all_reduce_bucket(g: torch.fx.Graph, ar_nodes: list[torch.fx.Node], mode: str | None = ..., insert_before: torch.fx.Node | None = ..., wait_insertion_point: torch.fx.Node | None = ...) -> tuple[list[torch.fx.Node], dict[torch.fx.Node, torch.fx.Node]]:
    ...

def merge_all_gather_bucket(g: torch.fx.Graph, ag_nodes: list[torch.fx.Node], mode: BucketMode = ..., insert_before: torch.fx.Node | None = ..., wait_insertion_point: torch.fx.Node | None = ...) -> tuple[list[torch.fx.Node], dict[torch.fx.Node, torch.fx.Node]]:
    ...

def merge_reduce_scatter(gm: torch.fx.GraphModule, rs_buckets: list[list[torch.fx.Node]], mode: BucketMode = ...) -> None:
    """
    Merges specified buckets of reduce_scatter to joint reduce_scatter.
    """
    ...

def merge_all_gather(gm: torch.fx.GraphModule, ag_buckets: list[list[torch.fx.Node]], mode: BucketMode = ...) -> None:
    """
    Merges specified buckets of all_gather to joint all_gather.
    """
    ...

