"""
This type stub file was generated by pyright.
"""

import torch.fx as fx
from dataclasses import dataclass
from torch.utils._ordered_set import OrderedSet

"""Detect fusion regions for overlap scheduling."""
@dataclass
class FusionRegion:
    """Represents a connected set of fusible operations that will fuse together."""
    subgraph_node: fx.Node
    subgraph_module: fx.GraphModule
    total_bytes: int = ...
    cost_ms: float = ...
    def __post_init__(self) -> None:
        """Compute cost based on subgraph's placeholder inputs and output node."""
        ...
    


def is_view_node(n: fx.Node) -> bool:
    """Check if a node is a view operation (zero cost, no memory allocation)."""
    ...

def is_fusible_node(n: fx.Node) -> bool:
    """Check if a node is fusible based on whether it has an inductor lowering.

    A node is fusible if:
    - It has a lowering in torch._inductor.lowering.lowerings
    - It does NOT have a flop counter (expensive compute ops like mm/conv)
    - It is NOT a registered fallback (ops that fall back to eager)
    - It is NOT a collective or wait op
    - For aten.cat, it must have <= max_pointwise_cat_inputs inputs
    """
    ...

def build_fusion_regions(gm: fx.GraphModule) -> dict[fx.Node, OrderedSet[fx.Node]]:
    """Build fusion regions from contiguous spans of fusible nodes.

    1. Identify contiguous spans of fusible nodes (separated by non-fusible nodes)
    2. Find connected components within each span
    3. Return regions that have 2+ non-view nodes

    This ensures fusion regions are strictly local - no reordering across
    non-fusible node boundaries.

    Returns a dict mapping each node to its fusion group (OrderedSet of nodes).
    """
    ...

def collapse_fusion_regions(gm: fx.GraphModule, region_of: dict[fx.Node, OrderedSet[fx.Node]]) -> dict[fx.Node, FusionRegion]:
    """
    Collapse fusion regions into call_module nodes using fuse_by_partitions.
    Returns new_region_of mapping module nodes to FusionRegions.
    """
    ...

def expand_fusion_regions(gm: fx.GraphModule, region_of: dict[fx.Node, FusionRegion]) -> dict[fx.Node, fx.Node | None]:
    """
    Expand call_module nodes back to their original nodes using _inline_module.

    Returns a mapping from erased module nodes to their replacement (last inlined node).
    This is used with transfer_erased_node_deps to update dependencies.
    """
    ...

