"""
This type stub file was generated by pyright.
"""

import torch.fx as fx
from torch._inductor.pattern_matcher import Arg, CallFunction, Match, register_graph_pattern

"""
Partitioned Scatter Optimization for Reduced Atomic Contention.

This pass transforms high-contention index_put operations by distributing
writes across multiple partitions, reducing atomic contention.
"""
log = ...
aten = ...
prims = ...
partitioned_scatter_patterns = ...
def partitioned_scatter_optimization_pass(graph: fx.Graph) -> fx.Graph:
    """
    Apply partitioned scatter optimization to high-contention index_put operations.

    Reduces atomic contention by distributing writes across multiple buffers.
    Controlled by: config.partitioned_scatter_enabled
    """
    ...

def validate_match(match: Match) -> bool:
    """Check if pattern match should be optimized for scatter."""
    ...

@register_graph_pattern(CallFunction(aten.index_put.default, Arg(), Arg(), Arg(), True), pass_dict=partitioned_scatter_patterns, extra_check=validate_match)
@register_graph_pattern(CallFunction(aten.index_put_.default, Arg(), Arg(), Arg(), True), pass_dict=partitioned_scatter_patterns, extra_check=validate_match)
def create_replacement(match: Match, input_tensor, indices, values) -> None:
    """Replace high-contention index_put with partitioned scatter."""
    ...

__all__ = ["partitioned_scatter_optimization_pass"]
