"""
This type stub file was generated by pyright.
"""

import torch

_GreenContext = ...
SUPPORTED = ...
if hasattr(torch._C, "_CUDAGreenContext"):
    _GreenContext = ...
    SUPPORTED = ...
class GreenContext(_GreenContext):
    r"""Wrapper around a CUDA green context.

    .. warning::
       This API is in beta and may change in future releases.
    """
    @staticmethod
    def create(num_sms: int, device_id: int = ...) -> _GreenContext:
        r"""Create a CUDA green context.

        Arguments:
            num_sms (int): The number of SMs to use in the green context.
            device_id (int, optional): The device index of green context.
        """
        ...
    
    def set_context(self) -> None:
        r"""Make the green context the current context."""
        ...
    
    def pop_context(self) -> None:
        r"""Assuming the green context is the current context, pop it from the
        context stack and restore the previous context.
        """
        ...
    
    def Stream(self) -> torch.Stream:
        r"""Return the CUDA Stream used by the green context."""
        ...
    


