"""
This type stub file was generated by pyright.
"""

import torch
import torch.ao.nn.intrinsic as nni
import torch.ao.nn.qat as nnqat
from typing import TYPE_CHECKING
from torch.ao.nn.intrinsic.modules.fused import _FusedModule
from torch.ao.quantization.qconfig import QConfigAny

if TYPE_CHECKING:
    ...
__all__ = ["LinearReLU"]
class LinearReLU(nnqat.Linear, _FusedModule):
    r"""
    A LinearReLU module fused from Linear and ReLU modules, attached with
    FakeQuantize modules for weight, used in
    quantization aware training.

    We adopt the same interface as :class:`torch.nn.Linear`.

    Similar to `torch.ao.nn.intrinsic.LinearReLU`, with FakeQuantize modules initialized to
    default.

    Attributes:
        weight: fake quant module for weight

    Examples::

        >>> # xdoctest: +SKIP
        >>> m = nn.qat.LinearReLU(20, 30)
        >>> input = torch.randn(128, 20)
        >>> output = m(input)
        >>> print(output.size())
        torch.Size([128, 30])
    """
    _FLOAT_MODULE = nni.LinearReLU
    def __init__(self, in_features: int, out_features: int, bias: bool = ..., qconfig: QConfigAny = ...) -> None:
        ...
    
    def forward(self, input: torch.Tensor) -> torch.Tensor:
        ...
    
    @classmethod
    def from_float(cls, mod: torch.nn.Module, use_precomputed_fake_quant: bool = ...) -> LinearReLU:
        ...
    
    def to_float(self) -> nni.LinearReLU:
        ...
    


