"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Optional
from torch._library.utils import RegistrationHandle

class EffectType(Enum):
    ORDERED = ...


skip_classes = ...
class EffectHolder:
    """A holder where one can register an effect impl to."""
    def __init__(self, qualname: str) -> None:
        ...
    
    @property
    def effect(self) -> Optional[EffectType]:
        ...
    
    @effect.setter
    def effect(self, _):
        ...
    
    def register(self, effect: Optional[EffectType]) -> RegistrationHandle:
        """Register an effect

        Returns a RegistrationHandle that one can use to de-register this
        effect.
        """
        ...
    


