"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional, Union
from ..utils import cache_on_self

log = ...
class MultiKernelState:
    """
    Maintain state of multi-kernel compilation so we don't define duplicated
    multi-kernel for the same set of sub-kernels.

    V.graph.wrapper_code has a reference to MultiKernelState instance.
    """
    def __init__(self) -> None:
        ...
    
    def define_kernel(self, kernels: list[Any], kernel_shape_keys: Optional[list[Union[None, tuple[tuple[int, ...], ...]]]] = ...) -> str:
        """
        Previously we name the multi kernel as "multi_kernel_{kernel_names[0]}".
        This has some minor issue.

        E.g. for persistent reduction https://gist.github.com/shunting314/39e7c00ff8bb2055942ed5a3255d61ca ,
        there are 2 flavors of non-persistent reduction:
          https://gist.github.com/shunting314/056d43d35907e87efb883970b35c17d4
        and
          https://gist.github.com/shunting314/02ee753b65c513c54e695626afe682bd

        The only different is cache eviction policy.

        We should name the multi-kernel differently in these 2 cases.

        kernels:
            A list of kernels
        kernel_shape_keys:
            Specified for size-hint multi-kernels.
            Each list element is a shape key, corresponding to the concrete input & output size hints each kernel was tuned for.
        """
        ...
    


class MultiKernel:
    """
    This class maintains the compile time state for multi kernels.

    Assume we do codegen for a MultiKernel encapsulating kernel1 and kernel2.
    The generated definition for the multi-kernel will looks like:
    ```
    multi_kernel_kernel1 = MultiKernelCall(
        [kernel1, kernel2], multi_kernel_definition_code
    )
    ```

    Here is a concrete example: https://gist.github.com/shunting314/d9f3fb6bc6cee3dbae005825ca196d39
    """
    def __init__(self, kernels) -> None:
        ...
    
    @staticmethod
    def merge_workspaces_inplace(kernels) -> list[Any] | None:
        ...
    
    def call_kernel(self, kernel_name) -> None:
        """
        Collect the union of arguments from all subkernels as the arguments
        for the multi-kernel.
        """
        ...
    
    def codegen_nan_check(self) -> None:
        ...
    
    @property
    def removed_buffers(self) -> OrderedSet[Any]:
        ...
    
    @property
    def inplaced_to_remove(self) -> OrderedSet[Any]:
        ...
    
    @property
    @cache_on_self
    def inplace_update_buffers(self):
        """
        Make sure all kernels have the same inplace update mappings.
        """
        ...
    
    def warn_mix_layout(self, kernel_name: str) -> None:
        ...
    


class MultiKernelCall:
    """
    This class is called at run time to actually run the kernel
    """
    def __init__(self, multi_kernel_name, kernels, arg_index) -> None:
        ...
    
    def cache_file_path(self) -> Path:
        ...
    
    def load_cache(self) -> None:
        ...
    
    def store_cache(self) -> None:
        ...
    
    @property
    def kernels(self) -> Any:
        """
        Read results from future.

        This should be called after parallel compilation is done.
        In case you call this before compilation is done,
        it may slow down the parallel compilation.
        """
        ...
    
    def benchmark_sub_kernels(self, *args, **kwargs) -> list[float]:
        """
        Benchmark all the sub kernels and return the execution time
        (in milliseconds) for each of time.

        Unit test may mock this method to force a specific kernel to
        be picked.
        """
        ...
    
    @staticmethod
    def record_choice(multi_kernel_name: str, picked_kernel_name: str) -> None:
        """
        Record the multi-kernel choice for cpp-wrapper after autotuning

        We should do nothing if this function is not called during codegen.
        """
        ...
    
    @staticmethod
    def lookup_choice(multi_kernel_name: str) -> str:
        ...
    
    def run(self, *args, **kwargs) -> None:
        ...
    


class SizeHintMultiKernel(MultiKernel):
    """
    Version of multi-kernel that generates kernels based on specified size hints.
    Currently only performs 1-d search over hints; doesn't perform combinatorial n-d search
    if n > 1 dynamic dimensions are specified.

    e.g. matmul([s0, s1], [s1, s2]) with size-hints [64, 256] only generates 2 kernels,
    based on tuning shapes ([64, 64], [64, 64]) and ([256, 256], [256, 256])
    """
    def __init__(self, kernels) -> None:
        ...
    


class SizeHintMultiKernelCall(MultiKernelCall):
    """
    Runtime class for size-hint multi-kernels.
    Instead of having a plain list of kernels to benchmark over, keys them by input & output shapes,
    and optionally perform shape-based selection. The pre-generated kernel is chosen based on the shape keys,
    with the heuristic being log2 l1 distance between the pre-generated / runtime input & output shapes.
    """
    def __init__(self, multi_kernel_name, kernels, arg_index) -> None:
        ...
    
    def run(self, *args, **kwargs) -> None:
        ...
    


