"""
This type stub file was generated by pyright.
"""

from torch._ops import OpOverload
from torch.distributed.device_mesh import DeviceMesh
from torch.distributed.tensor._op_schema import OpSchema, OpStrategy
from torch.distributed.tensor._sharding_prop import ShardingPropagator
from torch.utils._python_dispatch import TorchDispatchMode

"""
Decomposition-based sharding propagation for DTensor.

When an operator doesn't have a registered sharding strategy, we derive one by
tracing through its decomposition. The decomposed ops (which do have strategies)
determine how placements propagate through the original op.
"""
class PlacementTrackingMode(TorchDispatchMode):
    """
    TorchDispatchMode that tracks DTensor placements through op execution.

    Used during decomposition tracing: intercepts each op, propagates sharding
    via the ShardingPropagator, and records output placements on the result tensors.
    """
    def __init__(self, sharding_prop: ShardingPropagator, mesh: DeviceMesh) -> None:
        ...
    
    def __torch_dispatch__(self, func, types, args=..., kwargs=...):
        ...
    


class DecompShardingStrategy:
    """
    Generates sharding strategies for ops by tracing through their decompositions.

    For each candidate input placement combination, runs the decomposition on meta
    tensors under PlacementTrackingMode to determine the output placement. These
    single-dimension strategies are then expanded to the full mesh.
    """
    @staticmethod
    def has_decomp(op: OpOverload) -> bool:
        ...
    
    @staticmethod
    def ensure_schema_info(op: OpOverload, sharding_prop: ShardingPropagator) -> None:
        """
        Register schema_info for decomposition op on first invocation.
        Needed for correct shard prop cache key.
        """
        ...
    
    @staticmethod
    def propagate_strategy(op_schema: OpSchema, sharding_prop: ShardingPropagator) -> OpStrategy | None:
        ...
    


