"""
This type stub file was generated by pyright.
"""

import sympy
from dataclasses import dataclass
from typing import Optional
from torch._inductor.utils import _IntLike

def static_eq(a: _IntLike, b: _IntLike) -> bool:
    ...

@dataclass
class Term:
    coefficient: _IntLike
    range: Optional[_IntLike]
    original_expr: sympy.Expr
    reconstruction_multiplier: _IntLike
    ...


def generate_inverse_formula(expr: sympy.Expr, var: sympy.Symbol) -> Optional[sympy.Expr]:
    """
     Analyze an expression to see if it matches a specific invertible pattern that we
     know how to reverse.

     We're looking for expressions that are sums of terms where each term extracts a
     distinct bounded range from the input variable, like:

         y = c₀*a₀ + c₁*a₁ + c₂*a₂ + ... + cₙ*aₙ

     where each aᵢ must be one of these specific patterns:
     - ModularIndexing(var, divisor, modulo)
     - FloorDiv(ModularIndexing(var, 1, modulo), divisor)
     - FloorDiv(var, divisor)
     - var (the variable itself)

     The key pattern we need is:
     - Coefficients are strictly decreasing: c₀ > c₁ > c₂ > ... > cₙ
     - Each coefficient matches the product of ranges of later terms (mixed-radix property)
     - Each term extracts a bounded range, creating non-overlapping "slots"

     If we find this pattern, we can generate the reconstruction transformation that
     decomposes the variable and rebuilds it using the correct multipliers.

     EXAMPLE:
     Input: 100*((p//100)) + 10*((p%100)//10) + (p%10)

     Returns the reconstruction expression:
         remainder₀ = p
         component₀ = remainder₀ // 100          # hundreds digit
         remainder₁ = remainder₀ % 100
         component₁ = remainder₁ // 10           # tens digit
         remainder₂ = remainder₁ % 10
         component₂ = remainder₂                 # ones digit
         result = component₀*100 + component₁*10 + component₂*1

    This decomposes p into its components and rebuilds it using the original
     multipliers, which should equal the input expression.

     Args:
         expr: Expression to analyze (sum of terms with ModularIndexing, FloorDiv, etc.)
         var: The variable being decomposed

     Returns:
         None if not invertible, or the reconstruction expression

     References:
         Mixed-radix systems: https://en.wikipedia.org/wiki/Mixed_radix
    """
    ...

def parse_terms(expr: sympy.Expr, var: sympy.Symbol) -> Optional[list[Term]]:
    """Parse expression into terms."""
    ...

def parse_single_term(term: sympy.Expr, var: sympy.Symbol) -> Optional[Term]:
    """Parse a single term and extract coefficient, range, and reconstruction multiplier."""
    ...

def analyze_expression_properties(expr: sympy.Expr, var: sympy.Symbol) -> tuple[Optional[_IntLike], Optional[_IntLike]]:
    """Analyze an expression to determine its range and reconstruction multiplier."""
    ...

def check_invertibility(terms: list[Term]) -> bool:
    """Check if the terms represent an invertible transformation."""
    ...

def generate_reconstruction_expr(terms: list[Term], var: sympy.Symbol) -> sympy.Expr:
    ...

