"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from typing import Any, Literal, Optional, TYPE_CHECKING
from torch._dynamo.aot_compile_types import BundledAOTAutogradSerializableCallable
from torch._inductor.utils import InputType
from collections.abc import Callable, Sequence
from torch.compiler._cache import CacheInfo
from torch.fx import GraphModule

if TYPE_CHECKING:
    ...
log = ...
class CompiledArtifact(ABC):
    """
    CompiledArtifact class represents the inductor cache artifacts that
    can be invoked in order to avoid repeated compilation.

    CompiledArtifact can be obtained by calling standalone_compile(gm, example_inputs)
    to create a fresh CompiledArtifact from a GraphModule and example inputs.

    Later this CompiledArtifact can be saved to disk, either as a binary or unpacked
    into the provided folder via the CompiledArtifact.save function.

    CompiledArtifact.load provides a way to create a CompiledArtifact from the
    binary or unpacked data.

    Finally, the CompiledArtifact can be invoked via the __call__ method
    to execute the cached artifact.
    """
    def __init__(self, compiled_fn: Callable[..., Any], artifacts: Optional[tuple[bytes, CacheInfo]]) -> None:
        ...
    
    @abstractmethod
    def __call__(self, *args: Any) -> Any:
        ...
    
    @abstractmethod
    def save(self, *, path: str, format: Literal["binary", "unpacked"] = ...) -> None:
        ...
    
    @staticmethod
    def load(*, path: str, format: Literal["binary", "unpacked"] = ...) -> CompiledArtifact:
        ...
    


class CacheCompiledArtifact(CompiledArtifact):
    """
    CompiledArtifact that depends on torch.compiler.save_cache_artifacts
    """
    CACHE_HEADER = ...
    def __init__(self, compiled_fn: Callable[..., Any], artifacts: Optional[tuple[bytes, CacheInfo]]) -> None:
        ...
    
    def __call__(self, *args: Any) -> Any:
        ...
    
    def is_saveable(self) -> bool:
        ...
    
    def save(self, *, path: str, format: Literal["binary", "unpacked"] = ...) -> None:
        ...
    
    @staticmethod
    def load(*, path: str, format: Literal["binary", "unpacked"] = ...) -> CompiledArtifact:
        ...
    


class AOTCompiledArtifact(CompiledArtifact):
    """
    Similar to CompiledArtifact, but the object is a single, bundled precompiled function.
    This object is always a serializable callable function.

    This object is essentially a wrapper for BundledAOTAutogradSerializableCallable, which
    is used by torch._dynamo.aot_compile for AOT Precompilation.
    """
    AOT_HEADER = ...
    def __init__(self, compiled_fn: Callable[..., Any]) -> None:
        ...
    
    @staticmethod
    def from_bundled_callable(bundled_fn: BundledAOTAutogradSerializableCallable) -> AOTCompiledArtifact:
        ...
    
    def __call__(self, *args: Any) -> Any:
        ...
    
    def save(self, *, path: str, format: Literal["binary", "unpacked"] = ...) -> None:
        ...
    
    def serialize(self) -> bytes:
        ...
    
    @staticmethod
    def deserialize(result_bytes: bytes) -> AOTCompiledArtifact:
        ...
    
    @staticmethod
    def load(*, path: str, format: Literal["binary", "unpacked"] = ...) -> CompiledArtifact:
        ...
    


def standalone_compile(gm: GraphModule, example_inputs: Sequence[InputType], *, dynamic_shapes: Any, options: Any, aot: bool = ...) -> CompiledArtifact:
    """
    Implementation of torch.inductor.standalone_compile
    """
    ...

