"""
This type stub file was generated by pyright.
"""

from .int_tuple import IntTuple, as_tuple, crd2crd, crd2idx, elem_scale, flatten, has_none, idx2crd, inner_product, is_int, is_tuple, match_structure, product, shape_div, signum, slice_, suffix_product, tuple_max
from .layout import Layout, LayoutBase, coalesce, complement, composition, cosize, filter, is_layout, left_inverse, logical_divide, logical_product, make_layout, right_inverse, size, slice_and_offset, tiled_divide, tiled_product, zipped_divide, zipped_product
from .typing import Integer

