"""
This type stub file was generated by pyright.
"""

from typing import TypeAlias
from typing_extensions import Self, TypeIs
from .int_tuple import IntTuple

"""
Definition of CuTe Layouts and functions to manipulate them which works with the order
of lexicographic instead of co-lexicographic as implemented in the original layout.py
"""
CoordinateType: TypeAlias = (int | IntTuple | tuple[object, ...] | None)
class LayoutBase:
    ...


def is_layout(x: object) -> TypeIs[Layout]:
    ...

class Layout(LayoutBase):
    def __init__(self, _shape: IntTuple, _stride: IntTuple | None = ...) -> None:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __call__(self, *args: CoordinateType) -> Self | int:
        """
        Map a logical coordinate to a linear index (Coord has no Underscore slice operators)
        OR
        Slice the layout and return the sublayout (Coord has an Underscore slice op)

        Follow the same behavior of `Layout::operator(Coord const&)` in cute C++
        """
        ...
    
    def __getitem__(self, i: int) -> Self:
        ...
    
    def size(self) -> int:
        ...
    
    def cosize(self) -> int:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    


LayoutOrIntTuple: TypeAlias = Layout | IntTuple
LayoutProfile: TypeAlias = tuple[object, ...] | Layout | None
LayoutInput: TypeAlias = Layout | IntTuple | tuple[object, ...] | None
def make_layout(*layouts: Layout | tuple[Layout, ...]) -> Layout:
    ...

def size(layout: LayoutOrIntTuple) -> int:
    ...

def cosize(layout: Layout) -> int:
    ...

def coalesce(layout: Layout, profile: LayoutProfile = ...) -> Layout:
    ...

def filter(layout: Layout, profile: LayoutProfile = ...) -> Layout:
    ...

def composition(layoutA: Layout, layoutB: LayoutInput) -> Layout:
    ...

def complement(layout: LayoutOrIntTuple, max_idx: int = ...) -> Layout:
    ...

def right_inverse(layout: LayoutOrIntTuple | None) -> Layout | None:
    ...

def left_inverse(layout: LayoutOrIntTuple | None) -> Layout | None:
    ...

def logical_divide(layoutA: Layout, layoutB: LayoutInput) -> Layout:
    ...

def logical_product(layoutA: Layout, layoutB: LayoutInput) -> Layout:
    ...

def hier_unzip(splitter: object, layoutA: Layout, layoutB: LayoutInput) -> Layout:
    ...

def zipped_divide(layoutA: Layout, layoutB: LayoutInput) -> Layout:
    ...

def tiled_divide(layoutA: Layout, layoutB: LayoutInput) -> Layout:
    ...

def zipped_product(layoutA: Layout, layoutB: LayoutInput) -> Layout:
    ...

def tiled_product(layoutA: Layout, layoutB: LayoutInput) -> Layout:
    ...

def slice_and_offset(crd: tuple[object, ...], layout: Layout) -> tuple[Layout, int]:
    ...

