"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from torch.utils._config_typing import *

"""
Global configuration flags for torch.distributed
"""
__all__ = ["compile_on_one_rank", "use_torchcomms"]
compile_on_one_rank: bool = ...
use_torchcomms: bool = ...
if TYPE_CHECKING:
    ...
