"""
This type stub file was generated by pyright.
"""

import torch
import torch.fx
from typing import TYPE_CHECKING
from collections.abc import Callable
from torch.onnx._internal.exporter import _registration

if TYPE_CHECKING:
    ...
def dispatch(node: torch.fx.Node, registry: _registration.ONNXRegistry) -> tuple[Callable | None, str]:
    """Dispatch a node to an ONNX function based on the node's target and the ONNX registry.

    Args:
        node: The node to dispatch.
        registry: The ONNX registry to use for dispatching.

    Returns:
        A tuple containing the matched ONNX function and a string describing the reason for failure or success.
    """
    ...

