"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from torch.onnx._internal._lazy_import import onnx_ir as ir
from collections.abc import Sequence

if TYPE_CHECKING:
    ...
_ONNX_DOMAIN = ...
logger = ...
def rename_inputs(model: ir.Model, new_names: Sequence[str]) -> None:
    ...

def rename_outputs(model: ir.Model, new_names: Sequence[str]) -> None:
    ...

def rename_axis(model: ir.Model, rename_mapping: dict[str | ir.SymbolicDim, str]) -> None:
    """Rename dynamic axes in a model according to the specified dynamic_axes names."""
    ...

def add_opset_imports(model: ir.Model) -> None:
    """Collect all opsets used and add opset imports to the model and functions."""
    ...

