"""
This type stub file was generated by pyright.
"""

from typing import Any
from torch.onnx._internal._lazy_import import onnx_ir as ir

"""Helpers for constructing ONNX operator signatures from Python functions."""
logger = ...
_PY_TYPE_TO_ATTR_TYPE = ...
_LIST_TYPE_TO_ATTR_TYPE = ...
_ALL_VALUE_TYPES = ...
TypeAnnotationValue = Any
def op_signature_from_function(func, domain: str, name: str | None = ..., overload: str = ..., *, since_version: int = ...) -> ir.schemas.OpSignature:
    """Produce an OpSignature from a function using type annotation."""
    ...

