"""
This type stub file was generated by pyright.
"""

import pstats
from dataclasses import dataclass
from typing import TYPE_CHECKING

"""
Dynamo Profiler - tracks where Dynamo spends time during compilation.

This module provides profiling functionality for Dynamo tracing, showing per-function
cumtime (inclusive) and tottime (exclusive) in a cProfile-compatible format.
The output can be visualized with tools like snakeviz.

Usage:
    # Enable via config (prints pstats output):
    torch._dynamo.config.dynamo_profiler = True

    # Or save to file for snakeviz:
    torch._dynamo.config.dynamo_profiler = "/tmp/dynamo.prof"
    # Then: snakeviz /tmp/dynamo.prof
"""
if TYPE_CHECKING:
    ...
@dataclass
class FunctionTraceTiming:
    """
    Timing data for a single inlined function trace.

    Follows cProfile conventions:
    - cumtime: total time in function including all subcalls (inclusive)
    - tottime: time in function excluding subcalls (exclusive)
    - caller info: who called this function (for building call graph)
    """
    func_name: str
    filename: str
    firstlineno: int
    cumtime_ns: int
    tottime_ns: int
    bytecode_count: int
    inline_depth: int
    caller_func_name: str | None = ...
    caller_filename: str | None = ...
    caller_firstlineno: int | None = ...
    is_primitive_call: bool = ...
    call_stack: tuple[tuple[str, str, int], ...] = ...
    @property
    def trace_time_ns(self) -> int:
        ...
    
    @property
    def trace_time_ms(self) -> float:
        ...
    
    @property
    def cumtime_ms(self) -> float:
        ...
    
    @property
    def tottime_ms(self) -> float:
        ...
    
    @property
    def caller_key(self) -> tuple[str, int, str] | None:
        """Return caller as a pstats-compatible key tuple."""
        ...
    
    @property
    def func_key(self) -> tuple[str, int, str]:
        """Return this function as a pstats-compatible key tuple."""
        ...
    
    def __repr__(self) -> str:
        ...
    


@dataclass
class ProfilerStackEntry:
    """Stack entry for tracking function timing in the Dynamo profiler."""
    func_name: str
    filename: str
    firstlineno: int
    start_time_ns: int
    child_time_ns: int
    is_primitive_call: bool = ...


class DynamoProfilerState:
    """State for Dynamo profiler tracking function trace timings."""
    def __init__(self) -> None:
        ...
    
    def record_timing(self, timing: FunctionTraceTiming) -> None:
        """Record timing data for a traced function."""
        ...
    
    def get_timings(self) -> list[FunctionTraceTiming]:
        """Get all recorded timings."""
        ...
    
    def push(self, func_name: str, filename: str, firstlineno: int, start_time_ns: int) -> None:
        """Push a new entry onto the timing stack."""
        ...
    
    def pop(self) -> ProfilerStackEntry | None:
        """Pop the top entry from the timing stack."""
        ...
    
    def add_child_time(self, child_cumtime_ns: int) -> None:
        """Add the child's cumulative time to the parent's child_time accumulator."""
        ...
    
    def get_current_caller(self) -> tuple[str, str, int] | None:
        """Get the current caller (top of stack) as (func_name, filename, firstlineno)."""
        ...
    
    def get_call_stack(self) -> tuple[tuple[str, str, int], ...]:
        """Get the full current call stack as tuple of (func_name, filename, firstlineno)."""
        ...
    
    def generate_pstats(self, output_file: str | None = ..., print_raw: bool = ...) -> pstats.Stats:
        """Generate pstats.Stats object from recorded timings.

        Args:
            output_file: Optional file path to save the stats.
            print_raw: If True, print raw aggregate timings before returning.
        """
        ...
    
    def generate_svg(self, profile_file: str, svg_file: str | None = ...) -> str | None:
        """Generate an SVG call graph from a profile file using gprof2dot and graphviz.

        Args:
            profile_file: Path to the pstats profile file.
            svg_file: Optional path for the output SVG. If not provided, uses
                profile_file with .svg extension.

        Returns:
            Path to the generated SVG file, or None if generation failed.
        """
        ...
    
    def dump_stats(self, output_file: str | None = ..., generate_svg: bool = ...) -> None:
        """Print profiler stats to stdout and optionally save to file.

        Args:
            output_file: Optional path to save the pstats profile.
            generate_svg: If True and output_file is provided, also generate an SVG
                call graph using gprof2dot and graphviz.
        """
        ...
    


