"""
This type stub file was generated by pyright.
"""

import torch
import torch.fx
from collections.abc import Callable, Sequence
from typing import Any, Optional, TYPE_CHECKING, TypeVar
from torch._dynamo.convert_frame import CaptureOutput
from torch._dynamo.decorators import disable as dynamo_disable
from torch.export.dynamic_shapes import Constraint
from torch.fx import Node
from torch.fx.experimental.symbolic_shapes import ConstraintViolationError
from torch.fx.node import Argument, Target

if TYPE_CHECKING:
    ...
T = TypeVar("T")
log = ...
def post_process_error_msg(constraint_violation_error: ConstraintViolationError, func: Callable[..., Any], args: Any, kwargs: Any) -> ConstraintViolationError:
    """
    Because we trace a different callable, the sources are all messed up.
    Manually patch them so the error message looks correct.
    """
    ...

EXPORT_ROOT_REPLACEMENTS = ...
def clean_export_root_string(text: str) -> str:
    """Generic utility to clean export_root patterns from strings."""
    ...

def clean_nn_module_stack_and_source_fn(graph_module: torch.fx.GraphModule, is_inline_builtin: bool = ...) -> torch.fx.GraphModule:
    """
    Clean up nn_module_stack metadata by removing export_root references.

    Removes the _export_root module references from nn_module_stack metadata
    in graph nodes, which are artifacts from the export process. Fixes two patterns:

    1. Keys: Removes "__export_root_" and "__modules['_export_root']_" prefixes
       - Normal case: "L__self____export_root_child" -> "L__self__child"
       - inline_builtin case: Uses numeric ID strings like "140468831433840"

    2. Values: Removes "._export_root" and "._modules['_export_root']" from child names
       e.g., "L['self']._export_root.child" -> "L['self'].child"
       e.g., "L['self']._modules['_export_root'].child" -> "L['self'].child"

    Also removes the root export entry "L__self____export_root" entirely.

    Args:
        graph_module: The GraphModule to clean up
        is_inline_builtin: If True, keys are numeric ID strings and self references
                          (L['self']) are filtered out

    Returns:
        The cleaned GraphModule (modified in-place)
    """
    ...

def clean_export_root(graph_module: torch.fx.GraphModule) -> None:
    """Remove export_root artifacts from FX graph in-place"""
    ...

class ModuleToTrace(torch.nn.Module):
    def __init__(self, foo: Any, in_spec: Any) -> None:
        ...
    
    def forward(self, *flat_args: Any) -> ExportTracerOutput:
        ...
    


ExportTracerOutput = ...
class DynamoGraphTransformer(torch.fx.Transformer):
    """Graph transformer for dynamo export that flattens inputs/outputs without complex matching."""
    def __init__(self, module: torch.fx.GraphModule, flat_inputs: list[Any], flat_args_dynamic_dims: list[set[int]], graph_input_order: dict[int, int], graph_output_map: dict[int, tuple[str, Any]], fake_mode: Optional[Any] = ...) -> None:
        ...
    
    def placeholder(self, target: Target, args: tuple[Argument, ...], kwargs: dict[str, Any]) -> Any:
        """Replace old placeholders with new flattened ones."""
        ...
    
    def output(self, target: Target, args: Sequence[Any], kwargs: dict[str, Any]) -> Any:
        """Transform output according to graph_output_map."""
        ...
    
    def run_node(self, n: Node) -> Any:
        """Run node transformation and preserve metadata."""
        ...
    
    def transform(self) -> torch.fx.GraphModule:
        """Perform the graph transformation and copy module metadata."""
        ...
    


def normalize_graph_module(gm: torch.fx.GraphModule) -> None:
    ...

class InputProcessor:
    def __init__(self, root: object, num_args: int, kwarg_names: list[str]) -> None:
        ...
    
    def __call__(self, inputs: tuple[object, ...]) -> tuple[tuple[object, ...], dict[str, object]]:
        ...
    


class Yield(Exception):
    ...


class DynamoBytecodeFlatten:
    def __init__(self, input_processor: InputProcessor, out: CaptureOutput, f_globals: dict[str, object]) -> None:
        ...
    
    @dynamo_disable(reason="do not trace internal dynamo graph capture")
    def __call__(self, *inputs: object) -> object:
        ...
    


class DynamoBytecodeUnflatten:
    def __init__(self, input_processor: InputProcessor, out: CaptureOutput, f_globals: dict[str, object]) -> None:
        ...
    
    @dynamo_disable(reason="do not trace internal dynamo graph capture")
    def __call__(self, flat_outs: Sequence[object], inputs: tuple[object, ...]) -> object:
        ...
    


def create_fx_graph_from_captured_output(out: CaptureOutput, mod: Any, args: tuple[Any, ...], kwargs: dict[str, Any]) -> torch.fx.GraphModule:
    ...

class _DynamoBytecodeCodeGen(torch.fx.graph.CodeGen):
    def __init__(self, orig_arg_names: list[str], dynamo_bytecode_flatten: Callable, dynamo_bytecode_unflatten: Callable) -> None:
        ...
    
    def process_inputs(self, *inputs: Any) -> Any:
        ...
    
    def process_outputs(self, outputs: Any) -> Any:
        ...
    
    def gen_fn_def(self, free_vars: list[str], maybe_return_annotation: str, *, expanded_def: bool = ...) -> str:
        ...
    
    def gen_var_bindings(self, fn_args: list[str], free_vars: list[str], expanded_def: bool) -> str:
        ...
    
    def generate_output(self, output_args: torch.fx.node.Argument, *, descs: object | None = ...) -> str:
        ...
    


def dynamo_graph_capture_for_export(mod: Callable[..., Any], constraints: Optional[list[Constraint]] = ..., restore_state_dict: bool = ...) -> Callable[..., Any]:
    ...

