"""
This type stub file was generated by pyright.
"""

import sys
import torch
from typing import Any
from typing_extensions import deprecated

__all__ = ["autocast", "custom_fwd", "custom_bwd"]
@deprecated("`torch.cuda.amp.autocast(args...)` is deprecated. " "Please use `torch.amp.autocast('cuda', args...)` instead.", category=FutureWarning)
class autocast(torch.amp.autocast_mode.autocast):
    r"""See :class:`torch.autocast`.

    ``torch.cuda.amp.autocast(args...)`` is deprecated. Please use ``torch.amp.autocast("cuda", args...)`` instead.
    """
    if sys.version_info < (3, 13):
        ...
    def __init__(self, enabled: bool = ..., dtype: torch.dtype = ..., cache_enabled: bool = ...) -> None:
        ...
    
    def __enter__(self) -> Self:
        ...
    
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> Literal[False] | None:
        ...
    
    def __call__(self, func) -> _Wrapped[..., Any, ..., Any]:
        ...
    


@deprecated("`torch.cuda.amp.custom_fwd(args...)` is deprecated. " "Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.", category=FutureWarning)
def custom_fwd(fwd=..., *, cast_inputs=...) -> partial[Any] | _Wrapped[..., Any, ..., Any]:
    """
    ``torch.cuda.amp.custom_fwd(args...)`` is deprecated. Please use
    ``torch.amp.custom_fwd(args..., device_type='cuda')`` instead.
    """
    ...

@deprecated("`torch.cuda.amp.custom_bwd(args...)` is deprecated. " "Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.", category=FutureWarning)
def custom_bwd(bwd) -> partial[Any] | _Wrapped[..., Any, ..., Any]:
    """
    ``torch.cuda.amp.custom_bwd(args...)`` is deprecated. Please use
    ``torch.amp.custom_bwd(args..., device_type='cuda')`` instead.
    """
    ...

