"""
This type stub file was generated by pyright.
"""

"""CPU-specific implementations for flex attention"""
def check_cpu_supported() -> bool:
    ...

def lower_cpu(query, key, value, subgraph, block_mask, scale, kernel_options, score_mod_other_buffers, mask_mod_other_buffers) -> tuple[TensorBox | Any | tuple[ShapeAsConstantBuffer, ExternKernelCaller] | ShapeAsConstantBuffer | tuple[TensorBox, CUTLASSTemplateCaller | ChoiceCaller] | tuple[Any, Any]]:
    """CPP based template for flex attention for x86 CPUs"""
    ...

