"""
This type stub file was generated by pyright.
"""

import functools
import sympy
from contextlib import contextmanager
from typing import Any, Optional
from torch.fx import GraphModule
from ...ir import ShapeAsConstantBuffer, Subgraph, TensorBox
from .common import SubgraphResults

"""Call into flash-attention 4 for flexattention"""
aten = ...
prims = ...
@functools.lru_cache(maxsize=1)
def ensure_flash_available() -> bool:
    """Check if flash-attn is importable; cache the result for reuse.

    Call ensure_flash_available.cache_clear() after installing flash-attn
    in the same interpreter to retry the import.
    """
    ...

flash_attention_cutedsl_template = ...
flash_attention_backward_cutedsl_template = ...
class HierarchicalIndex(sympy.Function):
    """
    Inert wrapper to carry an N-D index tuple through Inductor's SymPy-based IR.

    Inductor generally represents a tensor index as a single `sympy.Expr` (often a
    flattened linear offset in memory). CuteDSL, however, wants structured coordinates so it
    can emit `tensor[i, j, ...]` and handle strides internally. We therefore wrap
    the per-dimension indices in a `sympy.Function` node: this keeps the value a
    `sympy.Expr` for existing substitution/CSE machinery, while letting CuteDSL
    codegen pattern-match and unpack the coordinates via `index.args`.

    `eval()` returns None to keep the node inert (no simplification/flattening).

    These nodes are intended to be short-lived wrappers and are only interpreted by
    CuteDSL codegen (see `ModificationWrapperCuteDSL.load` in
    `torch/_inductor/codegen/cutedsl/cutedsl_kernel.py`).
    """
    @classmethod
    def eval(cls, *args) -> None:
        ...
    


@contextmanager
def patch_fixed_layout_indexer_for_cutedsl() -> Generator[None, Any, None]:
    """
    Temporarily swap FixedLayout.make_indexer so CuteDSL sees hierarchical indexing.

    Note [CuteDSL indexer patch]:
    Flex flash attention only supports a limited set of IR ops (pointwise, reads, no stores),
    so temporarily changing the indexing behavior is safe for the kernels we emit today.
    TODO(dynamic shapes): Reconfirm once flex flash attention supports dynamic shapes.
    """
    ...

def wrap_choice_render_with_cutedsl_indexer(choice: Any) -> None:
    """
    Wrap a template choice's kernel render to apply CuteDSL indexer patching.

    See Note [CuteDSL indexer patch]:
    CuteDSL handles tensor strides internally, so template rendering must use
    hierarchical indexing.
    """
    ...

def input_buffers_require_grads(graph_module, num_score_mod_placeholders: int) -> bool:
    """Check if any of the input buffers (beyond the score mod placeholders) require gradients."""
    ...

def is_trivial_score_graph(graph_module: GraphModule) -> bool:
    """Backwards currently doesn't support score_mods, match against identity"""
    ...

def is_trivial_mask_graph(graph_module: GraphModule) -> bool:
    """Mask graph is trivial when it only gates via the default full op."""
    ...

def create_flex_flash_attention_kernel(query: TensorBox, key: TensorBox, value: TensorBox, block_mask: tuple[Any, ...], scale: float, kernel_options: dict[str, Any], subgraph_buffer: SubgraphResults, mask_graph_buffer: SubgraphResults, score_mod_other_buffers: list[TensorBox], mask_mod_other_buffers: list[TensorBox], kv_num_blocks: TensorBox | None, kv_indices: TensorBox | None, full_kv_num_blocks: TensorBox | None, full_kv_indices: TensorBox | None, sparse_q_block_size: int, sparse_kv_block_size: int, mask_graph: Subgraph, subgraph: Subgraph | None = ...) -> tuple[TensorBox, TensorBox]:
    """Create a flex flash attention kernel using CuteDSL template."""
    ...

def create_flex_flash_attention_backward_kernel(query: TensorBox, key: TensorBox, value: TensorBox, out: TensorBox, logsumexp: TensorBox, grad_out: TensorBox, scale: float, kernel_options: dict[str, Any], sparse_q_block_size: int, sparse_kv_block_size: int, fw_subgraph_buffer: Optional[SubgraphResults] = ..., joint_subgraph_buffer: Optional[Any] = ..., score_mod_other_buffers: Optional[list[TensorBox]] = ..., mask_graph_buffer: Optional[SubgraphResults] = ..., q_num_blocks: Optional[TensorBox] = ..., q_indices: Optional[TensorBox] = ..., full_q_num_blocks: Optional[TensorBox] = ..., full_q_indices: Optional[TensorBox] = ...) -> tuple[TensorBox | ShapeAsConstantBuffer, TensorBox, TensorBox, tuple]:
    """Create a CuteDSL flash attention backward kernel for the default mod path."""
    ...

