"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Sequence
from typing import Any, Optional
from torch.fx import Graph, Node
from .common import ChunkingMeta

aten = ...
log = ...
def set_chunking_meta(node: Node, meta: Optional[ChunkingMeta] = ..., **kwargs: Any) -> bool:
    """
    kwargs can override fields in the passed in `meta`
    """
    ...

def update_chunking_meta(node: Node, **kwargs: Any) -> bool:
    """
    Unlike set_chunking_mete, this function keeps the existing chunking
    metadata if it's not overridden.
    """
    ...

def set_chunking_meta_if_none(nodes: Sequence[Node], meta: ChunkingMeta, filter_for_nop: Optional[Callable[[Node], bool]] = ...) -> bool:
    """
    If filter_fop_nop returns true for a node, we set the chunking
    meta to nop instead.
    """
    ...

def copy_chunking_meta(dst_node: Node, src_node: Node | ChunkingMeta) -> bool:
    ...

def get_chunking_meta(node: Node) -> Optional[ChunkingMeta]:
    ...

def has_nop_chunking_meta(node: Node) -> bool:
    ...

def get_chunking_metas(nodes: Sequence[Node], skip_none: bool = ...) -> Sequence[ChunkingMeta | None]:
    ...

eligible_amplifier_node = ...
def find_amplifier_node(graph: Graph) -> Optional[Node]:
    r"""
    Find the 'amplifier' node which is a node that generates large
    output with small/medium input.

    If there are multiple amplifier nodes, return the one with the largest
    amplification ratio.
    """
    ...

def reorder_nodes(graph: Graph) -> Graph:
    """
    Create a new graph to be like:
    1. all nodes run before `chunking_subgraph_nodes`
    2. all nodes in `chunking_subgraph_nodes`
    3. all nodes run after `chunking_subgraph_nodes`

    Return a new graph so it's easier to fallback.
    """
    ...

