"""
This type stub file was generated by pyright.
"""

"""Internal feature flags for torch.onnx.

NOTE: These flags are experimental only. Any flag here can be removed at any
time without notice.
"""
logger = ...
ENABLE_DRAFT_EXPORT: bool = ...
PREFER_DEFERRED_RUNTIME_ASSERTS_OVER_GUARDS: bool = ...
