"""
This type stub file was generated by pyright.
"""

class OpaqueBaseMeta(type):
    def __instancecheck__(cls, instance) -> bool:
        ...
    


class OpaqueBase(metaclass=OpaqueBaseMeta):
    ...


