"""
This type stub file was generated by pyright.
"""

import contextlib
import builtins
import torch
from abc import ABC, abstractmethod
from contextlib import AbstractContextManager
from typing import Any, Optional, TYPE_CHECKING, Union
from typing_extensions import Self
from collections.abc import Callable, Generator, Sequence
from types import TracebackType
from torch._functorch.pyfunctorch import FunctionalizeInterpreter
from torch._ops import OpOverload
from torch.utils._python_dispatch import TorchDispatchMode

if TYPE_CHECKING:
    ...
not_implemented_log = ...
class FunctionalTensor(torch.Tensor):
    """
    Functional tensors represent tensors that will remove mutations
    from a program. If you perform a mutable operation on a functional tensor,
    it will re-dispatch to the functional variant of that operation.

    Historically, functionalization is implemented in C++ in the dispatcher.
    This class is a lightweight python shim around the C++ functionalization logic.

    FunctionalTensor is required to be used with a corresponding
    FunctionalTensormode active, because it relies
    on using the mode for dispatch (which can properly handle factory functions).
    """
    elem: torch.Tensor
    _mode_key = ...
    _extra_dispatch_keys = ...
    metadata_fns = ...
    _inference_mode_base: Optional[FunctionalTensor] = ...
    def __new__(cls, elem: torch.Tensor, mode: FunctionalTensorMode) -> Self:
        ...
    
    def __torch_dispatch__(self, func: OpOverload, types: Sequence[type], args: tuple[Any, ...] = ..., kwargs: dict[str, Any] | None = ...) -> Any:
        ...
    
    def __repr__(self, *, tensor_contents: object | None = ...) -> str:
        ...
    
    @staticmethod
    def to_functional(x: torch.Tensor) -> FunctionalTensor:
        ...
    
    def from_functional(self) -> torch.Tensor:
        ...
    
    def is_base_tensor(self) -> bool:
        ...
    
    def replace_(self, output: torch.Tensor) -> None:
        ...
    
    def commit_update(self) -> None:
        ...
    
    def sync(self) -> None:
        ...
    
    def mark_mutation_hidden_from_autograd(self) -> None:
        ...
    
    def tolist(self) -> Any:
        ...
    
    def to(self, *args: Any, **kwargs: Any) -> torch.Tensor:
        ...
    
    def cuda(self, device: torch.device | int | str | None = ..., *args: Any, **kwargs: Any) -> torch.Tensor:
        ...
    
    char = ...
    cpu = ...
    bfloat16 = ...
    byte = ...
    double = ...
    float = ...
    bool = ...
    half = ...
    int = ...
    long = ...
    def to_dense(self, dtype: torch.dtype | None = ..., *, masked_grad: builtins.bool | None = ...) -> torch.Tensor:
        ...
    
    @property
    def layout(self) -> torch.layout:
        ...
    
    def __bool__(self) -> builtins.bool:
        ...
    


class FunctionalTensorMode(TorchDispatchMode):
    def __init__(self, pre_dispatch: bool = ..., export: bool = ..., _allow_token_discovery: bool = ...) -> None:
        ...
    
    def __enter__(self) -> Self:
        ...
    
    def __exit__(self, exc_type: Optional[type[BaseException]], exc_val: Optional[BaseException], exc_tb: Optional[TracebackType]) -> None:
        ...
    
    def __torch_dispatch__(self, func: OpOverload, types: Sequence[type], args: tuple[Any, ...] = ..., kwargs: dict[str, Any] | None = ...) -> Any:
        ...
    
    @classmethod
    def is_infra_mode(cls) -> bool:
        ...
    


@contextlib.contextmanager
def disable_functional_mode() -> Generator[None, None, None]:
    ...

def dispatch_functionalize(func: Callable[..., Any], mode: FunctionalTensorMode = ...) -> Callable[..., Any]:
    ...

class BaseFunctionalizeAPI(ABC):
    @abstractmethod
    def wrap_tensors(self, args: tuple[Any, ...]) -> tuple[Any, ...]:
        ...
    
    @abstractmethod
    def unwrap_tensors(self, args: torch.Tensor | tuple[torch.Tensor, ...]) -> Any:
        ...
    
    @abstractmethod
    def functionalize(self, inner_f: Callable[..., Any]) -> Callable[..., Any]:
        ...
    
    @abstractmethod
    def redispatch_to_next(self) -> AbstractContextManager[None]:
        ...
    
    @abstractmethod
    def replace(self, input_tensor: torch.Tensor, output_tensor: torch.Tensor) -> None:
        ...
    
    @abstractmethod
    def commit_update(self, tensor: torch.Tensor) -> None:
        ...
    
    @abstractmethod
    def sync(self, tensor: torch.Tensor) -> None:
        ...
    
    @abstractmethod
    def mark_mutation_hidden_from_autograd(self, tensor: torch.Tensor) -> None:
        ...
    


class PythonFunctionalizeAPI(BaseFunctionalizeAPI):
    def __init__(self, mode: Optional[FunctionalTensorMode] = ..., pre_dispatch: bool = ...) -> None:
        ...
    
    def wrap_tensors(self, args: tuple[Any]) -> tuple[Any]:
        ...
    
    def unwrap_tensors(self, args: Union[torch.Tensor, tuple[torch.Tensor, ...], list[torch.Tensor]]) -> Any:
        ...
    
    def functionalize(self, inner_f: Callable) -> Callable:
        ...
    
    def redispatch_to_next(self) -> AbstractContextManager[None]:
        ...
    
    def replace(self, input_tensor: torch.Tensor, output_tensor: torch.Tensor) -> None:
        ...
    
    def commit_update(self, tensor: torch.Tensor) -> None:
        ...
    
    def sync(self, tensor: torch.Tensor) -> None:
        ...
    
    def mark_mutation_hidden_from_autograd(self, tensor: torch.Tensor) -> None:
        ...
    


class CppFunctionalizeAPI(BaseFunctionalizeAPI):
    def wrap_tensors(self, args: tuple[Any, ...]) -> tuple[Any, ...]:
        ...
    
    def unwrap_tensors(self, args: Union[torch.Tensor, tuple[torch.Tensor, ...]]) -> Union[torch.Tensor, tuple[torch.Tensor, ...]]:
        ...
    
    def functionalize(self, inner_f: Callable) -> Callable:
        ...
    
    def redispatch_to_next(self) -> AbstractContextManager[None]:
        ...
    
    def replace(self, input_tensor: torch.Tensor, output_tensor: torch.Tensor) -> None:
        ...
    
    def commit_update(self, tensor: torch.Tensor) -> None:
        ...
    
    def sync(self, tensor: torch.Tensor) -> None:
        ...
    
    def mark_mutation_hidden_from_autograd(self, tensor: torch.Tensor) -> None:
        ...
    


class FunctorchFunctionalizeAPI(BaseFunctionalizeAPI):
    def __init__(self, interpreter: FunctionalizeInterpreter) -> None:
        ...
    
    def wrap_tensors(self, args: tuple[Any]) -> tuple[Any]:
        ...
    
    def unwrap_tensors(self, args: Union[torch.Tensor, tuple[torch.Tensor, ...]]) -> Union[torch.Tensor, tuple[torch.Tensor, ...]]:
        ...
    
    def functionalize(self, inner_f: Callable) -> Callable:
        ...
    
    def redispatch_to_next(self) -> AbstractContextManager[None]:
        ...
    
    def replace(self, input_tensor: torch.Tensor, output_tensor: torch.Tensor) -> None:
        ...
    
    def commit_update(self, tensor: torch.Tensor) -> None:
        ...
    
    def sync(self, tensor: torch.Tensor) -> None:
        ...
    
    def mark_mutation_hidden_from_autograd(self, tensor: torch.Tensor) -> None:
        ...
    


def mb_unwrap_functional_tensor(tensor: torch.Tensor) -> torch.Tensor:
    ...

