"""
This type stub file was generated by pyright.
"""

import math
import os
import socket
import uuid
import torch
import torch.distributed._functional_collectives as funcol
import torch.distributed.distributed_c10d as c10d
from collections.abc import Callable, Generator, Sequence
from contextlib import contextmanager
from datetime import timedelta
from enum import Enum
from functools import partial
from typing import Any, Literal, TYPE_CHECKING, Union, overload
from typing_extensions import deprecated
from torch._C._autograd import DeviceType
from torch._C._distributed_c10d import ProcessGroup, Work as _Work, _SymmetricMemory
from torch.types import _device, _dtype, _int

_group_name_to_store: dict[str, c10d.Store] = ...
@deprecated("`enable_symm_mem_for_group` is deprecated. There is no need to call this function anymore.", category=FutureWarning)
def enable_symm_mem_for_group(group_name: c10d.GroupName) -> None:
    """
    Enables symmetric memory for a process group.

    Args:
        group_name (str): the name of the process group.
    """
    ...

_is_test_mode: bool = ...
_mocked_group_names: set[str] | None = ...
def is_symm_mem_enabled_for_group(group_name: c10d.GroupName) -> bool:
    """
    Check if symmetric memory is enabled for a process group.

    Args:
        group_name (str): the name of the process group.
    """
    ...

_group_name_to_workspace_tensor: dict[str, torch.Tensor | None] = ...
def get_symm_mem_workspace(group_name: c10d.GroupName, min_size: int) -> _SymmetricMemory:
    """
    Get the symmetric memory workspace associated with the process group. If
    ``min_size`` is greater than the workspace associated with ``group_name``,
    the workspace will be re-allocated and re-rendezvous'd.

    Args:
        group_name (str): the name of the process group.
        min_size (int): the size requirement for the workspace in bytes.

    Returns:
        _SymmetricMemory: the symmetric memory workspace associated with the
        group.
    """
    ...

_backend_streams: dict[int, torch.cuda.Stream] = ...
lib = ...
class _ScaleMode(Enum):
    UNSCALED = ...
    TENSOR_WISE = ...
    ROW_WISE_SHARDED = ...
    ROW_WISE_REPLICATED = ...


def make_contiguous_for_perm(t: torch.Tensor, perm: list[int]) -> torch.Tensor:
    """
    Restride `t` such that `t.permute(perm)` is contiguous.
    """
    ...

def restride_A_shard_for_fused_all_gather_matmul(t: torch.Tensor, gather_dim: int) -> torch.Tensor:
    """
    Restride the `A_shard` arg of `fused_all_gather_matmul` for optimal perf.
    See the doc for `fused_all_gather_matmul` for detail.
    """
    ...

def restride_A_for_fused_matmul_reduce_scatter(t: torch.Tensor, scatter_dim: int) -> torch.Tensor:
    """
    Restride the `A_shard` arg of `fused_matmul_reduce_scatter` for optimal
    perf. See the doc for `fused_matmul_reduce_scatter` for detail.
    """
    ...

class Work(_Work):
    def __init__(self) -> None:
        ...
    
    def wait(self, timeout: timedelta = ...) -> bool:
        ...
    


if TYPE_CHECKING:
    ...
_use_implicit_mempool: bool | None = ...
@overload
def empty(*size: _int, dtype: _dtype | None = ..., device: _device | None = ...) -> torch.Tensor:
    ...

@overload
def empty(size: Sequence[_int], *, dtype: _dtype | None = ..., device: _device | None = ...) -> torch.Tensor:
    ...

def empty(*size: Any, dtype: _dtype | None = ..., device: _device | None = ...) -> torch.Tensor:
    r"""
    Similar to :func:`torch.empty()`. The returned tensor can be used by
    :func:`torch._distributed._symmetric_memory.rendezvous()` to establish a
    symmetric memory tensor among participating processes.

    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.

    Keyword args:
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
        device (:class:`torch.device`, optional): the desired device of returned tensor.
            Default: if ``None``, uses the current device for the default tensor type
            (see :func:`torch.set_default_device`). :attr:`device` will be the CPU
            for CPU tensor types and the current CUDA device for CUDA tensor types.
    """
    ...

def rendezvous(tensor: torch.Tensor, group: c10d.GroupName | ProcessGroup) -> _SymmetricMemory:
    r"""
    rendezvous(tensor, group) -> _SymmetricMemory

    Establish a symmetric memory tensor among participating processes. This is
    a collective operation.

    Args:
        tensor (:class:`torch.Tensor`): the local tensor used to establish the symmetric memory tensor.
            It must be allocated via :func:`torch._distributed._symmetric_memory.empty()`. The shape,
            dtype, and device type must be identical across all participating processes.
        group (Union[str, :class:`torch.distributed.ProcessGroup`]): The group identifying the
            participating processes. This can be either a group name or a process group object.
    """
    ...

def is_nvshmem_available() -> bool:
    r"""
    is_nvshmem_available() -> bool

    Check if NVSHMEM is available in current build and on current system.
    """
    ...

def set_backend(name: Literal["NVSHMEM", "CUDA", "NCCL"]) -> None:
    r"""
    Set the backend for symmetric memory allocation. This is a global setting
    and affects all subsequent calls to
    :func:`torch._distributed._symmetric_memory.empty()`.  Note that the backend
    cannot be changed once a symmetric memory tensor has been allocated.

    Args:
        backend (str): the backend for symmetric memory allocation. Currently,
            only `"NVSHMEM"`, `"CUDA"`, `"NCCL"` are supported.
    """
    ...

def get_backend(device: _device) -> str | None:
    r"""
    Get the backend for symmetric memory allocation for a given device. If not
    found, return None.

    Args:
        device (`torch.device` or str): the device for which to get the backend.
    """
    ...

def get_mempool_allocator(device: _device) -> Any:
    r"""
    Get the MemPool allocator for symmetric memory for a given device.

    Args:
        device (`torch.device` or str): the device for which to get the MemPool
            allocator.
    """
    ...

def set_signal_pad_size(size: int) -> None:
    r"""
    Set the signal pad size for future symmetric memory allocations.

    Signal pads are P2P-accessible memory regions used for synchronization in
    symmetric memory. This function allows users to configure
    the signal pad size to be proportional to their workload requirements.

    .. warning::
        This must be called before any symmetric memory allocations are made.
        The size cannot be changed after allocations have been performed.

    Args:
        size (int): the signal pad size in bytes. The size should be
            proportional to the number of blocks launched and the world size.

    Example::

        >>> # doctest: +SKIP
        >>> # Set a larger signal pad size before any allocations
        >>> torch.distributed._symmetric_memory.set_signal_pad_size(1024 * 1024)  # 1MB
    """
    ...

def get_signal_pad_size() -> int:
    r"""
    Get the current signal pad size for symmetric memory allocations.

    Returns the user-configured size if set via :func:`set_signal_pad_size`,
    otherwise returns the default size.

    Returns:
        int: the signal pad size in bytes.

    Example::

        >>> # doctest: +SKIP
        >>> size = torch.distributed._symmetric_memory.get_signal_pad_size()
        >>> print(f"Signal pad size: {size} bytes")
    """
    ...

_symm_mem_pools: dict[_device, torch.cuda.MemPool] = ...
def get_mem_pool(device: _device) -> torch.cuda.MemPool:
    """
    Get the symmetric memory pool for a given device. If not found, create a new
    pool.

    The tensor allocations with this pool must be symmetric across ranks.  The
    allocated tensors can be used with symmetric operations, for example,
    operations defined under `torch.ops.symm_mem`.

    Args:
        device (`torch.device` or str): the device for which to get the symmetric memory pool.

    Returns:
        `torch.cuda.MemPool`: the symmetric memory pool for the given device.

    Example::

        >>> # doctest: +SKIP
        >>> pool = torch.distributed._symmetric_memory.get_mem_pool("cuda:0")
        >>> with torch.cuda.use_mem_pool(pool):
        >>>     tensor = torch.randn(1000, device="cuda:0")
        >>> tensor = torch.ops.symm_mem.one_shot_all_reduce(tensor, "sum", group_name)

    """
    ...

def put_signal(src: torch.Tensor, hdl: _SymmetricMemory, peer: int) -> None:
    r"""
    put_signal(src, hdl, peer) -> None

    Put data to a peer's symmetric memory and signal the peer.

    Args:
        src (torch.Tensor): the source tensor to read data from.
        hdl (SymmetricMemory): the symmetric memory to put data to.
        peer (int): the peer to put data to.
    """
    ...

def wait_signal(hdl: _SymmetricMemory, peer: int) -> None:
    r"""
    wait_signal(hdl, peer) -> None

    Wait for a signal from a peer.

    Args:
        hdl (SymmetricMemory): the symmetric memory handle on which to wait for a signal.
        peer (int): the peer to wait for a signal from.
    """
    ...

__all__ = ["empty", "rendezvous", "is_nvshmem_available", "set_backend", "get_backend", "set_signal_pad_size", "get_signal_pad_size", "get_mem_pool"]
