"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterable
from typing import Any, Optional
from ...autotune_process import CuteDSLBenchmarkRequest
from ...ir import Buffer, ChoiceCaller, IRNode, Layout, TensorBox
from ..common import KernelTemplate

log = ...
class CuteDSLTemplate(KernelTemplate):
    """Template for generating CuteDSL (CUTLASS Python DSL) kernels."""
    kernel_type: type[Any] = ...
    index_counter = ...
    all_templates: dict[str, CuteDSLTemplate] = ...
    def __init__(self, name: str, source: str, subgraph_fn: Optional[Any] = ..., mask_fn: Optional[Any] = ...) -> None:
        ...
    
    def maybe_append_choice(self, choices: list[Any], **kwargs: Any) -> Optional[NotImplementedError]:
        """
        Maybe generates a new ChoiceCaller and appends it into existing choices.
        Returns None if success, otherwise returns the error.
        """
        ...
    
    def generate(self, **kwargs: Any) -> ChoiceCaller:
        """Generate the CuteDSL kernel caller."""
        ...
    


class CuteDSLTemplateCaller(ChoiceCaller):
    """Caller for CuteDSL templates that integrates with the autotuning system."""
    def __init__(self, name: str, input_nodes: list[Buffer], layout: Layout, make_kernel_render: Any, bmreq: CuteDSLBenchmarkRequest, template: CuteDSLTemplate, mutated_inputs: Optional[Iterable[IRNode]] = ...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def benchmark(self, *args, out) -> float:
        """Benchmark the kernel execution."""
        ...
    
    def output_node(self) -> TensorBox:
        """Create the output node for this template choice."""
        ...
    
    def call_name(self) -> str:
        """Return the kernel call name."""
        ...
    
    def to_callable(self) -> Any:
        """Return callable that can execute this kernel."""
        ...
    
    def hash_key(self) -> str:
        """Return unique hash key for this choice."""
        ...
    
    def info_dict(self) -> dict[str, Any]:
        """Return information about this kernel."""
        ...
    


