"""
This type stub file was generated by pyright.
"""

import torch
from dataclasses import dataclass
from typing import Any, TypeGuard
from torch import Tensor
from torch._subclasses.functional_tensor import FunctionalTensor
from torch.fx.experimental.symbolic_shapes import SymIntEqByExpr

"""
This file contains utilities related to functionalization in AOTAutograd:
1. converting to/from functional tensors
2. detecting Tensor mutations - both metadata and Tensor value
3. regenerating/replaying views from their base
4. checking if a graph is functional i.e. whether it contains any mutation ops
"""
aot_joint_log = ...
def to_fun(t: object) -> Any:
    ...

def sync_functional_tensor(t: torch.Tensor) -> None:
    ...

def from_fun(t: object) -> object:
    ...

def is_fun(t: object) -> TypeGuard[FunctionalTensor | Tensor]:
    ...

def has_data_mutation(t: object) -> bool:
    ...

def are_all_mutations_hidden_from_autograd(t: object) -> bool:
    ...

def are_all_mutations_under_no_grad_or_inference_mode(t: torch.Tensor) -> bool:
    ...

def was_inductor_storage_resized(t: object) -> bool:
    ...

def has_metadata_mutation(f_arg: object, arg: object, *, check_only_storage_mutation: bool) -> bool:
    ...

def gen_alias_from_base(aliased_base_tensor: Tensor, target_meta_tensor: Tensor, target_requires_grad: bool, target_view_meta_sequence: ViewMetaSequence | None = ..., *, replay_views: bool) -> Tensor:
    ...

def has_same_metadata(t1: Tensor, t2: Tensor) -> bool:
    ...

@dataclass(frozen=True)
class MetadataKey:
    """
    This should be equal whenever has_same_metadata would return True
    """
    size: tuple[SymIntEqByExpr, ...]
    layout: torch.layout
    is_sparse: bool
    stride: tuple[SymIntEqByExpr, ...] | None
    storage_offset: SymIntEqByExpr | None
    is_conj: bool
    is_neg: bool
    @staticmethod
    def make(t: Tensor) -> MetadataKey:
        ...
    


class ViewMetaSequence:
    def __init__(self, tensor: FunctionalTensor) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def __eq__(self, other: object) -> bool:
        ...
    


def was_tensor_updated(arg: torch.Tensor, new_arg: torch.Tensor) -> bool:
    ...

def was_tensor_metadata_updated(arg: Any, new_arg: Any) -> bool:
    ...

def assert_functional_graph(fx_g: torch.fx.Graph) -> int:
    ...

def propagate_input_mutation_stacktraces(fx_g: torch.fx.Graph) -> None:
    ...

