"""
This type stub file was generated by pyright.
"""

import torch
from collections.abc import Callable, Generator
from contextlib import AbstractContextManager, contextmanager
from dataclasses import dataclass
from typing import Any, Optional, TypeVar, Union
from torch import Tensor
from .descriptors import AOTInput
from .schemas import AOTConfig, FxValue, InputAliasInfo, JointTraceFn, PreppedForAutogradTraceFn, SubclassTracingInfo, TraceFn, ViewAndMutationMeta

"""
This module is responsible for transforming functions to be traced into a form
that is easier for the downstream infra (e.g. Autograd, FX, AOTAutograd analysis)
to handle.

It does so by:
1. functionalization (including RNG functionalzation)
2. creating a joint graph when required
3. transforming mutations into extra outputs
4. dispatching subclasses
"""
def fn_input_mutations_to_outputs(fn: Callable[..., Any], args_descs: list[AOTInput], meta: ViewAndMutationMeta, keep_data_input_mutations: bool) -> Any:
    ...

@contextmanager
def disable_autocast() -> Generator[None, None, None]:
    ...

def fn_prepped_for_autograd(fn: TraceFn, args_descs: list[AOTInput], meta: ViewAndMutationMeta, aot_config: AOTConfig) -> PreppedForAutogradTraceFn:
    ...

@dataclass
class JointFnHandle:
    post_forward: Callable[..., Any] | None = ...


def create_joint(fn: Callable[..., Any], primals_descs: Optional[list[AOTInput]] = ..., *, aot_config: AOTConfig) -> Callable[..., Any]:
    ...

def create_functionalized_rng_ops_wrapper(func: Callable[..., Any], args: Any, args_descs: list[AOTInput], trace_joint: bool = ...) -> Any:
    ...

@contextmanager
def set_partitioner_tag(tag: str) -> Generator[None, None, None]:
    ...

def set_partitioner_tag_is_backward() -> AbstractContextManager[None]:
    ...

def set_partitioner_tag_must_be_in_backward() -> AbstractContextManager[None]:
    ...

def set_partitioner_tag_must_be_in_forward() -> AbstractContextManager[None]:
    ...

@dataclass
class MutationCounters:
    mc_data: int
    mc_storage: int
    mc_inductor_storage_resized: int
    ...


T = TypeVar("T")
def sc_visit(t: torch.Tensor, fn: Callable[[Tensor], T], reduce_fn: Callable[[T, T], T], accum_init: T) -> T:
    ...

def apply_in_graph_mutations(input_info: InputAliasInfo, inpt_old: Tensor, inpt_new: Tensor, f_inpt: Tensor, input_idx: int, mcs: Optional[MutationCounters] = ..., applied_mcs: Optional[MutationCounters] = ...) -> None:
    ...

def create_functionalized_fn(fn: Callable[..., Any], args: Any, args_descs: Any, *, meta: ViewAndMutationMeta, aot_config: AOTConfig, trace_joint: bool, joint_fn_handle: Optional[JointFnHandle] = ...) -> Any:
    ...

def handle_effect_tokens_fn(fn: Callable[..., Any], args: Any, args_descs: list[AOTInput], *, meta: ViewAndMutationMeta, trace_joint: bool) -> Any:
    ...

def aot_dispatch_subclass(flat_fn_maybe_joint: Union[JointTraceFn, TraceFn], args: Union[list[FxValue], tuple[list[FxValue], list[FxValue]]], args_descs: Union[list[AOTInput], tuple[list[AOTInput], list[AOTInput]]], *, is_joint_structure: bool, meta: ViewAndMutationMeta, fw_only: Callable[..., Any]) -> SubclassTracingInfo:
    ...

def create_functional_call(mod: Any, params_spec: Any, params_len: int, store_orig_mod: bool = ..., strict_out_tuple: bool = ...) -> Callable[..., Any]:
    ...

