"""
This type stub file was generated by pyright.
"""

import dataclasses
import torch
from collections.abc import Callable, Generator
from contextlib import contextmanager
from typing import Any, Optional, TYPE_CHECKING
from torch._subclasses import FakeTensor
from torch.fx.graph_module import GraphModule
from .schemas import AOTConfig, AOTGraphCapture, AOTState, FlatFn, ViewAndMutationMeta

"""
Functions in this module do most of the "work" of AOTAutograd.
An aot_dispatch_* function:
- Takes in the input flat_fn, flat_args, and some metadata
- Runs a set of pre compile wrappers (e.g. argument deduping)
- Runs the actual compiler
- Wraps the returned callable in a set of post compile wrappers
- Returns the wrapped callable and metadata.
"""
if TYPE_CHECKING:
    ...
_thread_local = ...
@contextmanager
def maybe_skip_decompose(aot_config: AOTConfig) -> Generator[None, None, None]:
    ...

zip = ...
log = ...
aot_joint_log = ...
aot_graphs_log = ...
aten = ...
DispatchReturn = tuple[Callable[..., Any], ViewAndMutationMeta]
def aot_stage1_graph_capture(aot_state: AOTState, orig_flat_fn: FlatFn) -> AOTGraphCapture:
    ...

def aot_stage2_export(aot_state: AOTState, aot_graph_capture: AOTGraphCapture) -> DispatchReturn:
    ...

def sanitize_aot_config(input: AOTConfig) -> AOTConfig:
    ...

def aot_stage2_compile(aot_state: AOTState, aot_graph_capture: AOTGraphCapture, partition_fn: Callable, fw_compiler: Callable, bw_compiler: Optional[Callable] = ..., inference_compiler: Optional[Callable] = ...) -> DispatchReturn:
    ...

def aot_stage2_inference(aot_state: AOTState, aot_graph_capture: AOTGraphCapture) -> DispatchReturn:
    """
    Handles functions that don't need autograd. Runs wrappers and compiles with fw_compiler.
    """
    ...

def collect_fw_donated_buffer_idxs(fw_ins: list[Optional[FakeTensor]], user_fw_outs: list[Optional[FakeTensor]], bw_outs: list[Optional[FakeTensor]], saved_tensors: list[FakeTensor | None]) -> list[int]:
    """
    Checks if the saved tensors are donated buffers, which means a saved tensor is not
    an alias of any tensors in fw_ins, user_fw_outs, and bw_outs.
    """
    ...

def collect_bw_donated_buffer_idxs(fw_module: torch.fx.GraphModule, bw_module: torch.fx.GraphModule, fw_metadata: ViewAndMutationMeta) -> list[int]:
    """
    Collects backward donated buffer indexes from fw_module and bw_module.
    """
    ...

@dataclasses.dataclass
class InvokeSubgraphHopGraphs:
    """
    A data structure to hold all the information needed to partition the
    `joint_hop_gm` and joint graph and the restitch the `new_fw_hop_gm` and
    `new_bw_hop_gm` into the bigger `joint_gm`.
    """
    partitioning_done: bool = ...
    old_num_fw_outputs: Optional[int] = ...
    old_num_fw_inputs: Optional[int] = ...
    new_fw_hop_gm: Optional[torch.fx.GraphModule] = ...
    new_bw_hop_gm: Optional[torch.fx.GraphModule] = ...
    new_num_sym_nodes: Optional[int] = ...
    new_num_saved_nodes: Optional[int] = ...


def prepare_for_partitioner(mod: torch.fx.GraphModule, num_primals: int, num_fw_outputs: int) -> torch.fx.GraphModule:
    ...

def run_joint_graph_passes_on_hops(joint_gm: torch.fx.GraphModule, joint_inputs: Any, aot_config: AOTConfig) -> torch.fx.GraphModule:
    """
    This pass runs the joint graph passes on the HOP graph. In torch.compile, we
    typically have many passes which work on the joint graph and then end with a
    partitioner.


    The partitioner part is quite mechanical to handle. HOP have their own
    forward and backward graph. The process can be broken into following steps

    1) Get a `joint_hop_gm` from the `fw_hop_gm` and `bw_hop_gm`
    2) Run joint graph passes on the `joint_hop_gm` to get `new_fw_hop_gm` and `new_bw_hop_gm`
    3) Stitch the `new_fw_hop_gm` and `new_bw_hop_gm` back into the `joint_gm`.

    The terminology used in the code is
    `joint_graph/joint_gm` : Refers to the main graph. This may contain many HOPs which have their own `hop_graph`
    `fw_hop_graph/fw_hop_gm` : Refers to the forward graph associated with a HOP.
    `bw_hop_graph/bw_hop_gm` : Refers to the backward graph associated with a HOP.
    `joint_hop_graph/joint_hop_gm` : Refers to the subgraph associated with the HOP like invoke_subgraph.
    `new_fw_hop_graph/new_fw_hop_gm` : Refers to the forward graph after partitioning is applied to `joint_hop_gm`.
    `new_bw_hop_graph/new_bw_hop_gm` : Refers to the backward graph after partitioning is applied to `joint_hop_gm`.

    NB: This pass works for invoke_subgraph today because we took extra care in
    the Autograd.Dispatch key of invoke_subgraph to vastly simplify Step 1.
    """
    ...

def maybe_log_graph(gm: torch.fx.GraphModule, graph_name: str, aot_config: AOTConfig, structured_log_prefix_fn: Callable[[], str], out_structured_logs: Optional[list[str]] = ...) -> None:
    ...

def create_wrap_fn(fn: Callable[..., Any], args: tuple[Any, ...]) -> tuple[Callable[..., Any], tuple[Any, ...]]:
    ...

def prepare_hook_gm(aot_config: AOTConfig, fn: Callable[..., Any], args: tuple[Any, ...]) -> torch.fx.GraphModule:
    ...

def maybe_inline_graph_saved_tensors_hooks(fw_module: torch.fx.GraphModule, bw_module: torch.fx.GraphModule, num_inner_fwd_outputs: int, inner_meta: ViewAndMutationMeta, aot_config: AOTConfig, static_input_indices: list[int]) -> None:
    ...

def aot_stage2_autograd(aot_state: AOTState, aot_graph_capture: AOTGraphCapture) -> DispatchReturn:
    """
    Autograd logic. Generates a joint graph, partitions it, manipulates the input with various wrappers,
    and returns a wrapped torch.autograd.Function with a forward and backward.
    """
    ...

