"""
This type stub file was generated by pyright.
"""

from collections.abc import Iterator, MutableMapping
from typing import Generic, Optional, TypeVar

K = TypeVar("K")
V = TypeVar("V")
class IndexedDict(MutableMapping[K, V], Generic[K, V]):
    """A dict that maintains insertion order with O(1) index access."""
    __slots__ = ...
    def __init__(self) -> None:
        ...
    
    def __setitem__(self, key: K, value: V) -> None:
        ...
    
    def __getitem__(self, key: K) -> V:
        ...
    
    def __delitem__(self, key: K) -> None:
        ...
    
    def __len__(self) -> int:
        ...
    
    def __iter__(self) -> Iterator[K]:
        ...
    
    def __contains__(self, key: object) -> bool:
        ...
    
    def next_key(self, key: K) -> Optional[K]:
        """Get the next key in insertion order. O(1)."""
        ...
    
    def prev_key(self, key: K) -> Optional[K]:
        """Get the previous key in insertion order. O(1)."""
        ...
    


