"""
This type stub file was generated by pyright.
"""

import torch
from collections.abc import Callable, Iterable, Sequence
from typing import Any, Optional, TYPE_CHECKING, TypeVar, Union
from torch import SymInt, Tensor
from torch.types import IntLikeType
from .descriptors import AOTInput, AOTOutput
from .schemas import FakifiedFlatArgs, FxValue, MemoryFormatMeta, PlainTensorMeta, SubclassCreationMeta, ViewAndMutationMeta

"""
This file contains utilities for tracing through __torch_dispatch__ based tensor subclasses and modes.
AOTAutograd's responsibility is to trace through all pytorch capabilities that live in the pytorch dispatcher,
and this includes tensor subclasses that implement __torch_dispatch__.
"""
if TYPE_CHECKING:
    ...
zip = ...
T = TypeVar("T", bound=torch.Tensor)
def requires_subclass_dispatch(args: FakifiedFlatArgs, fw_metadata: ViewAndMutationMeta) -> bool:
    ...

def maybe_suggest_memory_format(t: Tensor, with_memory_format: bool) -> Optional[MemoryFormatMeta]:
    ...

def get_subclass_typing_container(tensor_subclass: torch.Tensor) -> dict[type[torch.Tensor], list[type[torch.Tensor]]]:
    """
    Given a subclass, returns a recursive dictionary mapping each
    inner tensors to its' subclass types.
    """
    ...

def create_subclass_metadata(a: Any, start_idx: int, count_symints: bool, with_memory_format: bool = ...) -> tuple[Any, int]:
    ...

def create_subclass_meta(curr_args: Union[list[Any], tuple[Any, ...]], *, count_symints: bool = ..., with_memory_format: bool = ...) -> list[Union[PlainTensorMeta, SubclassCreationMeta]]:
    ...

def enumerate_filter_symints(lst: Iterable[IntLikeType]) -> list[tuple[int, SymInt]]:
    ...

def compute_symint_placeholders(lst: Iterable[Union[None, int, SymInt]]) -> list[bool]:
    ...

AOTDescriptor = TypeVar("AOTDescriptor", AOTInput, AOTOutput)
def unwrap_tensor_subclasses(wrapped_args: list[FxValue], wrapped_args_descs: list[AOTDescriptor], *, append_symints: bool) -> tuple[list[FxValue], list[AOTDescriptor]]:
    ...

def runtime_unwrap_tensor_subclasses(wrapped_args: list[Tensor | int], *, append_symints: bool, subclass_metas: list[PlainTensorMeta | SubclassCreationMeta] | None = ...) -> list[Any]:
    ...

def unwrap_tensor_subclasses_with_indices_to_original(wrapped_args: list[Any]) -> tuple[list[Any], list[int]]:
    ...

def remap_unwrapped_subclass_arg_indices(wrapped_args: list[Any], static_input_indices: list[int]) -> list[int]:
    ...

def wrap_tensor_subclasses(unwrapped_args: Sequence[Any], *, subclass_metas: list[PlainTensorMeta | SubclassCreationMeta], num_fw_outs_saved_for_bw: int | None = ..., included_subclass_symints: bool = ..., is_runtime: bool = ..., make_subclass_override: Callable[..., Any] | None = ...) -> tuple[Any, ...]:
    ...

def wrap_tensor_subclasses_maybe_joint(unwrapped_args: Sequence[Any], *, is_joint_structure: bool, meta: ViewAndMutationMeta) -> tuple[Any, ...]:
    ...

def compute_inner_mutated_inp_indices_from_subclass_meta(fw_metadata: ViewAndMutationMeta, inner_metadata: ViewAndMutationMeta) -> list[int]:
    ...

